### ISSUE TITLE
[Bug] Yarn install ignores changes in patched dependencies

### ISSUE THREAD

**Issue by goszczynskip** [yarnpkg/berry#1097]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Patching dependencies of external package doesn't trigger change in resolved packages.

**To Reproduce**

My package json:
```
{
  "name": "bug",
  "version": "0.1.0",
  "dependencies": {
    "@craco/craco": "patch:@craco/craco@npm:5.6.3#./craco.patch",
    ...
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.0",
    "typescript": "~3.7.2"
  },
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
 ...
}
```

Patch file:
```
diff --git a/lib/args.js b/lib/args.js
index 24770be..bc6d35b 100644
--- a/lib/args.js
+++ b/lib/args.js
@@ -1,4 +1,4 @@
-const { isNil } = require("lodash");
+const isNil = require("lodash.isnil");

 const VERBOSE_ARG = "--verbose";
 const CONFIG_ARG = "--config";
diff --git a/package.json b/package.json
index c701a9e..907da0b 100644
--- a/package.json
+++ b/package.json
@@ -41,6 +41,7 @@
     "dependencies": {
         "cross-spawn": "^7.0.0",
         "lodash.mergewith": "^4.6.2",
+        "lodash.isnil": "^4.0.0",
         "webpack-merge": "^4.2.2"
     },
     "version": "5.6.3",
```

Code above should change package.json dependencies of `@craco/craco`. After installing with patch and running `yarn start` I'm gettig error of missing `lodash.isnil` dependency. 

Command output:
```
D:\workspace\temp\yarn-berry-bug\bug>yarn start
D:\workspace\temp\yarn-berry-bug\bug\.pnp.js:25169
    throw firstError;
    ^

Error: @craco/craco tried to access lodash.isnil, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: lodash.isnil (via "lodash.isnil")
Required by: @craco/craco@virtual:512ec774d7af5bda4105a69793d47ce99cfda9c2b3f54617651f51e889f89ca8b74ef30f25142ef3d5b8a03124032b2d2e892cffe45a7ba68140a2cc830b2979#patch:@craco/craco@npm%3A5.6.3#./craco.patch::version=5.6.3&hash=4c5b9b&locator=bug%40w
orkspace%3A. (via /D:/workspace/temp/yarn-berry-bug/bug/.yarn/$$virtual/@craco-craco-virtual-3c722cd8ef/0/cache/@craco-craco-patch-2e52937673-2.zip/node_modules/@craco/craco/lib/)

Require stack:
- D:\workspace\temp\yarn-berry-bug\bug\.yarn\$$virtual\@craco-craco-virtual-3c722cd8ef\0\cache\@craco-craco-patch-2e52937673-2.zip\node_modules\@craco\craco\lib\args.js
- D:\workspace\temp\yarn-berry-bug\bug\.yarn\$$virtual\@craco-craco-virtual-3c722cd8ef\0\cache\@craco-craco-patch-2e52937673-2.zip\node_modules\@craco\craco\scripts\start.js
    at Object.makeError (D:\workspace\temp\yarn-berry-bug\bug\.pnp.js:18434:34)
    at resolveToUnqualified (D:\workspace\temp\yarn-berry-bug\bug\.pnp.js:25794:37)
    at resolveRequest (D:\workspace\temp\yarn-berry-bug\bug\.pnp.js:25884:27)
    at Object.resolveRequest (D:\workspace\temp\yarn-berry-bug\bug\.pnp.js:25952:26)
    at Function.module_1.Module._resolveFilename (D:\workspace\temp\yarn-berry-bug\bug\.pnp.js:25147:34)
    at Function.module_1.Module._load (D:\workspace\temp\yarn-berry-bug\bug\.pnp.js:25032:40)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (D:\workspace\temp\yarn-berry-bug\bug\.yarn\$$virtual\@craco-craco-virtual-3c722cd8ef\0\cache\@craco-craco-patch-2e52937673-2.zip\node_modules\@craco\craco\lib\args.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
``` 
**Environment:**

 - OS: Windows 10 1909 Build 18363.720
 - Node version 13.2.0
 - Yarn version 2.0.0-rc.30

**Comment by arcanis** [comment]
This is expected. Patching occurs during the fetching step, which is after the resolution step. By the time the patching occurs, the dependency tree has already been completely resolved.

To achieve this effect, use [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions) as well as your patch.

**Comment by merceyz** [comment]
Upstream PR https://github.com/gsoft-inc/craco/pull/150
