### ISSUE TITLE
Yarn2 cannot install @vue/cli

### ISSUE THREAD

**Issue by nickbreen** [yarnpkg/berry#1222]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When adding `@vue/cli` (for example) yarn2 tries to resolve versions that do not exist for dependencies.

It seems that if one generates a yarn.lock file with yarn 1.22.4 it's OK.

**To Reproduce**

Fails:

```bash
#!/usr/bin/env bash
set -ex
trap 'rm -rf .yarn* yarn.lock .pnp.js package.json' EXIT
echo '{"name": "test"}' > package.json
[ -f yarn-1.22.4.js ] || curl -JLO https://classic.yarnpkg.com/latest.js
node yarn-1.22.4.js cache clean
node yarn-1.22.4.js set version berry
node yarn-1.22.4.js cache clean
node yarn-1.22.4.js add @vue/cli
node yarn-1.22.4.js install
```

Passes:

```bash
#!/usr/bin/env bash
set -ex
trap 'rm -rf .yarn* yarn.lock .pnp.js package.json' EXIT
echo '{"name": "test"}' > package.json
[ -f yarn-1.22.4.js ] || curl -JLO https://classic.yarnpkg.com/latest.js
node yarn-1.22.4.js cache clean
node yarn-1.22.4.js add @vue/cli
node yarn-1.22.4.js set version berry
node yarn-1.22.4.js cache clean
node yarn-1.22.4.js install
```

**Environment if relevant (please complete the following information):**

 - OS: Ubuntu Focal x64
 - Node version v12.16.1
 - Yarn version 1.22.4 and 2.0.0-rc.32

**Additional context**

The failures look like this:

```
$ bash test2.sh 
+ trap 'rm -rf .yarn* yarn.lock .pnp.js package.json' EXIT
+ echo '{"name": "test"}'
+ '[' -f yarn-1.22.4.js ']'
+ node yarn-1.22.4.js cache clean
yarn cache v1.22.4
warning package.json: No license field
success Cleared cache.
Done in 1.90s.
+ node yarn-1.22.4.js set version berry
warning package.json: No license field
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /home/nick/src/test2/.yarn/releases/yarn-berry.js...
Updating /home/nick/src/test2/.yarnrc.yml...
Done!
+ node yarn-1.22.4.js cache clean
➤ YN0000: Done in 0s
+ node yarn-1.22.4.js add @vue/cli
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for apollo-codegen-core@npm:^0.36.7
    at /home/nick/src/test2/.yarn/releases/yarn-berry.js:42:105034
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000: └ Completed in 5.83s
➤ YN0000: Failed with errors in 5.83s
+ rm -rf .yarn .yarnrc.yml yarn.lock .pnp.js package.json
```

Anecdotally, each invocation seems to fail on an apollo dependency and each time it is trying to resolve a single point version past the current one available for the module. I.e. at time of writing 0.36.6 is the latest for apollo-codegen-core.

Inspecting the package.json for the @vue/cli -> @vue/cli-ui -> ... -> apollo-codegen-core appears to be correctly specifying version expressions that match the extant versions.

Changing the test to add  `@vue/cli@3.4.1` (a serendipidous typo on my part) does pass both tests. After exploring this for a while all (tested) `@vue/cli@4.x.y` fail and all (tested) `@vue/cli@3.x.y` pass.

While this could be hand-waved away as an issue with that particular package, that npm and yarn 1.22.4 can resolve these dependencies correctly and 2.0.0-rc.32 or 2.0.0-rc.31 cannot is strange.

**Comment by nickbreen** [comment]
```
$ yarn add -D @vue/cli
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for @apollographql/apollo-tools@npm:^0.4.6
    at /home/nick/src/test1/.yarn/releases/yarn-berry.js:42:105034
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
➤ YN0000: └ Completed in 7.83s
➤ YN0000: Failed with errors in 7.83s
```
```
$ yarn npm info --json @apollographql/apollo-tools | jq .versions | tail
  "0.4.4",
  "0.4.5",
  "0.4.6-alpha.0"
]
```

```
$ yarn add -D @vue/cli
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for apollo-codegen-core@npm:^0.36.7
    at /home/nick/src/test1/.yarn/releases/yarn-berry.js:42:105034
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
➤ YN0000: └ Completed in 13.02s
➤ YN0000: Failed with errors in 13.02s
```
```
$ yarn npm info --json apollo-codegen-core | jq .versions | tail
  "0.36.5",
  "0.36.6-0.36.6-alpha.2.0",
  "0.36.6-alpha.0",
  "0.36.6-alpha.1",
  "0.36.6",
  "1.0.0-alpha.80",
  "1.0.0-alpha.81",
  "1.0.0-alpha.82",
  "1.0.0-beta.82",
  "1.0.0-beta.84",
  "1.0.0-beta.85",
  "1.0.0-beta.87",
  "1.0.0-beta.89"
]
```

```
$ npm add -D @vue/cli
$ npm ls apollo-codegen-core
test1@
└─┬ @vue/cli@4.3.1
  └─┬ @vue/cli-ui@4.3.1
    └─┬ vue-cli-plugin-apollo@0.21.3
      └─┬ apollo@2.27.0
        ├── apollo-codegen-core@0.36.6 
        ├─┬ apollo-codegen-flow@0.34.6
        │ └── apollo-codegen-core@0.36.6  deduped
        ├─┬ apollo-codegen-scala@0.35.6
        │ └── apollo-codegen-core@0.36.6  deduped
        ├─┬ apollo-codegen-swift@0.36.6
        │ └── apollo-codegen-core@0.36.6  deduped
        └─┬ apollo-codegen-typescript@0.36.6
          └── apollo-codegen-core@0.36.6  deduped
```

```
$ yarn add @vue/cli
$ yarn why apollo-codegen-core
yarn why v1.22.4
warning package.json: No license field
[1/4] Why do we have the module "apollo-codegen-core"...?
[2/4] Initialising dependency graph...
warning test1: No license field
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "apollo-codegen-core@0.36.6"
info Reasons this module exists
   - "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo" depends on it
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-flow#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-scala#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-swift#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-typescript#apollo-codegen-core"
info Disk size without dependencies: "1.9MB"
info Disk size with unique dependencies: "9.15MB"
info Disk size with transitive dependencies: "46.22MB"
info Number of shared dependencies: 69
Done in 1.07s.
```

```
$ yarn add @vue/cli
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for apollo-codegen-flow@npm:^0.34.7
    at /home/nick/src/test3/.yarn/releases/yarn-berry.js:42:105034
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000: └ Completed in 13.17s
➤ YN0000: Failed with errors in 13.17s
```
```
$ npm info --json apollo-codegen-flow | jq .versions | tail
  "0.34.5",
  "0.34.6-0.34.6-alpha.2.0",
  "0.34.6-alpha.0",
  "0.34.6-alpha.1",
  "0.34.6",
  "1.0.0-alpha.80",
  "1.0.0-alpha.81",
  "1.0.0-alpha.82",
  "1.0.0-beta.82",
  "1.0.0-beta.84",
  "1.0.0-beta.85",
  "1.0.0-beta.87",
  "1.0.0-beta.89"
]
```
```
$ yarn add @vue/cli-ui
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for apollo-codegen-core@npm:^0.36.7
    at /home/nick/src/test3/.yarn/releases/yarn-berry.js:42:105034
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000: └ Completed in 3.1s
➤ YN0000: Failed with errors in 3.1s
```

```
$ yarn add vue-cli-plugin-apollo
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for apollo-codegen-scala@npm:^0.35.7
    at /home/nick/src/test3/.yarn/releases/yarn-berry.js:42:105034
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000: └ Completed in 0.97s
➤ YN0000: Failed with errors in 0.97s
```
```
$ yarn add vue-cli-plugin-apollo
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for apollo-graphql@npm:^0.4.2
    at /home/nick/src/test3/.yarn/releases/yarn-berry.js:42:105034
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000: └ Completed in 0.95s
➤ YN0000: Failed with errors in 0.95s
```
```
$ npm info --json apollo-codegen-scala | jq .versions | tail 
  "0.35.6",
  "1.0.0-alpha.80",
  "1.0.0-alpha.81",
  "1.0.0-alpha.82",
  "1.0.0-beta.82",
  "1.0.0-beta.84",
  "1.0.0-beta.85",
  "1.0.0-beta.87",
  "1.0.0-beta.89"
]
```
```
$ npm info --json apollo-graphql | jq .versions | tail 
  "0.3.4-alpha.0",
  "0.3.4-alpha.1",
  "0.3.4",
  "0.3.5",
  "0.3.6",
  "0.3.7",
  "0.4.0",
  "0.4.1",
  "0.4.2-alpha.0"
]
```
```
$ npm info --json vue-cli-plugin-apollo versions dependencies devDependencies
{
  "versions": [
    "0.0.1",
    "0.0.2",
    "0.0.3",
    "0.0.4",
    "0.0.5",
    "0.1.0",
    "0.1.1",
    "0.1.2",
    "0.2.0",
    "0.2.1",
    "0.3.0",
    "0.4.0",
    "0.4.1",
    "0.5.0",
    "0.6.0",
    "0.6.1",
    "0.7.0",
    "0.7.1",
    "0.7.2",
    "0.7.3",
    "0.7.4",
    "0.7.5",
    "0.7.6",
    "0.7.7",
    "0.7.8",
    "0.7.9",
    "0.7.10",
    "0.8.0",
    "0.8.1",
    "0.8.2",
    "0.8.3",
    "0.9.0",
    "0.10.0",
    "0.10.1",
    "0.10.2",
    "0.10.3",
    "0.10.4",
    "0.11.0",
    "0.11.1",
    "0.11.2",
    "0.11.3",
    "0.11.4",
    "0.12.0",
    "0.12.1",
    "0.13.0",
    "0.13.1",
    "0.13.2",
    "0.13.3",
    "0.13.4",
    "0.13.5",
    "0.13.6",
    "0.13.7",
    "0.13.8",
    "0.13.9",
    "0.14.0",
    "0.14.1",
    "0.14.2",
    "0.14.3",
    "0.14.4",
    "0.14.5",
    "0.14.6",
    "0.15.0",
    "0.16.0",
    "0.16.1",
    "0.16.2",
    "0.16.3",
    "0.16.4",
    "0.16.5",
    "0.16.6",
    "0.17.0",
    "0.17.1",
    "0.17.2",
    "0.17.3",
    "0.17.4",
    "0.18.0",
    "0.18.1",
    "0.19.0",
    "0.19.1",
    "0.19.2",
    "0.20.0",
    "0.21.0",
    "0.21.1",
    "0.21.2",
    "0.21.3"
  ],
  "dependencies": {
    "apollo": "^2.20.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-http": "^1.5.16",
    "apollo-link-persisted-queries": "^0.2.2",
    "apollo-link-state": "^0.4.2",
    "apollo-link-ws": "^1.0.19",
    "apollo-server-express": "^2.9.6",
    "apollo-upload-client": "^11.0.0",
    "apollo-utilities": "^1.3.2",
    "chalk": "^2.4.2",
    "deepmerge": "^4.1.1",
    "dotenv": "^8.2.0",
    "esm": "^3.2.25",
    "execa": "^3.2.0",
    "express": "^4.17.1",
    "fs-extra": "^8.1.0",
    "graphql": "^14.5.8",
    "graphql-subscriptions": "^1.1.0",
    "graphql-tag": "^2.10.1",
    "graphql-tools": "^4.0.5",
    "node-fetch": "^2.6.0",
    "nodemon": "^1.19.4",
    "subscriptions-transport-ws": "^0.9.16",
    "ts-node": "^8.4.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.0.1",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^5.2.3",
    "vuepress": "^0.14.8"
  }
}
```

**Comment by nickbreen** [comment]
I think I've isolated it down to `vue-cli-plugin-apollo` < `@vue/cli-ui` < `@vue/cli`

**Comment by nickbreen** [comment]
Anecdotally, it seems that the packages that are attempting to resolve a 'future' version also have an alpha/beta version.

**Comment by nickbreen** [comment]
# Workaround 1

Define a workspace package to 'mask' `@vue/cli-ui` (e.g. `packages/@vue/cli-ui`) with no dependencies: 

```
{
  "name": "@vue/cli-ui",
  "version": "0.0.0",
  "description": "mask the real @vue/cli-ui as it's broken dependencies break yarn2 somehow"
}
```

Force workspace resolution for it in `.yarnrc.yml` with:

```

packageExtensions:
  "@vue/cli@*":
    dependencies:
      "@vue/cli-ui": "workspace:*"
```

**Comment by nickbreen** [comment]
For `yarn add -D @vue-cli-plugin-apollo@x.y.z`
- 0.21.x all fail to install
- 0.20.0 installs

0.21.0 added `apollo` (among others) as a new dependency.

**Comment by nickbreen** [comment]
# Workaround 2

```
packageExtensions:
  "@vue/cli-ui@*":
    dependencies:
      vue-cli-plugin-apollo: "0.20.0"
```

**Comment by nickbreen** [comment]
# Workaround 3
```
{
  ...
  "resolutions": {
    "@vue/cli-ui/vue-cli-plugin-apollo": "0.20.0"
  }
}
```

**Comment by arcanis** [comment]
Can you try to set a `resolutions` field on `apollo-codegen-core` to a version that exists, then once the install succeeds run `yarn why apollo-codegen-core` to see who's depending on it, to see which package should be fixed.

**Comment by nickbreen** [comment]
I think I've isolated it to `vue-cli-plugin-apollo`, at least pinning _that_ to 0.20.0.

It seems to flip/flop between failing on apollo-env, various apollo-codegen-XXXX, and one time @apollographql/apollo-tools! 

So there's some in-determinism for exactly which dependency fails... I'm assuming that it's simply the _first_ one that fails aborts the install.

**Comment by nickbreen** [comment]
```
info Reasons this module exists
   - "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo" depends on it
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-flow#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-scala#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-swift#apollo-codegen-core"
   - Hoisted from "@vue#cli#@vue#cli-ui#vue-cli-plugin-apollo#apollo#apollo-codegen-typescript#apollo-codegen-core"
```

**Comment by nickbreen** [comment]
```
$ npm info --json apollo  dependencies | grep codegen-core
  "apollo-codegen-core": "^0.36.6",
$ npm info --json apollo  dependencies | grep codegen-core
  "apollo-codegen-core": "^0.36.6",
nick@white:~/src/test1$ npm info --json apollo-codegen-flow dependencies | grep codegen-core
  "apollo-codegen-core": "^0.36.6",
nick@white:~/src/test1$ npm info --json apollo-codegen-scala dependencies | grep codegen-core
  "apollo-codegen-core": "^0.36.6",
nick@white:~/src/test1$ npm info --json apollo-codegen-swift dependencies | grep codegen-core
  "apollo-codegen-core": "^0.36.6",
nick@white:~/src/test1$ npm info --json apollo-codegen-typescript dependencies | grep codegen-core
  "apollo-codegen-core": "^0.36.6",



```

**Comment by arcanis** [comment]
I've sent a message, hopefully they'll be able to fix it soon 😕

https://github.com/apollographql/apollo-tooling/commit/9d8ffb07d4b4a661b4adda787646e256d130c75d#commitcomment-38665787

**Comment by nickbreen** [comment]
Hmm, setting a resolution for apollo 2.72.0 works too.

apollo 2.27.2 was released 5 days ago, which more-or-less correlates to when this started going a bit weird.

**Comment by nickbreen** [comment]
OK, I'm good with that. 

Have workarounds. Will Close.

TYVM.

**Comment by arcanis** [comment]
Our tests now pass, the Apollo team released the missing packages.
