### ISSUE TITLE
[Question] How can I fix relative require in lerna repo?

### ISSUE THREAD

**Issue by MrEfrem** [yarnpkg/berry#1238]
This package https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection-fast.js#L15 uses relative require to another package in Lerna:

```js
const { parse, serialize } = require('../../pg-protocol/dist')
```

I use `Webpack` with `babel-loader` and `pnp-webpack-plugin` and I receive this error when I try to compile my sources:
```
ERROR in ./.yarn/cache/pg-npm-8.0.3-a4ca4af1dd-2.zip/node_modules/pg/lib/connection-fast.js
Module not found: Error: Can't resolve '../../pg-protocol/dist' in '/Users/aleksandr/WebProjects/test/.yarn/cache/pg-npm-8.0.3-a4ca4af1dd-2.zip/node_modules/pg/lib'
 @ ./.yarn/cache/pg-npm-8.0.3-a4ca4af1dd-2.zip/node_modules/pg/lib/connection-fast.js 15:29-62
 @ ./.yarn/cache/pg-npm-8.0.3-a4ca4af1dd-2.zip/node_modules/pg/lib/client.js
 @ ./.yarn/cache/pg-npm-8.0.3-a4ca4af1dd-2.zip/node_modules/pg/lib/index.js
 @ ./.yarn/$$virtual/knex-virtual-00314689e9/0/cache/knex-npm-0.21.0-2cca93e051-2.zip/node_modules/knex/lib/dialects/postgres/index.js
 @ ./.yarn/$$virtual/knex-virtual-00314689e9/0/cache/knex-npm-0.21.0-2cca93e051-2.zip/node_modules/knex/lib/dialects sync ^\.\/.*\/index\.js$
 @ ./.yarn/$$virtual/knex-virtual-00314689e9/0/cache/knex-npm-0.21.0-2cca93e051-2.zip/node_modules/knex/lib/knex.js
 @ ./.yarn/$$virtual/knex-virtual-00314689e9/0/cache/knex-npm-0.21.0-2cca93e051-2.zip/node_modules/knex/lib/index.js
 @ ./.yarn/$$virtual/knex-virtual-00314689e9/0/cache/knex-npm-0.21.0-2cca93e051-2.zip/node_modules/knex/knex.js
 @ ./src/index.js
```

**Comment by arcanis** [comment]
Oh my, that's horrendous. Sorry, my best suggestion is to send a PR to make them use a proper dependency 🤔

**Comment by arcanis** [comment]
Interestingly they actually have the dependency on `pg-protocol`. I suspect the relative require is setup this way to emulate workspaces (since it'll load the local files when operating from within the repo, and the n_m files when operating from the consumer). Still, this isn't a good practice: they should use the builtin Yarn workspaces that make all that transparent.

**Comment by MrEfrem** [comment]
oh, but can I patch it myself via `patch:` protocol for example?

**Comment by MrEfrem** [comment]
@arcanis also I've still one error:
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1.75s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2.38s
➤ YN0000: ┌ Link step
➤ YN0007: │ libpq@npm:1.8.9 must be built because it never did before or the last one failed
➤ YN0009: │ libpq@npm:1.8.9 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/v9/cj318yz96_n6yc9g_6lk3g4r0000gn/T/xfs-f8b05402/build.log)
➤ YN0009: │ libpq@npm:1.8.9 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/v9/cj318yz96_n6yc9g_6lk3g4r0000gn/T/xfs-f8b05402/build.log)
➤ YN0000: └ Completed in 3.82s
➤ YN0000: Failed with errors in 8.17s
```

`build.log`:
```
# This file contains the result of Yarn building a package (libpq@npm:1.8.9)
# Script code: node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.16.2 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/aleksandr/WebProjects/test/.yarn/unplugged/node-gyp-npm-6.1.0-6c401fe21b/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aleksandr/WebProjects/test/.yarn/unplugged/libpq-npm-1.8.9-a860dc39eb/node_modules/libpq/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aleksandr/WebProjects/test/.yarn/unplugged/node-gyp-npm-6.1.0-6c401fe21b/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aleksandr/Library/Caches/node-gyp/12.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/aleksandr/Library/Caches/node-gyp/12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/aleksandr/WebProjects/test/.yarn/unplugged/node-gyp-npm-6.1.0-6c401fe21b/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/aleksandr/Library/Caches/node-gyp/12.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/aleksandr/WebProjects/test/.yarn/unplugged/libpq-npm-1.8.9-a860dc39eb/node_modules/libpq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/aleksandr/WebProjects/test/.yarn/unplugged/node-gyp-npm-6.1.0-6c401fe21b/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/aleksandr/.nvm/versions/node/v12.16.2/bin/node" "/Users/aleksandr/WebProjects/test/.yarn/unplugged/node-gyp-npm-6.1.0-6c401fe21b/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aleksandr/WebProjects/test/.yarn/unplugged/libpq-npm-1.8.9-a860dc39eb/node_modules/libpq
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
```

Actually I use `KnexJs` for which I was had to do so fixes:
```
packageExtensions:
  'knex@*':
    dependencies:
      'mssql': '*'
      'mysql': '*'
      'mysql2': '*'
      'oracledb': '*'
      'pg-query-stream': '*'
      'sqlite3': '*'
      'tedious': '*'
  'node-pre-gyp@*':
    dependencies:
      'aws-sdk': '*'
  'pg@*':
    dependencies:
      'pg-native': '*'
```
But errors for these fixes I see only when I use `Webpack + babel-loader + pnp-webpack-plugin` and I don't see them when I run my sources locally with `require('@babel/register')`.

**Comment by MrEfrem** [comment]
@arcanis `Knex` library uses PEER dependencies to different dialects of SQL databases:
1. peerDependencies: https://github.com/knex/knex/blob/master/package.json#L49
2. peerDependenciesMeta: https://github.com/knex/knex/blob/master/package.json#L56
3. https://github.com/knex/knex/tree/master/lib/dialects
And `Knex` conditionally loads them according to selected dialect in my configuration. But as I mentioned above `Webpack + babel-loader + pnp-webpack-plugin` could compile my sources only with list of those `packageExtensions` and therefore I also received that error in process of running `yarn install` (`/bin/sh: pg_config: command not found`).
It really isn't very well that I should explicitly install ALL dialects though I plan to use only one. And now I can't install all correctly because of that error above.
