### ISSUE TITLE
Get an error when I try to install a package with a tag [Bug]

### ISSUE THREAD

**Issue by dxvladislavvolkov** [yarnpkg/berry#1267]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I try to install a package with a tag and get an error after it.
It happens with a 2.0.0-rc.27 version. It seems like a regression.

> YN0001: │ Error: devextreme@19.2-stable isn't supported by any available resolver

**To Reproduce**
<details>
  <summary>Reproduction</summary>

  ```js repro
  1. yarn init
  2. yarn add devextreme@19.2-stable

  ```
</details>

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version v12.16.1
 - Yarn version 2.0.0-rc.27

**Additional context**

**Comment by paul-soporan** [comment]
<details>

<summary>Sherlock Reproduction</summary>

---

[Playground](https://yarnpkg.com/playground?code=Y29uc3QgaW5zdGFsbFByb21pc2UgPSBwYWNrYWdlSnNvbkFuZEluc3RhbGwoew0KICBkZXBlbmRlbmNpZXM6IHsNCiAgICBbYGRldmV4dHJlbWVgXTogYDE5LjItc3RhYmxlYCwNCiAgfSwNCn0pOw0KDQphd2FpdCBleHBlY3QoaW5zdGFsbFByb21pc2UpDQogIC5yZXNvbHZlcy50b0JlVHJ1dGh5KCk7DQo%3D)

```js repro
const installPromise = packageJsonAndInstall({

dependencies: {

[`devextreme`]: `19.2-stable`,

},

});



await expect(installPromise)

.resolves.toBeTruthy();


```

Output:

```
Error: [2mexpect([22m[31mreceived[39m[2m).[22mresolves[2m.[22mtoBeTruthy[2m()[22m

Received promise rejected instead of resolved
Rejected to value: [31m[Error: Command failed: /usr/local/bin/node /sandbox/berry/scripts/actions/../run-yarn.js install·[39m
[31m➤ YN0000: ┌ Resolution step[39m
[31m➤ YN0001: │ Error: devextreme@19.2-stable isn't supported by any available resolver[39m
[31m    at MultiResolver.getResolverByDescriptor (/sandbox/berry/packages/yarnpkg-core/sources/MultiResolver.ts:67:13)[39m
[31m    at MultiResolver.getResolverByDescriptor [as bindDescriptor] (/sandbox/berry/packages/yarnpkg-core/sources/MultiResolver.ts:31:27)[39m
[31m    at bindDescriptor (/sandbox/berry/packages/yarnpkg-core/sources/Project.ts:775:34)[39m
[31m➤ YN0000: └ Completed[39m
[31m➤ YN0000: Failed with errors in 0.04s[39m
[31m][39m
at expect (/sandbox/node_modules/expect/build/index.js:138:15)
at module.exports (evalmachine.<anonymous>:8:7)
at executeInTempDirectory (/sandbox/node_modules/@arcanis/sherlock/lib/executeRepro.js:56:19)
at executeInTempDirectory (/sandbox/node_modules/@arcanis/sherlock/lib/executeRepro.js:17:22)
at executeRepro (/sandbox/node_modules/@arcanis/sherlock/lib/executeRepro.js:24:18)
at module.exports../pages/api/sherlock.js.__webpack_exports__.default (/sandbox/.next/server/static/development/pages/api/sherlock.js:140:122)
at Object.apiResolver (/sandbox/node_modules/next/dist/next-server/server/api-utils.js:46:15)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

---

</details>
