### ISSUE TITLE
[Bug] Your application tried to access utils, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by njj** [yarnpkg/berry#1269]
**Describe the bug**

Jest is trying to access local files through relative paths and Berry is failing on them.

```
 FAIL  client/__tests__/utils/dateTimeFormatter.spec.js
  ● Test suite failed to run

    Your application tried to access utils, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

    Required package: utils (via "utils/dateTimeFormatter.js")
    Required by: /Users/nick/Development/my-project/client/__tests__/utils/

      32670 |     enumerable: false
      32671 |   };
    > 32672 |   return Object.defineProperties(new Error(message), {
            |                                  ^
      32673 |     code: Object.assign(Object.assign({}, propertySpec), {
      32674 |       value: code
      32675 |     }),

      at Object.makeError (.pnp.js:32672:34)
      at resolveToUnqualified (.pnp.js:40021:37)
      at resolveRequest (.pnp.js:40115:27)
      at Object.resolveRequest.maybeLog [as resolveRequest] (.pnp.js:40183:26)

Running coverage on untested files...^C%
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version [e.g. 8.15.0, 10.15.1, ...]
 - Yarn version: 2.0.0-rc.32

**Comment by njj** [comment]
I was able to solve this with configuring jest correctly.

**Comment by karol1990** [comment]
@njj, could you share information what configuration change did you do ?

**Comment by merceyz** [comment]
Most likely using the `link:` protocol https://yarnpkg.com/features/protocols/#why-is-the-link-protocol-recommended-over-aliases-for-path-mapping

**Comment by Imran109** [comment]
@njj Did you find any solution for this? I am facing the same issue as well after migrating from npm to yarn.
