### ISSUE TITLE
[Bug] `yarn set version from sources` fails with an Internal Error

### ISSUE THREAD

**Issue by kapooostin** [yarnpkg/berry#1450]
- [ ] I'd be willing to implement a fix

**Describe the bug**

`yarn set version from sources` fails to install.
Below is its full console output.

```console
(node:25418) ExperimentalWarning: The dns.promises API is experimental
(node:25418) ExperimentalWarning: The fs.promises API is experimental
➤ YN0000: Fetching the latest commits

  $ git fetch origin master --force
  $ git reset --hard FETCH_HEAD
  $ git clean -dfx

➤ YN0000: Building a fresh bundle

Disabled non-requirable plugin plugin-compat: require(...).brotliDecompressSync is not a function
Disabled non-requirable plugin plugin-node-modules: require(...).brotliDecompressSync is not a function
Disabled non-requirable plugin plugin-pnp: require(...).brotliDecompressSync is not a function
(node:25447) ExperimentalWarning: The dns.promises API is experimental
(node:25447) ExperimentalWarning: The fs.promises API is experimental
Internal Error: The package @yarnpkg/monorepo@workspace:. isn't supported by any of the available linkers
    at _fslib.ZipOpenFS.openPromise (/private/var/folders/s7/g25x54d51wg_yd5jxlmr5px00000gn/T/yarnpkg-sources/packages/yarnpkg-core/sources/scriptUtils.ts:255:13)
    at Function.fn [as openPromise] (/private/var/folders/s7/g25x54d51wg_yd5jxlmr5px00000gn/T/yarnpkg-sources/packages/yarnpkg-fslib/sources/ZipOpenFS.ts:28:20)
    at Object.openPromise [as hasPackageScript] (/private/var/folders/s7/g25x54d51wg_yd5jxlmr5px00000gn/T/yarnpkg-sources/packages/yarnpkg-core/sources/scriptUtils.ts:247:26)
➤ YN0001: Error: Child "yarn" exited with exit code 1
    at ChildProcess.C.on (/path/to/project/.yarn/releases/yarn-2.0.0-rc.33.js:10:394568)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
➤ YN0000: Failed with errors in 17.21s
```

**To Reproduce**
I'm inclined to blame my machine installation and configs, but it all worked just fine until recently.

`yarn set version berry` and `yarn set version latest` install Yarn correctly.

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.14.6
 - Node version 10.15.3
 - Yarn version 2.0.0-rc.33

**Comment by merceyz** [comment]
Yarn only supports Node >= 10.19.0
https://github.com/yarnpkg/berry/blob/1fca6a33dfcba1805804ebace3874a0c1bd027dd/package.json#L89-L91

**Comment by kapooostin** [comment]
Does it say anywhere in the docs?

**Comment by kapooostin** [comment]
Updating node to 10.21 solved the issue.
