### ISSUE TITLE
[Bug] Error running doctor

### ISSUE THREAD

**Issue by abrenneke** [yarnpkg/berry#1454]
Error below:

```bash
❯ npx @yarnpkg/doctor .
npx: installed 221 in 11.172s
Type Error: yup.object(...).atMostOneOf is not a function
    at Object.<anonymous> (/home/abrenneke/.npm/_npx/24377/lib/node_modules/@yarnpkg/doctor/node_modules/@yarnpkg/plugin-npm-cli/lib/commands/npm/logout.js:50:6)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/abrenneke/.npm/_npx/24377/lib/node_modules/@yarnpkg/doctor/node_modules/@yarnpkg/plugin-npm-cli/lib/index.js:9:34)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
```

It looks like `logout.js` was added recently? (10 days ago)

I can't find a reference to `atMostOneOf` _anywhere_ in `yup` or any documentation for the function anywhere.

Commands run on existing repository:

```bash
npm install -g yarn
yarn set version berry
npx run @yarnpkg/doctor
```

**Comment by arcanis** [comment]
Seems like there was a bug in the last publish, we'll fix that and upload a new release
