### ISSUE TITLE
[Bug] Qualified path resolution failed - none of the candidates can be found on the disk.

### ISSUE THREAD

**Issue by dzintars** [yarnpkg/berry#1554]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Took an attempt to upgrade to the latest and greatest. Webpack 5, Yarn 2.36, etc. Encountering this issue.
Tried to `yarn cache clean --all` and `yarn install` because on WebPack 4 branch it helped, but no luck there.
All packages upgraded to @ latest or similar.

Any ideas?

```sh
» yarn start  
/home/dzintars/code/front/.pnp.js:16788
    throw firstError;
    ^

Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: /home/dzintars/code/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs
Rejected candidate: /home/dzintars/code/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs
Rejected candidate: /home/dzintars/code/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs.js
Rejected candidate: /home/dzintars/code/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs.json
Rejected candidate: /home/dzintars/code/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs.node

Require stack:
- /home/dzintars/code/front/.yarn/unplugged/webpack-dev-server-virtual-85423d99a7/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at internalTools_makeError (/home/dzintars/code/front/.pnp.js:16533:34)
    at resolveUnqualified (/home/dzintars/code/front/.pnp.js:17524:13)
    at resolveRequest (/home/dzintars/code/front/.pnp.js:17548:14)
    at Object.resolveRequest (/home/dzintars/code/front/.pnp.js:17608:26)
    at Function.external_module_.Module._resolveFilename (/home/dzintars/code/front/.pnp.js:16765:34)
    at Function.external_module_.Module._load (/home/dzintars/code/front/.pnp.js:16629:48)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/dzintars/code/front/.yarn/unplugged/webpack-dev-server-virtual-85423d99a7/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
```

**Environment if relevant (please complete the following information):**

 - OS: **Linux Fedora 32**
 - Node version: **v14.5.0**
 - Yarn version: **2.0.0-rc.36.git.20200706.0d45e383**

**Comment by merceyz** [comment]
https://unpkg.com/browse/webpack-cli@4.0.0-beta.8/bin/
The file `config-yargs` doesn't exist

**Comment by dzintars** [comment]
So it seems that is the problem of `webpack-cli`
https://github.com/webpack/webpack-dev-server/issues/2029

**Comment by dzintars** [comment]
Yeah, downgrading `yarn add -D webpack-cli@3` seems fixes this issue. Tnx for hint.

**Comment by FreeYeti** [comment]
I just replaced `webpack-dev-server` with `webpack serve` in my `package.json`, then the problem solved.

My `package.json`

```javascript
"scripts": {
    "start": "NODE_ENV=dev webpack-dev-server --progress -w --env=dev",
    "build": "NODE_ENV=production NODE_ENV=production webpack --env=production"
},
```

To:

```js
"scripts": {
    "start": "NODE_ENV=dev webpack serve --progress",
    "build": "NODE_ENV=production webpack --mode=production"
},
```

**Comment by azuken** [comment]
[i18n-issue.zip](https://github.com/yarnpkg/berry/files/8462914/i18n-issue.zip)

Here !
