### ISSUE TITLE
[Bug] Crashes on old Node versions

### ISSUE THREAD

**Issue by imachug** [yarnpkg/berry#1609]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Installing `berry` via `yarn set version berry` on Node versions before v10.16.0 completes but yields the whole installation unusable.

**To Reproduce**

1. Make sure you have an old Node version, e.g. `v10.15.2`
2. `yarn set version berry`
3. Try running any yarn command, e.g. `yarn --version`

**Screenshots**

I prefer text.

```
ivanq@Ivanqs-Macbook:~/Documents/testyarn$ yarn --version
1.22.4
ivanq@Ivanqs-Macbook:~/Documents/testyarn$ yarn set version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js...
Updating /home/ivanq/Documents/testyarn/.yarnrc.yml...
Done!
ivanq@Ivanqs-Macbook:~/Documents/testyarn$ yarn --version
/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:2
module.exports=(()=>{var __webpack_modules__={49775:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-compat"}')},35729:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-dlx"}')},37904:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-essentials"}')},17508:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-file"}')},84779:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-git"}')},88454:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-github"}')},91953:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-http"}')},63756:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-init"}')},23100:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-link"}')},47047:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-node-modules"}')},31880:e=>{"use strict";e.exports=JSON.parse('{"u2":"@yarnpkg/plugin-npm-cli"}')},67310:e=>{"use strict";e.exports=JSON

TypeError: r(...).brotliDecompressSync is not a function
    at Module.80150 (/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:2:2181)
    at __webpack_require__ (/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:86:546526)
    at t.e (/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:2:444165)
    at Module.28638 (/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:2:219681)
    at __webpack_require__ (/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:86:546526)
    at module.exports (/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:86:547491)
    at Object.<anonymous> (/home/ivanq/Documents/testyarn/.yarn/releases/yarn-berry.js:86:547519)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version: v10.15.2
 - Yarn version: can't check because `yarn --version` is unavailable, latest `master` at the moment of publishing this issue

**Additional context**

This is failing because [zlib.brotliDecompressSync](https://nodejs.org/api/zlib.html#zlib_zlib_brotlidecompresssync_buffer_options) is available since v11.7.0 / v10.16.0 only.

**Comment by arcanis** [comment]
Future releases will now print an acceptable error message explaining that 10.17+ is required.
