### ISSUE TITLE
[Bug] node yarn.js run build:dev  Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by PlamenTurkedjiev** [yarnpkg/berry#1768]
Here are the error contents of the yarn-error.log

Trace: 
  Error: spawn UNKNOWN
      at ChildProcess.spawn (internal/child_process.js:358:11)
      at Object.spawn (child_process.js:533:9)
      at Promise (C:\miniconda3\envs\dev\Lib\site-packages\jupyterlab\staging\yarn.js:25588:24)
      at new Promise (<anonymous>)
      at queue.push (C:\miniconda3\envs\dev\Lib\site-packages\jupyterlab\staging\yarn.js:25587:32)
      at run (C:\miniconda3\envs\dev\Lib\site-packages\jupyterlab\staging\yarn.js:36016:7)
      at BlockingQueue.maybePushConcurrencyQueue (C:\miniconda3\envs\dev\Lib\site-packages\jupyterlab\staging\yarn.js:36031:7)
      at BlockingQueue.shift (C:\miniconda3\envs\dev\Lib\site-packages\jupyterlab\staging\yarn.js:36026:10)
      at Promise (C:\miniconda3\envs\dev\Lib\site-packages\jupyterlab\staging\yarn.js:35971:14)
      at new Promise (<anonymous>)
**To Reproduce**

[package.zip](https://github.com/yarnpkg/berry/files/5132607/package.zip)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version: 10.13.0
 - Yarn version 1.21.1

**Additional context**

I'm trying to run a `jupyter lab build ` and this command is failing

**Comment by merceyz** [comment]
Please provide an actual repro, that zip only contains a `package.json` which isn't enough.

You specified `Yarn version 1.21.1`, this is the repo for V2
