### ISSUE TITLE
upgare-interactive throws  Cannot read property 'anchoredLocator' of undefined

### ISSUE THREAD

**Issue by tomsonpl** [yarnpkg/berry#1820]
Hi,
I've previously used plugin interactive-tools to upgrade packages, all worked smoothly.
However today, it throwed an error multiple times

(node:38491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'anchoredLocator' of undefined
    at Module.F (/Users/tomaszciecierski/Projects/js/mono/.yarn/releases/yarn-2.2.2.cjs:2:23002)
    at d (/Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:39:443523)
    at /Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:39:445163
    at /Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:39:445350
    at Tr (/Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:31:40907)
    at ei (/Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:31:47951)
    at f (/Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:22:350)
    at p (/Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:22:977)
    at Timeout.x [as _onTimeout] (/Users/tomaszciecierski/Projects/js/mono/.yarn/plugins/@yarnpkg/plugin-interactive-tools.js:22:1856)
    at listOnTimeout (internal/timers.js:533:17)
(node:38491) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
(node:38491) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38491) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'anchoredLocator' of undefined

<img width="966" alt="Zrzut ekranu 2020-09-9 o 11 37 48" src="https://user-images.githubusercontent.com/16632552/92582482-4fba2380-f291-11ea-9c68-b7de007717d8.png">

Any ideas on where to dig? 

Best regards,
TC

**Comment by tomsonpl** [comment]
update from my side: 
degrading yarn from 2.2.2 to 2.1.1 resolved the issue.

**Comment by merceyz** [comment]
If you updated yarn you need to update the plugin as well

**Comment by tomsonpl** [comment]
@merceyz thanks, any idea on how to do that? ...

**Comment by merceyz** [comment]
Same way you installed it
```sh
yarn plugin import interactive-tools
```

**Comment by tomsonpl** [comment]
but there is no version specified anywhere.

**Comment by tomsonpl** [comment]
but indeed, problem solved.

**Comment by tomsonpl** [comment]
thanks

**Comment by bkarlson** [comment]
In such case shouldn't `yarn set version latest` upgrade plugins as well?

**Comment by tomsonpl** [comment]
@bkarlson yes.
