### ISSUE TITLE
[Bug] yarn link does not work inside berry repo

### ISSUE THREAD

**Issue by vlasenko** [yarnpkg/berry#184]
**Describe the bug**

`yarn link ~/ts-loader` does not work as described in the documentation (or it might be broken at the moment)

**To Reproduce**

```
cd ~
git clone git@github.com:TypeStrong/ts-loader.git
cd ~/berry/packages/berry-builder
yarn link ~/ts-loader
```

```
victor@victor-N501VW:~/work/berry/packages/berry-builder$ yarn link ~/ts-loader
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: Link-type dependencies cannot contain the character "?"
    at LinkResolver.bindDescriptor (/home/victor/work/berry/packages/berry-cli/bundles/berry.js:124531:19)
    at MultiResolver.bindDescriptor (/home/victor/work/berry/packages/berry-cli/bundles/berry.js:35929:25)
    at MultiResolver.bindDescriptor (/home/victor/work/berry/packages/berry-cli/bundles/berry.js:35929:25)
    at AliasResolver.bindDescriptor (/home/victor/work/berry/packages/berry-cli/bundles/berry.js:41163:26)
    at Promise.all.newLocators.map (/home/victor/work/berry/packages/berry-cli/bundles/berry.js:36785:59)
➤ YN0000: └ Completed in 0.27s
➤ YN0000: Failed with errors in 0.27s
```

`console.log` of `destination.range` var prior the `throw` reveals the following:
```
portal:/home/victor/ts-loader
portal:/home/victor/ts-loader
portal:/home/victor/ts-loader?locator=%40berry%2Fmonorepo%40workspace%3A.
portal:./gatsby-plugin-clipanion-cli
portal:/home/victor/ts-loader?locator=%40berry%2Fmonorepo%40workspace%3A.
```

**Comment by arcanis** [comment]
Will be fixed by #194 👍
