### ISSUE TITLE
[Feature] yarn up --exclude

### ISSUE THREAD

**Issue by xenoterracide** [yarnpkg/berry#2009]
sometimes you want to upgrade everything matching a pattern except a module or two, which follow the same pattern/namespace but are not managed under the same version/project.

```
> yarn up 'jest-*@26.5'   
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: No candidate found for jest-mock-extended@npm:26.5
    at /Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:334552
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 24)
    at async Ae.resolveEverything (/Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:334106)
    at async /Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:352716
    at async C.startTimerPromise (/Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:363457)
    at async Ae.install (/Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:352350)
    at async /Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:107509
    at async Function.start (/Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:362588)
    at async xe.execute (/Users/calebcushing/IdeaProjects/briggo/services/.yarn/releases/yarn-2.3.0.cjs:2:107437)
➤ YN0000: └ Completed in 0s 263ms
➤ YN0000: Failed with errors in 0s 266ms
```

**Comment by andreialecu** [comment]
`yarn up 'jest-!(mock-extended)@26.5'` should probably work. You can test globs at https://www.digitalocean.com/community/tools/glob

**Comment by arcanis** [comment]
The `yarn up` command is kind of a sugar to allow anyone to quickly update a package on all workspaces with low mental overhead. Adding an `exclude` flag would go against that idea, since you'd need to know *which* workspaces you want to exclude. If you're at this point, I'd recommend using `yarn workspaces foreach --all --exclude ... add` in a script (`update:lodash` for instance).

**Comment by arcanis** [comment]
Ah, my apologies, I didn't understand indeed. You need a pipe instead of `-`: `jest-!(mock|extended)`

**Comment by xenoterracide** [comment]
hmm... not quite, but it made me look again, what I really needed was this

```
yarn up 'jest*(-)!(*extended)@26.5'
```

thanks

**Comment by xenoterracide** [comment]
maybe an example of this could be added to the documentation?
