### ISSUE TITLE
[Bug] @yarnpkg/pnpify --sdk This tool can only be used with projects using Yarn Plug'n'Play

### ISSUE THREAD

**Issue by garymacpherson** [yarnpkg/berry#2152]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Unable to install pnp tools in brand new project with Berry

**To Reproduce**

```
mkdir pnptest
cd pnptest
yarn --version
    1.22.10
yarn set version berry
    Resolving berry to a url...
    Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
    Saving it into C:\Users\Me\code\pnptest\.yarn\releases\yarn-berry.cjs...
    Updating C:\Users\Me\code\pnptest/.yarnrc.yml...
    Done!
yarn --version
    2.3.3
yarn dlx @yarnpkg/pnpify --sdk vscode
    ➤ YN0000: ┌ Resolution step
    ➤ YN0000: └ Completed in 1s 467ms
    ➤ YN0000: ┌ Fetch step
    ➤ YN0000: └ Completed
    ➤ YN0000: ┌ Link step
    ➤ YN0000: └ Completed in 0s 232ms
    ➤ YN0000: Done in 1s 817ms

    Internal Error: This tool can only be used with projects using Yarn Plug'n'Play
        at SdkCommand.execute (C:\Users\Me\AppData\Local\Temp\xfs-a1075a38\dlx-3300\.yarn\$$virtual\@yarnpkg-pnpify-virtual-8a85396ffb\4\Yarn\Berry\cache\@yarnpkg-pnpify-npm-2.3.3-d139ee88e8-7.zip\node_modules\@yarnpkg\pnpify\lib\commands\SdkCommand.js:32:19)
        at SdkCommand.validateAndExecute (C:\Users\Me\AppData\Local\Yarn\Berry\cache\clipanion-npm-2.6.2-65049fe240-7.zip\node_modules\clipanion\lib\index.js:1118:37)
        at Cli.run (C:\Users\Me\AppData\Local\Yarn\Berry\cache\clipanion-npm-2.6.2-65049fe240-7.zip\node_modules\clipanion\lib\index.js:1371:38)
        at Cli.runExit (C:\Users\Me\AppData\Local\Yarn\Berry\cache\clipanion-npm-2.6.2-65049fe240-7.zip\node_modules\clipanion\lib\index.js:1388:39)
        at Object.<anonymous> (C:\Users\Me\AppData\Local\Temp\xfs-a1075a38\dlx-3300\.yarn\$$virtual\@yarnpkg-pnpify-virtual-8a85396ffb\4\Yarn\Berry\cache\@yarnpkg-pnpify-npm-2.3.3-d139ee88e8-7.zip\node_modules\@yarnpkg\pnpify\lib\cli.js:19:5)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)
        at Function.external_module_.Module._load (C:\Users\Me\AppData\Local\Temp\xfs-a1075a38\dlx-3300\.pnp.js:6169:14)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

 - OS: Windows
 - Node version 14.3.1
 - Yarn version 2.3.3

**Comment by garymacpherson** [comment]
was caused by a poor PR merge causing a committed .pnp.js to be deleted
