### ISSUE TITLE
[Bug] ➤ YN0001: │ Error: EROFS: read-only filesystem, unlink '/node_modules/@arcanis/slice-ansi'

### ISSUE THREAD

**Issue by francisu** [yarnpkg/berry#2154]
- [ ] I'd be willing to implement a fix

**Describe the bug**

yarn, on OSX, when spawned with stdit: 'inherit' is getting this error:

```
➤ YN0001: │ Error: EROFS: read-only filesystem, unlink '/node_modules/@arcanis/slice-ansi'
    at makeError (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:2197:24)
    at EROFS (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:2227:10)
    at ZipFS.unlinkSync (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:4271:30)
    at ZipFS.unlinkPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:4267:17)
    at /Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5107:26
    at /Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5368:79
    at ZipOpenFS.getZipPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5484:22)
    at ZipOpenFS.makeCallPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5368:23)
    at ZipOpenFS.unlinkPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5102:23)
    at VirtualFS.unlinkPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:2794:24)
```

This was all working fine, and (as far as I know) nothing changed and one day it stopped working. I took the opportunity to upgrade the OS to Big Sur (after I encountered the problem), and it still does not work. 

Finally, if I remove the stdio: 'inherit', it works fine.

**To Reproduce**

 - Unzip attached yarnexecuteproblem.zip
 - yarn install
 - yarn pnpify node test
 - (you will see the error)
 - yarn unplug serverless-plugin-log-subscription
 - (this, the same command, will work)

**Screenshots**

```
repoman:yarnrepro francis$ unzip yarnexecuteproblem.zip 
Archive:  yarnexecuteproblem.zip
   creating: .yarn/
   creating: .yarn/releases/
  inflating: .yarn/releases/yarn-berry.cjs  
  inflating: test.js                 
  inflating: .yarnrc.yml             
  inflating: yarn.lock               
  inflating: package.json            
repoman:yarnrepro francis$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ tunnel@npm:0.0.6 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ underscore@npm:1.11.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ util-deprecate@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ which@npm:2.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0s 450ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 232ms
➤ YN0000: Done in 0s 729ms
repoman:yarnrepro francis$ yarn pnpify node test
➤ YN0000: Will unpack serverless-plugin-log-subscription@npm:1.4.0 to /Users/francis/d/IdeaProjects/yarnrepro/.yarn/unplugged/serverless-plugin-log-subscription-npm-1.4.0-167f8b435d

➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0001: │ Error: EROFS: read-only filesystem, unlink '/node_modules/@arcanis/slice-ansi'
    at makeError (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:2197:24)
    at EROFS (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:2227:10)
    at ZipFS.unlinkSync (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:4271:30)
    at ZipFS.unlinkPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:4267:17)
    at /Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5107:26
    at /Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5368:79
    at ZipOpenFS.getZipPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5484:22)
    at ZipOpenFS.makeCallPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5368:23)
    at ZipOpenFS.unlinkPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:5102:23)
    at VirtualFS.unlinkPromise (/Users/francis/d/IdeaProjects/yarnrepro/.pnp.js:2794:24)
➤ YN0000: └ Completed in 0s 287ms
➤ YN0000: Failed with errors in 0s 451ms
repoman:yarnrepro francis$ yarn unplug serverless-plugin-log-subscription
➤ YN0000: Will unpack serverless-plugin-log-subscription@npm:1.4.0 to /Users/francis/d/IdeaProjects/yarnrepro/.yarn/unplugged/serverless-plugin-log-subscription-npm-1.4.0-167f8b435d

➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 239ms
➤ YN0000: Done in 0s 370ms
repoman:yarnrepro francis$ 

```

**Environment if relevant (please complete the following information):**

 - OS: OSX 11.0.1
 - Node version 12.16.2
 - Yarn version 2.3.3

**Additional context**

I spent some time try to reproduce this with Sherlock, but I was unable to capture the results of the yarn execution command and therefore know exactly what to compare it with.

[yarnexecuteproblem.zip](https://github.com/yarnpkg/berry/files/5575861/yarnexecuteproblem.zip)

**Comment by bgotink** [comment]
Yarn isn't meant to be executed with `pnpify`.

Executing a process with `pnpify` patches the node `fs` module to make it appear that there's a node_modules folder that contains all of your dependencies. That's a useful tool for compatibility with packages that implement their own variant of the node module resolution algorithm instead of using `require.resolve`, `resolve` or `Module.createRequire(...).resolve`.
Yarn finds the node_modules and tries to remove it, which doesn't work because the fake folder is readonly.

It doesn't succeed without `stdio: 'inherit'`, it just doesn't show the failure because any output from yarn gets suppressed. Note that even with `stdio: 'inherit'` the return code of `yarn pnpify node test` is 0.

Drop the pnpify and the command works fine:

```
bram:/var/folders/_d/ch2kc4h960d10cy_2c41qqzw0000gn/T/tmp.zp0JrC9aZ9 $ yarn node test
➤ YN0000: Will unpack serverless-plugin-log-subscription@npm:1.4.0 to /private/var/folders/_d/ch2kc4h960d10cy_2c41qqzw0000gn/T/tmp.zp0JrC9aZ9/.yarn/unplugged/serverless-plugin-log-subscription-npm-1.4.0-167f8b435d

➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 208ms
➤ YN0000: Done in 0s 363ms
```

**Comment by francisu** [comment]
> This was all working fine, and (as far as I know) nothing changed and one day it stopped working. I took the opportunity to upgrade the OS to Big Sur (after I encountered the problem), and it still does not work.
> 

<img width="1710" alt="Screen Shot 2020-11-20 at 2 10 00 PM" src="https://user-images.githubusercontent.com/944949/99854680-22fc7500-2b3a-11eb-8def-59bb02f5ea35.png">

Oops, sorry for the trouble and thanks for the education!
