### ISSUE TITLE
[Bug] Failing to install react-app dependancies with the latest yarn version

### ISSUE THREAD

**Issue by naorzr** [yarnpkg/berry#2181]
- [x] I'd be willing to implement a fix

**Describe the bug**

**To Reproduce**

I'm using yarn workspaces in one of my work projects, and since I've upgraded to typescript 4.1, I was required to also upgrade yarn to the latest version, but solving this issue, created another one, now, trying to install the dependancies for the react-app it fails with:

```
Failed to open the cache entry for @hapi/joi@npm:15.1.1: Not a zip archive
```

The full trace:
```
➤ YN0001: │ Libzip Error: Failed to open the cache entry for @hapi/joi@npm:15.1.1: Not a zip archive
    at f.makeLibzipError (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:459942)
    at new f (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:459365)
    at /Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:283988
    at Module.Q (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:408779)
    at n.factory (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:283963)
    at n.get baseFs [as baseFs] (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:443234)
    at n.existsPromise (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:452978)
    at n.existsPromise (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:452985)
    at Function.tryFind (/Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:312419)
    at /Users/foo/WebstormProjects/foo/.yarn/releases/yarn-sources.js:2:164897

```
hapi is a dependancy of a dependancy for the react-scripts package.

I've created a minimal reproducible repo, 
https://github.com/naorzr/repro-bug-yarn

Running yarn install there should yield the same error. 

**Environment if relevant (please complete the following information):**

 - OS: Mac
 - Node version 15.3
 - Yarn version: from sources

**Comment by merceyz** [comment]
Can't reproduce, your cache might have been corrupted. Could you try `yarn cache clean` (potentiall with `-all`) and see if that helps?

**Comment by naorzr** [comment]
that was it! thank you for the quick response

**Comment by benjackson1111** [comment]
Just wanted to say thank you for this - especially the --all bit! I had found someone else saying yarn cache clean but it didn't work without the --all !!!

Thanks!
