### ISSUE TITLE
[Bug] Trying to use serverless with pnp.

### ISSUE THREAD

**Issue by yoannmoinet** [yarnpkg/berry#2190]
- [x] I'd be willing to implement a fix

**Describe the bug**

I'm trying to install and use serverless in my repo that uses pnp.

But when I'm running `yarn serverless --help` once installed, I'm greated with this error:

<details>
<summary>Expand</summary>

```bash
  Error --------------------------------------------------

  Error: Cannot find module 'serverless'
      at ~/my-project/.yarn/cache/ncjsm-npm-4.1.0-16ebd5a008-03d2ecc1e2.zip/node_modules/ncjsm/lib/get-node-resolver.js:21:18
      at Function.then (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/_ext.js:65:13)
      at Deferred._settle (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:93:26)
      at Deferred.resolve (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:138:15)
      at Function.then (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/_ext.js:70:4)
      at Deferred._settle (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:93:26)
      at Deferred.resolve (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:138:15)
      at Function.then (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/_ext.js:70:4)
      at Deferred._settle (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:93:26)
      at Deferred.resolve (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:138:15)
      at Function.<anonymous> (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/ext/promise/catch.js:48:4)
      at Deferred._settle (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:93:26)
      at Deferred.reject (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:146:15)
      at Function.then (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/_ext.js:50:21)
      at Deferred._settle (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:93:26)
      at Deferred.reject (~/my-project/.yarn/cache/deferred-npm-0.7.11-6bb57e55a8-5136170c57.zip/node_modules/deferred/deferred.js:146:15)
      at ~/my-project/.yarn/cache/fs2-npm-0.3.9-3d3c737c31-b772c89e30.zip/node_modules/fs2/stat.js:14:13
      at callback (~/my-project/.yarn/cache/graceful-fs-npm-4.2.4-734467635f-d095ee4dc6.zip/node_modules/graceful-fs/polyfills.js:295:20)
      at ~/my-project/.pnp.js:56166:13

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         2.13.0
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.2
```

</details>

**To Reproduce**

```bash
yarn add serverless
yarn serverless --help
```

**Screenshots**

![image (13)](https://user-images.githubusercontent.com/597828/100596331-54283280-32fc-11eb-9b36-c3f83271eaff.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version `12.16.1`
 - Yarn version `2.3.3-git.20201023.caf8b08b`

**Additional context**

Apparently, they are aware of it too: https://github.com/serverless/serverless/issues/5634#issuecomment-639553609

I'll test this and get back here to update.

**Comment by theseyi** [comment]
Was your `patch:` usage successful? @yoannmoinet

**Comment by yoannmoinet** [comment]
Sorry I didn't write back, the patch didn't work, it fixed the first issue, but another one appeared, fixed it, and another on appeared, and so on...

So I ended up just disabling pnp in my project.

**Comment by theseyi** [comment]
> Sorry I didn't write back, the patch didn't work, it fixed the first issue, but another one appeared, fixed it, and another on appeared, and so on...
> 
> So I ended up just disabling pnp in my project.

Yea, seems like pnp has a way to go to get wide support in the community. Would be nice if there was a straightforward way to provide help provide support in third party libraries
