### ISSUE TITLE
[Bug] Fails to build gulp-iconfont package

### ISSUE THREAD

**Issue by doctyper** [yarnpkg/berry#220]
**Describe the bug**

Yarn 2 fails to install the `gulp-iconfont` package.

**To Reproduce**

I've isolated the issue to the `gulp-iconfont` package as seen here:
https://github.com/doctyper/test-yarn-2-gulp-iconfont

**Log**

```sh
❯ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.12s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.16s
➤ YN0000: ┌ Link step
➤ YN0007: │ ttf2woff2@npm:3.0.0 must be built because it never did before or the last one failed
➤ YN0001: │ SyntaxError: Expected "&&", ")", ";", "|", "|&", "||", or [ \t] but ">" found (line 1, column 41).
    at peg$buildStructuredError (test-yarn-2-gulp-iconfont/.yarn/releases/yarn-berry.js:11497:12)
    at Object.peg$parse [as parse] (test-yarn-2-gulp-iconfont/.yarn/releases/yarn-berry.js:12705:11)
    at Object.parseShell (test-yarn-2-gulp-iconfont/.yarn/releases/yarn-berry.js:11147:24)
    at Object.execute (test-yarn-2-gulp-iconfont/.yarn/releases/yarn-berry.js:11083:27)
    at Object.executePackageScript (test-yarn-2-gulp-iconfont/.yarn/releases/yarn-berry.js:10568:30)
➤ YN0000: └ Completed in 0.83s
➤ YN0000: Failed with errors in 1.15s
```

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: v10.15.3
 - Yarn version: v2.0.0

**Comment by vlasenko** [comment]
The error is because `>` is not supported by berry shell atm. This is being worked on here:
https://github.com/yarnpkg/berry/pull/218

**Comment by arcanis** [comment]
#215 also makes the error clearer by showing which package and build command fail to execute (rather than the uncaught syntax error).

**Comment by arcanis** [comment]
Should be fixed now that shell redirections are supported (#237 + #245); feel free to open a new bug if that's not the case 😃
