### ISSUE TITLE
[Bug] Failing to use "yarn install" behind a proxy

### ISSUE THREAD

**Issue by Arthy000** [yarnpkg/berry#2257]
- [ ] I'd be willing to implement a fix

**Describe the bug**

- yarn 2.4.0 (project-wide), yarn 1.22.1 (global install)
- debian machine

On install (yarn install) yarn2 tries to download yarn classic (nightly) even though a stable yarn classic is already installed (yarn -v => 1.22.1).
That attempt is made ignoring httpProxy setting. 

Our CI environment can only connect to the outside through a proxy.
Thus yarn install fails.

` cat  /tmp/xfs-d71dd059/pack.log`
```
Installing the project using Yarn Classic

➤ YN0000: Downloading https://nightly.yarnpkg.com/latest.js
➤ YN0001: RequestError: connect ETIMEDOUT 104.16.171.99:443
    at ClientRequest.<anonymous> (/home/gaming1/buildAgent/work/34b05846fe2fe691/.yarn/releases/yarn-berry.cjs:23:31294)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.e.emit (/home/gaming1/buildAgent/work/34b05846fe2fe691/.yarn/releases/yarn-berry.cjs:2:583004)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
➤ YN0000: Failed with errors in 2m 14s
```

I tried downloading the file `https://nightly.yarnpkg.com/latest.js` using wget (which has a proper proxy configuration and works) but running latest.js from command line only seems to start yarn install again:
```
 ./latest.js
➤ YN0000: ┌ Resolution step
...
```

1. I don't get why it's trying to install yarn classic when it's already installed
2. I don't get why the installed yarn classic should be a nightly build instead of a stable release
3. I don't get why the download attempt does not use the proxy configuration from .yarnrc

Please note that 
- I am not responsible for the recent change, in our repo, from yarn classic to yarn berry
- I have no power over the security put in place, so I have to use a proxy to download something from the outside, no other option

I have no idea how to progress further, I've been stuck for 2 days (+ a weekend) without CI, so any help would be appreciated.

**Comment by merceyz** [comment]
> I don't get why it's trying to install yarn classic when it's already installed
> I don't get why the installed yarn classic should be a nightly build instead of a stable release

One of your dependencies is a git repo using Yarn 1, but since the version in use isn't specified by the repo we fetch the latest nightly. (could probably be stable)

> I don't get why the download attempt does not use the proxy configuration from .yarnrc

It's in the external project which doesn't have that config, we should probably fix that but as a temp workaround you can add the proxy to your global config in `~/.yarnrc.yml`

**Comment by Arthy000** [comment]
Hello,

Thank you for answering so quickly.

Sadly even with the line
```yaml
httpProxy: "http://1.2.3.4:1234"
```
I still get the same `YN0001: RequestError: connect ETIMEDOUT 104.16.171.99:443`

**Comment by merceyz** [comment]
The request is for a https url so you need to use
```yml
httpsProxy: "http://1.2.3.4:1234"
```

**Comment by Arthy000** [comment]
Thank you so much, I can finally start my builds again.

**Comment by Arthy000** [comment]
So, whether you want to close this issue as invalid or to keep it open to keep track of the two small improvements, that's all the same to me :)

**Comment by merceyz** [comment]
I'll close for now

**Comment by pavera** [comment]
@merceyz We recently ran into a similar issue for Dependabot. Given RepoA which is a yarn berry project and RepoB which is a yarn classic package which RepoA depends on, where does the proxy config need to live in order for `yarn install` in RepoA to work? It seems from [this post](https://github.com/yarnpkg/berry/issues/2257#issuecomment-748914763) that the config must live in both RepoA and RepoB?

**Comment by kimmy214** [comment]
ying@YingdeiMac kui % yarn 
➤ YN0000: ┌ Resolution step
➤ YN0001: │ RequestError: connect ETIMEDOUT 104.16.18.35:443
    at ClientRequest.<anonymous> (/Users/ying/workspace/FEProjects/kui/.yarn/releases/yarn-3.2.2.cjs:195:14361)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.o.emit (/Users/ying/workspace/FEProjects/kui/.yarn/releases/yarn-3.2.2.cjs:190:90453)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
➤ YN0000: └ Completed in 5m 8s
➤ YN0000: Failed with errors in 5m 8s
