### ISSUE TITLE
[Bug] Cannot resolve packages in Yarn 2.4.0 PnP mode

### ISSUE THREAD

**Issue by graphan** [yarnpkg/berry#2290]
**Describe the bug**

Our project works properly with Yarn 2.4.0 using `nodeLinker: node-modules`, however, fails when we want to use PnP module resolution.

```
/Users/username/repos/companyname/.yarn/cache/resolve-patch-af4189aea7-9e62d2803a.zip/node_modules/resolve/lib/sync.js:91
    throw err;
    ^

Error: Cannot find module 'typescript' from '/Users/username/repos/companyname/packages/navigator-web/node_modules'
    at Function.resolveSync [as sync] (/Users/username/repos/companyname/.yarn/cache/resolve-patch-af4189aea7-9e62d2803a.zip/node_modules/resolve/lib/sync.js:89:15)
    at getModules (/Users/username/repos/companyname/.yarn/$$virtual/react-scripts-virtual-795bde0310/0/cache/react-scripts-npm-4.0.1-d59350ab1a-1d37d97d1b.zip/node_modules/react-scripts/config/modules.js:119:32)
    at Object.<anonymous> (/Users/username/repos/companyname/.yarn/$$virtual/react-scripts-virtual-795bde0310/0/cache/react-scripts-npm-4.0.1-d59350ab1a-1d37d97d1b.zip/node_modules/react-scripts/config/modules.js:142:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.external_module_.Module._load (/Users/username/repos/companyname/.pnp.js:33063:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/username/repos/companyname/.yarn/$$virtual/react-scripts-virtual-795bde0310/0/cache/react-scripts-npm-4.0.1-d59350ab1a-1d37d97d1b.zip/node_modules/react-scripts/config/webpack.config.js:31:17) {
  code: 'MODULE_NOT_FOUND'
}
```

Do you have any hints what could be wrong?

**To Reproduce**

Don't know how to reproduce. Unfortunately, cannot share the project.

**Screenshots**

Unplugged packages:

![Screenshot 2020-12-30 at 11 57 07](https://user-images.githubusercontent.com/22321063/103347092-42ba7d80-4a96-11eb-94ef-8d2c526addb6.png)

There are two `resolve` versions:

![Screenshot 2020-12-30 at 11 59 42](https://user-images.githubusercontent.com/22321063/103347189-92994480-4a96-11eb-8985-2a6b9b36777b.png)

Maybe this is the issue?

In advance, thanks a lot for any hints.

**Environment if relevant (please complete the following information):**

 - OS: macOS Catalina Version 10.15.7
 - Node version: 12.16.2
 - Yarn version: 2.4.0

**Comment by merceyz** [comment]
I'd guess you don't have `typescript` as a dependency in the `navigator-web` workspace, but without a way to reproduce there isn't much we can do to help
