### ISSUE TITLE
[Bug] codeload.github.com/highslide-software/highstock-release/tar.gz/59fcc69b1ab74e21bdca01bf280cd54d0771030e: Request failed "404 Not Found"

### ISSUE THREAD

**Issue by javasgl** [yarnpkg/berry#2385]
[yarn-error.log](https://github.com/yarnpkg/berry/files/5829890/yarn-error.log)

```
Trace:
  Error: https://codeload.github.com/highslide-software/highstock-release/tar.gz/59fcc69b1ab74e21bdca01bf280cd54d0771030e: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:696:66)
      at new ResponseError (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:67045:16)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js:141604:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by merceyz** [comment]
Follow the issue template

**Comment by javasgl** [comment]
- [ ] I'd be willing to implement a fix

**Describe the bug**

execute the command `yarn install`

**To Reproduce**
see the whole package.json in the file: yarn-error.log

**Environment if relevant (please complete the following information):**

 - OS: darwin x64
 - Node version  6.12.0
 - Yarn version 1.22.0

**Additional context**

Add any other context about the problem here.
