### ISSUE TITLE
[Bug] Dedupe crashed when using JFrog Artifactory

### ISSUE THREAD

**Issue by Evalon** [yarnpkg/berry#2467]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When using JFrog Artifactory and using dedupe command yarn return error:
```
➤ YN0000: ┌ Deduplication step
➤ YN0001: │ Error: jest-resolve@npm:26.6.0::__archiveUrl=http%3A%2F%2Fartifactory.xxx.net%2Fartifactory%2Fapi%2Fnpm%2Fnpm-remote%2Fjest-resolve%2F-%2Fjest-resolve-26.6.0.tgz isn't supported by any available resolver
    at n.getResolverByDescriptor (/Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:336683)
    at n.getSatisfying (/Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:336346)
    at /Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:50137
    at Function.from (<anonymous>)
    at highest (/Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:49408)
    at /Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:51189
    at f.startTimerPromise (/Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:389746)
    at /Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:51118
    at /Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:51983
    at Function.start (/Users/user/projects/work/frontend/.yarn/releases/yarn-berry.cjs:2:388443)
```

**To Reproduce**

For reproduction you need to install dependencies from JFrog Artifactory and run dedupe command.

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node: 15.0.1
 - Yarn: 2.4.0

**Additional context**

**Comment by merceyz** [comment]
While the output is different this is probably similar to https://github.com/yarnpkg/berry/issues/2377

**Comment by jgornick** [comment]
@merceyz I don't think #2516 fixed this issue. I'm still experiencing the same issue with 3.0.2.

**Comment by merceyz** [comment]
Yeah it didn't, https://github.com/yarnpkg/berry/issues/2939 tracks the issue now
