### ISSUE TITLE
[Bug] UnhandledPromiseRejectionWarning on yarn install

### ISSUE THREAD

**Issue by hhsl** [yarnpkg/berry#2599]
- [x] I'd be willing to implement a fix

**Describe the bug**

Hej I'd like to migrate a project to yarn 2 using `nodeLinker: node-modules`, following the steps from the migration guide (https://yarnpkg.com/getting-started/migration). However during the resolution step I'm getting the following error message:

```
$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0061: │ debug@npm:4.1.1 is deprecated: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
➤ YN0000: │ UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/projects/tickets/.yarn/releases/yarn-berry.cjs:23:10082)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: │ UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
➤ YN0000: │ DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
➤ YN0061: │ @hapi/joi@npm:16.1.8 is deprecated: Switch to 'npm install joi'
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ @hapi/formula@npm:1.2.0 is deprecated: Moved to 'npm install @sideway/formula'
➤ YN0061: │ @hapi/topo@npm:3.1.6 is deprecated: This version has been deprecated and is no longer supported or maintained
➤ YN0061: │ @hapi/pinpoint@npm:1.0.2 is deprecated: Moved to 'npm install @sideway/pinpoint'
➤ YN0061: │ @hapi/address@npm:2.1.4 is deprecated: Moved to 'npm install @sideway/address'
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0032: │ fsevents@npm:2.3.1: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.3.1: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @hapi/hoek@npm:8.5.1 is deprecated: This version has been deprecated and is no longer supported or maintained
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ mkdirp@npm:0.3.0 is deprecated: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
➤ YN0061: │ request-promise-native@npm:1.0.9 is deprecated: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0032: │ nan@npm:2.14.2: Implicit dependencies on node-gyp are discouraged
➤ YN0001: │ HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/projects/tickets/.yarn/releases/yarn-berry.cjs:23:10082)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: └ Completed in 13s 907ms
➤ YN0000: Failed with errors in 13s 916ms
(node:20154) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**To Reproduce**

Unfortunately I don't know what is causing this unintended behavior, due to the unhandled Error. 
Otherwise my internet works fine, no VPN, Private Registries or other is used.
Installation with yarn 1 works fine.

**Environment if relevant (please complete the following information):**

 - OS: Linux
 - Node version v14.15.0
 - Yarn version 2.4.1

**Comment by arcanis** [comment]
As the error indicates, it's a 404, meaning that a package doesn't exist on the remote registry. We don't currently print which url, unfortunately, which will be fixed by #2406.
