### ISSUE TITLE
[Bug] Error while running yarn set version from source

### ISSUE THREAD

**Issue by LvChengbin** [yarnpkg/berry#2720]
```sh
root@localhost:~/projects/x# yarn set version from sources
➤ YN0000: Cloning the remote repository

  $ git init /tmp/yarnpkg-sources/d0a670
  $ git remote add origin https://github.com/yarnpkg/berry.git
  $ git fetch origin master
  $ git reset --hard FETCH_HEAD

➤ YN0000: Building a fresh bundle

➤ YN0000: ┌ Building the CLI
➤ YN0001: │ Error: The service was stopped
    at /tmp/yarnpkg-sources/d0a670/.yarn/cache/esbuild-wasm-npm-0.8.36-921531b77c-46293c9630.zip/node_modules/esbuild-wasm/lib/main.js:806:31
    at Socket.afterClose (/tmp/yarnpkg-sources/d0a670/.yarn/cache/esbuild-wasm-npm-0.8.36-921531b77c-46293c9630.zip/node_modules/esbuild-wasm/lib/main.js:493:7)
    at Socket.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
➤ YN0000: └ Completed in 4s 472ms

➤ YN0001: ✘ Failed to build the CLI
➤ YN0001: Error: Child "yarn" exited with exit code 1
    at ChildProcess.<anonymous> (/root/projects/x/.yarn/releases/yarn-berry.cjs:2:404999)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
➤ YN0000: Failed with errors in 1m 44s
```

**Comment by merceyz** [comment]
Follow the issue template
