### ISSUE TITLE
[Bug] Unable to Load Prettier in 3.0.0-rc.2

### ISSUE THREAD

**Issue by zulaica** [yarnpkg/berry#2800]
- [x] I'd be willing to implement a fix

**Describe the bug**

After upgrading to Yarn 3.0.0-rc.3, Prettier fails to load resulting in an error when formatting a document.

**To Reproduce**

```json
// package.json
{
...
  "dependencies": {
    "@yarnpkg/pnpify": "^3.0.0-rc.3"
  },
  "devDependencies": {
    "@babel/core": "^7.13.16",
    "@babel/plugin-proposal-object-rest-spread": "^7.13.8",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.13.15",
    "@babel/preset-env": "^7.13.15",
    "@wordpress/eslint-plugin": "^9.0.2",
    "babel-loader": "^8.2.2",
    "eslint": "^7.24.0",
    "eslint-config-prettier": "^8.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jest": "^24.3.5",
    "eslint-plugin-jsdoc": "^32.3.0",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "laravel-mix": "^6.0.18",
    "postcss": "^8.1",
    "prettier": "^2.2.1",
    "webpack": "^5.35.1",
    "webpack-cli": "^4.6.0"
  },
  "scripts": {
    "lint": "yarn lint:eslint",
    "lint:eslint": "yarn eslint . --color --cache",
    "lint:fix": "yarn lint:eslint --fix",
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "production": "mix --production"
  },
  "dependenciesMeta": {
    "laravel-mix@6.0.18": {
      "unplugged": true
    }
  }
  ...
}
```

```sh
# Upgrade to Yarn 3.0.0-rc.2
yarn set version 3.0.0-rc.2

# Reinstall packages
yarn install

# Run pnpify
yarn pnpify --sdk vscode
```

**Environment if relevant (please complete the following information):**

 - OS: macOS 11.2.3
 - Node version: 14.16.0
 - Yarn version: 3.0.0-rc.2

**Additional context**

When attempting to format a document with Prettier using VS Code an error occurs. At a glance, it seems that PNP is attempting to load a `.pnp.js` file, but that no longer exists and has been replaced by a `.pnp.cjs` file.

```
["INFO" - 3:35:51 AM] Formatting /Absolute/Path/To/Project/webpack.mix.js
["INFO" - 3:35:51 AM] Using config file at '/Absolute/Path/To/Project/.prettierrc'
["INFO" - 3:35:51 AM] Using ignore file (if present) at /Absolute/Path/To/Project/.prettierignore
["INFO" - 3:35:51 AM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 3:35:51 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:35:51 AM] Prettier Options:
{
  "filepath": "/Absolute/Path/To/Project/webpack.mix.js",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "arrowParens": "always",
  "singleQuote": true,
  "trailingComma": "none"
}
["ERROR" - 3:35:51 AM] Error formatting document.
["ERROR" - 3:35:51 AM] ENOENT: no such file or directory, stat '/Absolute/Path/To/Project/.pnp.js'
Error: ENOENT: no such file or directory, stat '/Absolute/Path/To/Project/.pnp.js'
	at statSync (fs.js:1020:3)
	at Object.e.statSync (electron/js2c/asar_bundle.js:5:4264)
	at NodeFS.statSync (/Absolute/Path/To/Project/.pnp.js:5110:24)
	at makeCallSync.subPath.subPath (/Absolute/Path/To/Project/.pnp.js:7684:26)
	at ZipOpenFS.makeCallSync (/Absolute/Path/To/Project/.pnp.js:8220:26)
	at ZipOpenFS.statSync (/Absolute/Path/To/Project/.pnp.js:7683:17)
	at VirtualFS.statSync (/Absolute/Path/To/Project/.pnp.js:5479:24)
	at refreshApiEntry (/Absolute/Path/To/Project/.pnp.js:10082:31)
	at Object.getApiEntry (/Absolute/Path/To/Project/.pnp.js:10096:9)
	at Function.external_module_.Module._load (/Absolute/Path/To/Project/.pnp.js:8994:61)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:694)
	at Object.get babel [as babel] (/Absolute/Path/To/Project/.yarn/cache/prettier-npm-2.2.1-e0670992f8-92c6c9f4b8.zip/node_modules/prettier/index.js:47687:12)
	at resolveParser (/Absolute/Path/To/Project/.yarn/cache/prettier-npm-2.2.1-e0670992f8-92c6c9f4b8.zip/node_modules/prettier/index.js:13587:21)
	at normalize$1 (/Absolute/Path/To/Project/.yarn/cache/prettier-npm-2.2.1-e0670992f8-92c6c9f4b8.zip/node_modules/prettier/index.js:13695:18)
	at format (/Absolute/Path/To/Project/.yarn/cache/prettier-npm-2.2.1-e0670992f8-92c6c9f4b8.zip/node_modules/prettier/index.js:15111:46)
	at /Absolute/Path/To/Project/.yarn/cache/prettier-npm-2.2.1-e0670992f8-92c6c9f4b8.zip/node_modules/prettier/index.js:57542:12
	at Object.format (/Absolute/Path/To/Project/.yarn/cache/prettier-npm-2.2.1-e0670992f8-92c6c9f4b8.zip/node_modules/prettier/index.js:57562:12)
	at t.default.<anonymous> (/Absolute/Path/To/User/Home/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:16897)
	at Generator.next (<anonymous>)
	at s (/Absolute/Path/To/User/Home/.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:9119)
["INFO" - 3:35:51 AM] Formatting completed in 9.529208ms.
```

**Comment by zulaica** [comment]
Upon rebooting after upgrading macOS to 11.3, I am unable to replicate the issue. It's unclear what exactly resolved the issue for me—it could simply have been the reboot alone—but since it is no longer persisting I'll close this bug.
