### ISSUE TITLE
[Bug] Failure to build @material-ui/lab using snowpack

### ISSUE THREAD

**Issue by alubbe** [yarnpkg/berry#2879]
- [ ] I'd be willing to implement a fix

**Describe the bug**

I cannot build @material-ui/lab using snowpack and yarn berry:
```
$ yarn build
[18:01:30] [snowpack] ! building files...
[18:01:31] [snowpack] ✔ files built. [0.14s]
[18:01:31] [snowpack] ! building dependencies...
[18:01:33] [@snowpack/plugin-typescript] Command completed.
[18:01:34] [esinstall] /Users/alubbe/code/new-snowpack-yarn/.yarn/$$virtual/@material-ui-lab-virtual-88b9fd75b5/0/cache/@material-ui-lab-npm-4.0.0-alpha.58-05f1e9da95-4d5f07198f.zip/node_modules/@material-ui/lab/esm/AlertTitle/AlertTitle.js
   Module "/Users/alubbe/code/new-snowpack-yarn/.yarn/$virtual/@material-ui-core-virtual-8af7e36dae/0/cache/@material-ui-core-npm-4.11.4-d024c4b650-98c5e25c33.zip/node_modules/@material-ui/core/esm/index.js" could not be resolved by Snowpack (Is it installed?).
[18:01:34] [snowpack] Install failed.
[18:01:34] [snowpack] Error: Install failed.
    at Object.install (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-f0069b4e31.zip/node_modules/snowpack/lib/index.js:94506:23)
    at async Object.installPackages (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-f0069b4e31.zip/node_modules/snowpack/lib/index.js:122454:25)
    at async installOptimizedDependencies (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-f0069b4e31.zip/node_modules/snowpack/lib/index.js:182476:27)
    at async Object.buildDependencies (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-f0069b4e31.zip/node_modules/snowpack/lib/index.js:182630:31)
    at async build (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-f0069b4e31.zip/node_modules/snowpack/lib/index.js:182714:5)
    at async Object.command (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-f0069b4e31.zip/node_modules/snowpack/lib/index.js:182737:9)
    at async cli (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-f0069b4e31.zip/node_modules/snowpack/lib/index.js:183047:9)
```

But it works just fine with npm:
```
$ npm run build

> @ build /code/new-snowpack-yarn
> snowpack build

[17:29:49] [snowpack] ! building files...
[17:29:49] [snowpack] ✔ files built. [0.11s]
[17:29:49] [snowpack] ! building dependencies...
[17:29:52] [@snowpack/plugin-typescript] Command completed.
[17:29:54] [snowpack] ✔ dependencies built. [4.47s]
[17:29:54] [snowpack] ! writing to disk...
[17:29:54] [snowpack] ✔ write complete. [0.02s]
[17:29:54] [snowpack] ▶ Build Complete!
```

**To Reproduce**

Clone https://github.com/alubbe/new-snowpack-yarn

Run `yarn install && yarn build` to see it break.

Run `npm install && npm run build` to see it work.

**Environment if relevant (please complete the following information):**

 - OS: Mac OS
 - Node version v14.16.1
 - Yarn version 2.4.1

**Comment by alubbe** [comment]
Thanks, that does indeed fix it! I've got one immediate follow-up, but I'll create a new ticket
