### ISSUE TITLE
[Bug] 3.0.0-rc.2 `yarn node -r` cannot access local files

### ISSUE THREAD

**Issue by alubbe** [yarnpkg/berry#2885]
- [ ] I'd be willing to implement a fix

This works just fine:
```
$ node -r ./.pnp.cjs -p '`hello`'
hello
```

This does not:
```
$ yarn node -r ./.pnp.cjs -p '`hello`'

/Users/alubbe/code/.pnp.cjs:58769
    throw firstError;
    ^

Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: /Users/alubbe/code/node_modules/.pnp.cjs
Not found: /Users/alubbe/code/node_modules/.pnp.cjs
Not found: /Users/alubbe/code/node_modules/.pnp.cjs.js
Not found: /Users/alubbe/code/node_modules/.pnp.cjs.json
Not found: /Users/alubbe/code/node_modules/.pnp.cjs.node

Require stack:
- internal/preload
    at Function.external_module_.Module._resolveFilename (/Users/alubbe/code/.pnp.cjs:58768:55)
    at Function.external_module_.Module._load (/Users/alubbe/code/.pnp.cjs:58588:48)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:449:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:76:3)
    at internal/main/eval_string.js:14:1
```

And probably related, if I put this into package.json:
```
  "scripts": {
    "hello": "node -r ./.pnp.cjs -p '`hello`'"
  },
```
then running `yarn hello` gives the same error:
```
$ yarn lol

/Users/alubbe/code/.pnp.cjs:58769
    throw firstError;
    ^

Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: /Users/alubbe/code/node_modules/.pnp.cjs
Not found: /Users/alubbe/code/node_modules/.pnp.cjs
Not found: /Users/alubbe/code/node_modules/.pnp.cjs.js
Not found: /Users/alubbe/code/node_modules/.pnp.cjs.json
Not found: /Users/alubbe/code/node_modules/.pnp.cjs.node

Require stack:
- internal/preload
    at Function.external_module_.Module._resolveFilename (/Users/alubbe/code/.pnp.cjs:58768:55)
    at Function.external_module_.Module._load (/Users/alubbe/code/.pnp.cjs:58588:48)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:449:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:76:3)
```

**Comment by alubbe** [comment]
Perfect, it works great now. Thank you for the quick fix!
