### ISSUE TITLE
[Bug] 3.0.0-rc.2 cannot run `snowpack dev` (wrt `array.prototype.flat`)

### ISSUE THREAD

**Issue by alubbe** [yarnpkg/berry#2902]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Running `snowpack dev` when using yarn pnp gives this error:
```
$ snowpack dev --verbose
...
[15:56:45] [esinstall:has] installing npm packages: has
[15:56:45] [esinstall:has] writing install results to disk
[15:56:45] [snowpack] Successfully ran esinstall.
[15:56:45] [snowpack]     └── has@1.0.3 DONE
[15:56:45] [snowpack]       └── function-bind@1.1.1 (dedupe)
[15:56:45] [snowpack] Package "function-bind" not found. Have you installed it?
[15:56:45] [snowpack] Error: Package "function-bind" not found. Have you installed it?
    at Object.resolveEntrypoint (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:93949:15)
    at PackageSourceLocal.buildPackageImport (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:122916:34)
    at async /Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:123071:21
    at async PackageSourceLocal.buildPackageImport (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:122943:30)
    at async PackageSourceLocal.prepare (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:122723:13)
    at async startServer (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:181745:9)
    at async Object.command (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:182387:9)
    at async cli (/Users/alubbe/code/new-snowpack-yarn/.yarn/cache/snowpack-npm-3.3.7-ef3e36d1b8-e04d9531b7.zip/node_modules/snowpack/lib/index.js:183051:9)
```
whereas when using `npm install`, it works great.

**To Reproduce**

Clone https://github.com/alubbe/new-snowpack-yarn, run `yarn install && yarn start --verbose` to get the above error. Then run `npm install && npm start` to see it work.

Sorry that I can't be more helpful here, I have no idea where to start debugging this error. Do let me know if there's any further info I can add!

**Comment by merceyz** [comment]
Running `PNP_DEBUG_LEVEL=1 yarn start --verbose` shows the error actual error:
```
✖ array.prototype.flat tried to access function-bind, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

  In ← 'function-bind/package.json'
  In ← '/.yarn/cache/array.prototype.flat-npm-1.2.4-7b3397fc11-8.zip/node_modules/array.prototype.flat/index.js/'
  In ← { considerBuiltins: false }
```

Which is interesting as `array.prototype.flat` doesn't use `function-bind` so this seems to be an error in snowpack

**Comment by alubbe** [comment]
thank you, that solved it!
