### ISSUE TITLE
[Bug] YN0001: │ TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by lolmaus** [yarnpkg/berry#2946]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Running `yarn` in a project fails with:

```
➤ YN0001: │ TypeError: Cannot read property 'name' of undefined
    at o (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:553)
    at o (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:688)
    at o (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:688)
    at o (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:688)
    at o (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:688)
    at KFe (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:703)
    at px (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:2166)
    at px (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:437:2557)
    at gX (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:434:6939)
    at $o (/home/lolmaus/Code/kaliber5/ember-bdd/.yarn/releases/yarn-3.0.0-rc.2.cjs:442:338)
```

There are no further details, it just crashes in the middle of normal oepration.

**To Reproduce**

I just run `yarn` in my [project](https://github.com/kaliber5/ember-bdd/commit/31eb82abb6f70125ca0942626b5f7e70e471ea74).

**Screenshots**

<a href="https://user-images.githubusercontent.com/200884/119969988-e792a580-bfb7-11eb-84cb-0e03fc94fea7.png"><img src="https://user-images.githubusercontent.com/200884/119969988-e792a580-bfb7-11eb-84cb-0e03fc94fea7.png" width="555" alt="screenshot"></a>

**Environment**

 - OS: Unbuntu 20.04
 - Node: 14.15.4
 - Yarn: 3.0.0-rc.2 (rc.1 also has the same problem)

**Additional context**

Does not happen on CI for some reason, so I did not bother with a reproduction. Sorry about that, but I hope that the stacktrace is enough to locate the cause of the problem and fix it to at least spit out a meaningful error.

**Comment by lolmaus** [comment]
My project is a Yarn Workspaces monorepo, Yarn Berry is running in the `node_modules` mode.

**Comment by larixer** [comment]
Fixed already, but not published yet, you can use `yarn set version from sources`  to get the latest unpublished version.
