### ISSUE TITLE
[Bug] Unable to upgrade to 3.0.0-rc.2 from 2.4.1

### ISSUE THREAD

**Issue by jacogr** [yarnpkg/berry#2957]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Due to the TS 4.3.2 mismatch, I need to upgrade to 3.0.0-rc.2 (also using the node linker in all my projects). Sadly attempting to upgrade fails with an "Invalid semver version"

**To Reproduce**

```
$ yarn set version latest
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/master/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-2.4.1.cjs
➤ YN0000: Done in 3s 579ms
$ yarn set version 3.0.0-rc.2  
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/%40yarnpkg/cli/3.0.0-rc.2/packages/yarnpkg-cli/bin/yarn.js
➤ YN0001: Error: Invalid semver version
    at /xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:87536
    at async a.mktempPromise (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:514978)
    at async Qe (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:87261)
    at async /xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:87122
    at async Function.start (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:389517)
    at async we.execute (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:86945)
    at async we.validateAndExecute (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:660570)
    at async Y.run (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:17:3854)
    at async Y.runExit (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:17:4021)
    at async h (/xyz/dev/.yarn/releases/yarn-2.4.1.cjs:2:285303)
➤ YN0000: Failed with errors in 2s 908ms
```

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.15.2
 - Node version 14.15.1
 - Yarn version 2.4.1

**Comment by paul-soporan** [comment]
You need to disable your plugins (by commenting them out of the `.yarnrc.yml` - but note that Yarn doesn't currently preserve comments) before running `yarn set version latest`. This issue will be fixed starting from the next release.
