### ISSUE TITLE
[Bug]: @yarnpkg/doctor fails with the interactive-tools plugin

### ISSUE THREAD

**Issue by pearj** [yarnpkg/berry#3164]
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

When running `yarn dlx @yarnpkg/doctor` with the interactive-tools plugin installed it crashes with:

```
➤ YN0000: ┌ /home/pearj/dev/idm-ts-types/package.json
➤ YN0001: │ TypeError: clipanion__WEBPACK_IMPORTED_MODULE_2__.Command.Path is not a function (when initializing @yarnpkg/plugin-interactive-tools, defined in /home/pearj/dev/idm-ts-types/.yarnrc.yml)
    at Module.<anonymous> (/home/pearj/dev/idm-ts-types/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs:311:100)
    at __webpack_require__ (/home/pearj/dev/idm-ts-types/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs:64501:42)
    at Module.<anonymous> (/home/pearj/dev/idm-ts-types/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs:16:74)
    at __webpack_require__ (/home/pearj/dev/idm-ts-types/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs:64501:42)
    at /home/pearj/dev/idm-ts-types/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs:64564:18
    at factory (/home/pearj/dev/idm-ts-types/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs:64565:12)
    at plugin (/home/pearj/.yarn/berry/cache/@yarnpkg-core-npm-3.0.0-rc.12-e1c4aa16f6-7.zip/node_modules/@yarnpkg/core/lib/Configuration.js:768:45)
    at Object.prettifyAsyncErrors (/home/pearj/.yarn/berry/cache/@yarnpkg-core-npm-3.0.0-rc.12-e1c4aa16f6-7.zip/node_modules/@yarnpkg/core/lib/miscUtils.js:125:22)
    at importPlugin (/home/pearj/.yarn/berry/cache/@yarnpkg-core-npm-3.0.0-rc.12-e1c4aa16f6-7.zip/node_modules/@yarnpkg/core/lib/Configuration.js:767:48)
    at Function.find (/home/pearj/.yarn/berry/cache/@yarnpkg-core-npm-3.0.0-rc.12-e1c4aa16f6-7.zip/node_modules/@yarnpkg/core/lib/Configuration.js:792:27)
➤ YN0000: └ Completed in 0s 495ms
```

### To reproduce

I tried to use sherlock but I wasn't able to import plugins for some reason

```bash
yarn set version berry
yarn init
yarn add typescript
yarn plugin import interactive-tools
yarn dlx @yarnpkg/doctor
```

I also tried from source on the 2.4 branch:
```bash
yarn set version berry
yarn init
yarn set version from sources --no-minify --branch cherry-pick/2.4
yarn plugin import from sources interactive-tools --no-minify --branch cherry-pick/2.4
yarn add typescript
yarn dlx @yarnpkg/doctor
```

On master it works ok, so maybe something needs a backport?

```bash
yarn set version berry
yarn init
yarn set version from sources --no-minify
yarn plugin import from sources interactive-tools --no-minify
yarn add typescript
yarn dlx @yarnpkg/doctor
```

### Environment

System:
  OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
  CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
Binaries:
  Node: 12.22.1 - /tmp/xfs-8c1d0fb9/node
  Yarn: 2.4.2 - /tmp/xfs-8c1d0fb9/yarn
  npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm

**Comment by paul-soporan** [comment]
You need to use a v2 version of the doctor (latest on the registry is 3.x) inside Yarn v2 projects: `yarn dlx @yarnpkg/doctor@2.x`
