### ISSUE TITLE
[Bug]: @yarnpkg/sdks@2.4.1 is missing the `lib` folder

### ISSUE THREAD

**Issue by sampi** [yarnpkg/berry#3179]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

the latest version of `@yarnpkg/sdks` (v2.4.1) only contains a `package.json` and nothing else, so trying to use it will result in the following error:

```
<myWorkspace>/.pnp.cjs:53973
    throw firstError;
    ^

Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: <myWorkspace>/.yarn/cache/@yarnpkg-sdks-npm-2.4.1-c2c5c3dd4e-673fe95416.zip/node_modules/@yarnpkg/sdks/lib/cli.js
Not found: <myWorkspace>/.yarn/cache/@yarnpkg-sdks-npm-2.4.1-c2c5c3dd4e-673fe95416.zip/node_modules/@yarnpkg/sdks/lib/cli.js
Not found: <myWorkspace>/.yarn/cache/@yarnpkg-sdks-npm-2.4.1-c2c5c3dd4e-673fe95416.zip/node_modules/@yarnpkg/sdks/lib/cli.js.js
Not found: <myWorkspace>/.yarn/cache/@yarnpkg-sdks-npm-2.4.1-c2c5c3dd4e-673fe95416.zip/node_modules/@yarnpkg/sdks/lib/cli.js.json
Not found: <myWorkspace>/.yarn/cache/@yarnpkg-sdks-npm-2.4.1-c2c5c3dd4e-673fe95416.zip/node_modules/@yarnpkg/sdks/lib/cli.js.node

    at Function.external_module_.Module._resolveFilename (<myWorkspace>/.pnp.cjs:53972:55)
    at Function.external_module_.Module._load (<myWorkspace>/.pnp.cjs:53771:48)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

```

### To reproduce

```
yarn install -D @yarnpkg/sdks@2.4.1 && yarn sdks
```

### Environment

System:
  OS: macOS 11.5
  CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
Binaries:
  Node: 14.17.3 - /private/var/folders/y7/69q1j69d1fvf4sqzz43r4ql80000gn/T/xfs-da2c6d07/node
  Yarn: 3.0.0 - /private/var/folders/y7/69q1j69d1fvf4sqzz43r4ql80000gn/T/xfs-da2c6d07/yarn
  npm: 7.20.0 - ~/.nvm/versions/node/v14.17.3/bin/npm

### Additional context

switching back to `@yarnpkg/sdks@2.4.1-rc.4` fixes the issue

**Comment by brion-fuller** [comment]
I see the same issue in version 3.0.0.  Only thing included is the package.json.  When running `yarn dlx @yarnpkg/pnpify --sdk vscode` I now get a 
```
Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: /Users/Code/components/.yarn/cache/@yarnpkg-pnpify-npm-3.0.0-4a2df64655-072d007b58.zip/node_modules/@yarnpkg/pnpify/lib/cli.js`
```

**Comment by arcanis** [comment]
Indeed something looks weird - let me check at our release script 🤔

**Comment by arcanis** [comment]
As a short-term measure I've set them back to their RC versions; still trying to figure out how that happened.
