### ISSUE TITLE
[Bug] Type errors when building forked project

### ISSUE THREAD

**Issue by Js-Brecht** [yarnpkg/berry#330]
**Describe the bug**

So, this is a little strange.  I forked this project, so I could work on a PR, but if I try to run `build:cli+hook`, I wind up with a lot of node type errors.  **Theoretically**, the repositories should be identical after forking, and I'm able to build this repo without a problem.  `build:cli` works without a problem; this just threw me off, because... why would it work for one repo and not the other, when they should be the same.

**To Reproduce**

Clone [https://github.com/Js-Brecht/berry](https://github.com/Js-Brecht/berry), and try to run `build:cli+hook`.

**Screenshots**

![image](https://user-images.githubusercontent.com/1935258/62401256-1b1c5a00-b51e-11e9-8e7f-c1a157ef5ba7.png)

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version: v10.13.0 and v12.5.0
 - Yarn version: v2.0.0

**Comment by arcanis** [comment]
The hook build is broken, it'll be fixed with #328 🙂

**Comment by arcanis** [comment]
I just merged it, can you pull and confirm it fixed the problem?

**Comment by Js-Brecht** [comment]
This is what I get now.  Looks like it's prepending "/" to the beginning of the path somewhere

```
D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\cli.js:74
                                throw err;
                                ^

Error: Couldn't find a suitable Node resolution for the specified unqualified path

Source path: /D:/dev/source/test/yarnpkg/berry/.yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd/1/packages/berry-pnpify/lib
Rejected resolution: /D:/dev/source/test/yarnpkg/berry/.yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd/1/packages/berry-pnpify/lib
Rejected resolution: /D:/dev/source/test/yarnpkg/berry/.yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd/1/packages/berry-pnpify/lib.js
Rejected resolution: /D:/dev/source/test/yarnpkg/berry/.yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd/1/packages/berry-pnpify/lib.json
Rejected resolution: /D:/dev/source/test/yarnpkg/berry/.yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd/1/packages/berry-pnpify/lib.node
Rejected resolution: /D:/dev/source/test/yarnpkg/berry/.yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd/1/packages/berry-pnpify/lib.mjs

    at Object.makeError (D:\dev\source\test\yarnpkg\berry\.pnp.js:26930:26)
    at resolveUnqualified (D:\dev\source\test\yarnpkg\berry\.pnp.js:29272:35)
    at resolveRequest (D:\dev\source\test\yarnpkg\berry\.pnp.js:29288:20)
    at Object.resolveRequest (D:\dev\source\test\yarnpkg\berry\.pnp.js:29323:32)
    at Function.module_1.default._resolveFilename (D:\dev\source\test\yarnpkg\berry\.pnp.js:28755:37)
    at Function.module_1.default._load (D:\dev\source\test\yarnpkg\berry\.pnp.js:28676:45)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (D:\dev\source\test\yarnpkg\berry\.yarn\cache\v8-compile-cache-npm-2.0.2-17947293ffecdaee7d9e4d938ebcb88b57ddf1a30ac12649ae97e13402e339d0.zip\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\dev\source\test\yarnpkg\berry\packages\berry-pnp\webpack.config.hook.js:1:63)
    at Module._compile (D:\dev\source\test\yarnpkg\berry\.yarn\cache\v8-compile-cache-npm-2.0.2-17947293ffecdaee7d9e4d938ebcb88b57ddf1a30ac12649ae97e13402e339d0.zip\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.module_1.default._load (D:\dev\source\test\yarnpkg\berry\.pnp.js:28694:20)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (D:\dev\source\test\yarnpkg\berry\.yarn\cache\v8-compile-cache-npm-2.0.2-17947293ffecdaee7d9e4d938ebcb88b57ddf1a30ac12649ae97e13402e339d0.zip\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\utils\convert-argv.js:115:13)
    at requireConfig (D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\utils\convert-argv.js:117:6)
    at D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\utils\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\utils\convert-argv.js:122:15)
    at D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (D:\dev\source\test\yarnpkg\berry\.yarn\cache\yargs-npm-12.0.5-18c426aea9a03bc58a6704778e77147379425224d79bf4e3635adf4a736a13f8.zip\node_modules\yargs\yargs.js:567:18)
    at D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (D:\dev\source\test\yarnpkg\berry\.yarn\virtual\webpack-cli-virtual-f612afee02728f9d5a2192cb3840bf0e8428d29e80aedbd560b408ca08e9b1dc\0\cache\webpack-cli-npm-3.3.2-578b4734ac72bebf6b5cbaaea4f6374e564192f85c75aa40c65d313bf2742bc0.zip\node_modules\webpack-cli\bin\cli.js:375:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.module_1.default._load (D:\dev\source\test\yarnpkg\berry\.pnp.js:28694:20)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  pnpCode: 'QUALIFIED_PATH_RESOLUTION_FAILED',
  data: {
    unqualifiedPath: '/D:/dev/source/test/yarnpkg/berry/.yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd/1/packages/berry-pnpify/lib',
    request: '@berry/pnpify/lib',
    issuer: '/D:/dev/source/test/yarnpkg/berry/packages/berry-pnp/webpack.config.hook.js'
  }
}
command not found: run
```

**Comment by arcanis** [comment]
I published b7bb83d6a7f1c6febc3d0d67d2a607b376dee15a which should fix it!

For the record the problem wasn't coming from the path - this is actually expected (in order to support all platforms under a common codebase we use an in-house "Portable Path" data type instead of the regular filesystem utilities; those portable paths all use the posix style, even on Windows).

**Comment by Js-Brecht** [comment]
Ah, I see.  That's pretty cool.  I really like what you guys are doing with Yarn, with the Plug'n'Play, and the API hooks.  Very good idea.

And yes, that did fix it.  Later on today I'll spin up my Windows box and test.

I still think it's a little bizarre that I was able to do a hook build from this repo, but with a fresh fork, it failed.  I mean... should have been the same code.  I did the fork and noticed almost immediately that it failed.  Then I cloned them both side by side, and tested both.  `yarnkpkg/berry` worked, mine didn't :man_shrugging: ... weird.

**Comment by arcanis** [comment]
My best guess is that the old repository needed to `pull` to get the fix. Another option is that maybe you had a corrupted local build that was taking precedence over the checked-in bundle 🤔

Since the issue appears fixed I'll close this one, feel free to open a new one if it happens again!
