### ISSUE TITLE
[Bug?]: yarn2 In monorepo, the root module cannot directly import the yarn plugin of the submodule

### ISSUE THREAD

**Issue by rxliuli** [yarnpkg/berry#3331]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In short, I failed when using the plugin of the `yarn plugin import` submodule, not sure if this is the expected behavior

### To reproduce

> [Reproduce Warehouse](https://github.com/rxliuli/liuli-tools)

Steps to reproduce

1. `yarn && yarn setup` installation dependencies and initialization
2. `cd libs/yarn-plugin-changed && yarn build` package plugin
3. `cd ../.. && yarn plugin import libs/yarn-plugin-changed/bundles/\@yarnpkg/plugin-changed.js` Back to the root directory to install the plugin
4. Get the error

```js
$ yarn plugin import libs/yarn-plugin-changed/bundles/\@yarnpkg/plugin-changed.js
➤ YN0001: Error: Invalid locator (@yarnpkg/plugin-libs/yarn-plugin-changed/bundles/@yarnpkg/plugin-changed.js)
    at Object.hA (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:242:12395)
    at C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:387:1702
    at async Function.start (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:275:2287)
    at async Rp.execute (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:387:1110)
    at async Rp.validateAndExecute (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:197:620)
    at async ts.run (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:211:1846)
    at async ts.runExit (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:211:2013)
    at async i (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:310:12327)
    at async r (C:\Users\rxliuli\Code\Pkg\liuli-tools\.yarn\releases\yarn-berry.cjs:310:10567)
➤ YN0000: Failed with errors in 0s 133ms
```

### Environment

  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.0 - ~\AppData\Local\Temp\xfs-68112280\node.CMD
    Yarn: 3.0.0 - ~\AppData\Local\Temp\xfs-68112280\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD

**Comment by merceyz** [comment]
You need to use a relative path
```sh
yarn plugin import "./libs/yarn-plugin-changed/bundles/@yarnpkg/plugin-changed.js"
```

**Comment by rxliuli** [comment]
> You need to use a relative path
> 
> ```shell
> yarn plugin import "./libs/yarn-plugin-changed/bundles/@yarnpkg/plugin-changed.js"
> ```

thx, it has been fixed, and the plugin packaged by `builder build plugin` defaults to _bundles/@yarnpkg/plugin-changed.js_ instead of _bundles/@liuli-util/plugin-changed.js_. Is this also the expected behavior?
