### ISSUE TITLE
[Bug?]: workspaces foreach using too much memory

### ISSUE THREAD

**Issue by LaurensUP** [yarnpkg/berry#3395]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

We used to have a custom script building a dependency tree for our monorepo and building packages in the right order.
Since the workspaces plugin does the same thing, we've replaced this script.
However, when running the command on CI, it goes out of memory. 

As the workspaces foreach command is essentially doing the same thing as our former JS script, this is unexpected behavior.

Script:
`yarn workspaces foreach --topological-dev --parallel --verbose --jobs 4 run build`

It also goes out of memory with 2 jobs, while we used to be able to run this with 4 workers.

Output on CI:

```
15:33:33  ➤ YN0000: [id-component-repo]: Internal Error: spawn ENOMEM
15:33:33  ➤ YN0000: [id-component-repo]:     at ChildProcess.spawn (internal/child_process.js:403:11)
15:33:33  ➤ YN0000: [id-component-repo]:     at spawn (child_process.js:667:9)
15:33:33  ➤ YN0000: [id-component-repo]:     at Object.spawnWithSignal [as spawn] (child_process.js:871:17)
15:33:33  ➤ YN0000: [id-component-repo]:     at FN (/opt/jenkins/workspace/Compose_design-studio_PR-1808/.yarn/releases/yarn-3.0.0.cjs:4:7428)
15:33:33  ➤ YN0000: [id-component-repo]:     at Wf.implementation (/opt/jenkins/workspace/Compose_design-studio_PR-1808/.yarn/releases/yarn-3.0.0.cjs:255:1599)
15:33:33  ➤ YN0000: [id-component-repo]:     at Wf.exec (/opt/jenkins/workspace/Compose_design-studio_PR-1808/.yarn/releases/yarn-3.0.0.cjs:258:1582)
15:33:33  ➤ YN0000: [id-component-repo]:     at Wf.run (/opt/jenkins/workspace/Compose_design-studio_PR-1808/.yarn/releases/yarn-3.0.0.cjs:258:1753)
15:33:33  ➤ YN0000: [id-component-repo]:     at SJ (/opt/jenkins/workspace/Compose_design-studio_PR-1808/.yarn/releases/yarn-3.0.0.cjs:267:6185)
15:33:33  ➤ YN0000: [id-component-repo]:     at runMicrotasks (<anonymous>)
15:33:33  ➤ YN0000: [id-component-repo]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
15:33:33  ➤ YN0000: [id-component-repo]: Process exited (exit code 1), completed in 28s 273ms
15:33:38  ➤ YN0000: [id-data-model-service]: [info] [webpackbar] Compiling Webpack
15:33:38  ➤ YN0000: [id-data-model-service]: [success] [webpackbar] Webpack: Compiled successfully in 28.69s
15:33:38  ➤ YN0000: [id-data-model-service]: Process exited (exit code 0), completed in 32s 180ms
15:33:38  ➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
15:33:38  ➤ YN0000: Failed with errors in 4m 7s
```

### To reproduce

Need quite a big monorepo to reproduce this..
If there are ideas for me to set this up, I will try to make a solid reproduce case.

### Environment

```
  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.17.6 - /tmp/xfs-88fc14e7/node
    Yarn: 3.0.0 - /tmp/xfs-88fc14e7/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    jest: 27.0.1 => 27.0.1 
```

**Comment by LaurensUP** [comment]
It seems to me that there is some kind of memory leak when using `yarn workspaces foreach` on a big monorepo (~80+ packages).

We have a test suite per package, and when running those suites sequentially with `workspaces foreach`, even those are going out of memory on CI atm.

**Comment by LaurensUP** [comment]
Working on a reproduce case.

**Comment by LaurensUP** [comment]
Could this have to do with how [Clipanion](https://github.com/arcanis/clipanion) spawns new processes? 
In our former script (that did virtually the same thing as `yarn workspaces foreach`) we used node's `child_process.exec` to spawn the commands. This was giving is no memory issues on the same CI machine.

**Comment by arcanis** [comment]
The scripts are executed within the same process ([here](https://github.com/yarnpkg/berry/blob/master/packages/plugin-workspace-tools/sources/commands/foreach.ts#L200-L204)) - it's possible there's a weird interaction somewhere, but my assumption was that in-process execution would be lighter than spawning subprocesses 🤔

**Comment by merceyz** [comment]
> It seems to me that there is some kind of memory leak when using yarn workspaces foreach on a big monorepo (~80+ packages).

I tested on a project with 277 workspaces with a total of 6449 packages and it sits at about 400MB memory and doesn't climb so the project size doesn't seem to be the problem

**Comment by LaurensUP** [comment]
Our situation is: CI Host > Spawning Docker container > Running yarn commands

We've found a resolution for this by running the following command in the Host
`sudo echo 1 > /proc/sys/vm/overcommit_memory`

Inspiration came from https://github.com/nodejs/node/issues/25382#issuecomment-452441332

**Comment by seansfkelley** [comment]
I've been tooling around with replacing Lerna with workspaces foreach recently, and while my memory issues aren't as severe as yours, I have also seen the problem with spawning lots of intermediate processes that do barely anything sucking up resources.

In an attempt to solve it I've been hacking around with a plugin that hooks into the `run` lifecycle and attempts to run scripts in-process when it thinks it can be done safely, no configuration required. Feel free to check it out; I'm curious to know if it helps. I don't have any plans to publish it or try to merge it upstream cause it seems so finicky and unstable, but I guess I could put something together if the maintainers are interested. I also have some improvements planned to fix some edge cases it currently doesn't handle well.

https://github.com/seansfkelley/berry/tree/alias-run/packages/plugin-run-inline
