### ISSUE TITLE
[Bug?]: webpack-cli needs v8-compile-cache？

### ISSUE THREAD

**Issue by prehonor** [yarnpkg/berry#3471]
/run/current-system/sw/bin/node /nix/store/v56k9vhq7657qyh48gp3a5jxjzgps1mm-yarn-1.22.10/libexec/yarn/bin/yarn.js run build
/ah/prehonor/js-project/word/.pnp.cjs:15668
    throw firstError;
    ^

Error: Cannot find module './lib/argument.js'
Require stack:
- /gh/prehonor/.yarn/cache/commander-npm-8.2.0-881bcc6660-8.zip/node_modules/commander/index.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/lib/webpack-cli.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/lib/bootstrap.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/cli.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-virtual-96f459d260/5/gh/prehonor/.yarn/cache/webpack-npm-5.53.0-265265042b-8.zip/node_modules/webpack/bin/webpack.js
Require stack:
- /gh/prehonor/.yarn/cache/commander-npm-8.2.0-881bcc6660-8.zip/node_modules/commander/index.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/lib/webpack-cli.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/lib/bootstrap.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/cli.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-virtual-96f459d260/5/gh/prehonor/.yarn/cache/webpack-npm-5.53.0-265265042b-8.zip/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.external_module_.Module._resolveFilename (/ah/prehonor/js-project/word/.pnp.cjs:15647:54)
    at Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.external_module_.Module._load (/ah/prehonor/js-project/word/.pnp.cjs:15460:36)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/gh/prehonor/.yarn/cache/v8-compile-cache-npm-2.3.0-80e1ef7fa3-8.zip/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/gh/prehonor/.yarn/cache/commander-npm-8.2.0-881bcc6660-8.zip/node_modules/commander/index.js:1:84)
    at Module._compile (/gh/prehonor/.yarn/cache/v8-compile-cache-npm-2.3.0-80e1ef7fa3-8.zip/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32) {
  code: 'MODULE_NOT_FOUND'
}

This is my .yarnrc.yml:

npmRegistryServer: "https://registry.npm.taobao.org"

yarnPath: .yarn/releases/yarn-3.0.2.cjs

enableGlobalCache: true

globalFolder: /home/prehonor/.yarn

#cacheFolder: /home/prehonor/.yarn/cache

#pnpUnpluggedFolder: /home/prehonor/.yarn/unplugged

nodeLinker: pnp

pnpMode: loose

this is my package.json:
{
  "name": "word",
  "packageManager": "yarn@3.0.2",
  "title": "miaomiao web",
  "author": "prehonor",
  "version": "1.1.1",
  "devDependencies": {
    "commander": "^8.2.0",
    "html-webpack-plugin": "^5.3.2",
    "import-local": "^3.0.2",
    "tslib": "^2.3.1",
    "v8-compile-cache": "^2.3.0",

    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.2.1"
  },
  "scripts": {
    "build": "webpack --version"
  },
  "dependencies": {
    "webpack": "^5.53.0",
    "envinfo": "^7.8.1"
  }
}

yarn dlx -q envinfo --preset jest

  System:
    OS: Linux 5.10 NixOS 21.05 (Okapi) 21.05.2873.6bfe71f2a4e (Okapi)
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 14.17.4 - /run/user/1000/xfs-cfc33071/node
    Yarn: 3.0.2 - /run/user/1000/xfs-cfc33071/yarn
    npm: 6.14.14 - /run/current-system/sw/bin/npm

**Comment by prehonor** [comment]
when my package.json is :
{
  "name": "word",
  "title": "miaomiao web",
  "author": "prehonor",
  "version": "1.1.1",
  "devDependencies": {
    "html-webpack-plugin": "*",
    "webpack-cli": "*",
    "webpack-dev-server": "*"
  },
  "scripts": {
    "build": "webpack --version"
  },
  "dependencies": {
    "webpack": "*"
  }
}

I get error 
/run/current-system/sw/bin/node /nix/store/v56k9vhq7657qyh48gp3a5jxjzgps1mm-yarn-1.22.10/libexec/yarn/bin/yarn.js run build
/ah/prehonor/js-project/word/.pnp.cjs:14115
    throw firstError;
    ^

Error: Your application tried to access v8-compile-cache, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: v8-compile-cache
Required by: /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/

Require stack:
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/cli.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-virtual-96f459d260/5/gh/prehonor/.yarn/cache/webpack-npm-5.53.0-265265042b-8.zip/node_modules/webpack/bin/webpack.js
    at Function.external_module_.Module._resolveFilename (/ah/prehonor/js-project/word/.pnp.cjs:14114:55)
    at Function.external_module_.Module._load (/ah/prehonor/js-project/word/.pnp.cjs:13913:48)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/cli.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.external_module_.Module._load (/ah/prehonor/js-project/word/.pnp.cjs:13963:14)
    at Module.require (internal/modules/cjs/loader.js:961:19)

Process finished with exit code 1


The same config used by pnpm  is ok good .

**Comment by arcanis** [comment]
Please make a basic effort to provide clear information.
