### ISSUE TITLE
[Bug?]:  yarn2 report that "Your application tried to access v8-compile-cache", but pnpm dosn't

### ISSUE THREAD

**Issue by prehonor** [yarnpkg/berry#3474]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

/run/current-system/sw/bin/node /nix/store/v56k9vhq7657qyh48gp3a5jxjzgps1mm-yarn-1.22.10/libexec/yarn/bin/yarn.js run build
/ah/prehonor/js-project/word/.pnp.cjs:14115
    throw firstError;
    ^

Error: Your application tried to access v8-compile-cache, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: v8-compile-cache
Required by: /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/

Require stack:
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/cli.js
- /ah/prehonor/js-project/word/.yarn/__virtual__/webpack-virtual-96f459d260/5/gh/prehonor/.yarn/cache/webpack-npm-5.53.0-265265042b-8.zip/node_modules/webpack/bin/webpack.js
    at Function.external_module_.Module._resolveFilename (/ah/prehonor/js-project/word/.pnp.cjs:14114:55)
    at Function.external_module_.Module._load (/ah/prehonor/js-project/word/.pnp.cjs:13913:48)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ah/prehonor/js-project/word/.yarn/__virtual__/webpack-cli-virtual-0afdb96e5a/5/gh/prehonor/.yarn/cache/webpack-cli-npm-4.8.0-89ebefbaa3-8.zip/node_modules/webpack-cli/bin/cli.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.external_module_.Module._load (/ah/prehonor/js-project/word/.pnp.cjs:13963:14)
    at Module.require (internal/modules/cjs/loader.js:961:19)

Process finished with exit code 1

### To reproduce

nothing

### Environment

```shell
System:
    OS: Linux 5.10 NixOS 21.05 (Okapi) 21.05.2873.6bfe71f2a4e (Okapi)
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 14.17.4 - /run/user/1000/xfs-e3002c7e/node
    Yarn: 3.0.2 - /run/user/1000/xfs-e3002c7e/yarn
    npm: 6.14.14 - /run/current-system/sw/bin/npm
```

### Additional context

This is my package.json :
{
  "name": "word",
  "title": "miaomiao web",
  "author": "prehonor",
  "version": "1.1.1",
  "devDependencies": {
    "html-webpack-plugin": "^5.3.2",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.2.1"
  },
  "scripts": {
    "build": "webpack --version"
  },
  "dependencies": {
    "webpack": "^5.53.0"
  }
}

**Comment by prehonor** [comment]
"commander" version too higher,I change it to ^7.2.0 then all is passed

**Comment by prehonor** [comment]
The radical error that my “globalFolder” is a softlink。
