### ISSUE TITLE
Default nodeLinker is node_modules instead of pnp

### ISSUE THREAD

**Issue by rtritto** [yarnpkg/berry#3482]
When I create a new project with yarn berry,  the default value of *nodeLinker* is *node_modules* as default.
It should be *pnp* ([source](https://yarnpkg.com/features/pnp#pnp-loose-mode)).

How can I reset the default value (equal to the initial setup of yarn) of *nodeLinker* to *pnp*?

# Steps to reproduce
1. `yarn init -y`
2. `yarn set version berry`
3. `yarn add @yarnpkg/sdks -D`
node_modules folder is created
4. `yarn sdks`

# Results
## Actual
```
Internal Error: This tool can only be used with projects using Yarn Plug'n'Play
    at SdkCommand.execute (C:\workspace\node_modules\@yarnpkg\sdks\lib\commands\SdkCommand.js:39:19)
    at SdkCommand.validateAndExecute (C:\workspace\node_modules\clipanion\lib\advanced\Command.js:64:37)
    at Cli.run (C:\workspace\node_modules\clipanion\lib\advanced\Cli.js:132:38)
    at Cli.runExit (C:\workspace\node_modules\clipanion\lib\advanced\Cli.js:149:39)
    at Object.<anonymous> (C:\workspace\node_modules\@yarnpkg\sdks\lib\cli.js:16:5)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

## Expect
```
Usage Error: No integrations have been provided as arguments, and no preexisting integrations could be found. Make sure to run `yarn sdks <integrations>` first, or `yarn sdks base` if you only need the SDK files and prefer to manage your own environment settings. Run `yarn sdks -h` to see the list of supported integrations.

$ sdks [--cwd #0] [-v,--verbose] ...
```

# Versions
yarn: 3.0.2
OS: Windows 10

# Workaround

To change manually value of *nodeLinker* to *pnp*, I added in `.yarnrc.yml`:
```yml
nodeLinker: pnp
...
```
Then I run `yarn` command and I got:
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: └ Completed
➤ YN0000: Done with warnings
```
Now when I run `yarn sdks` command, I got log in expected results.

**Comment by Thanaen** [comment]
Hi,
Your "workaround" is the actual way of enabling PNP, as described [in yarn's documentation](https://yarnpkg.com/getting-started/migration#enabling-it) 😊

**Comment by arcanis** [comment]
For context, when migrating a Yarn 1 project to Yarn 2, we automatically enable the node_modules linker (to easen the migration). To init w/ PnP, I think `yarn init -y2` should do the trick if your global Yarn is up to date (there's an known issue with Corepack, working on this).

**Comment by arcanis** [comment]
That being said, it's a little strange that you have the node-modules linker set on an empty project. Are you sure you didn't run `yarn add` prior the `yarn set version`?

**Comment by rtritto** [comment]
1. `yarn init -y`
2. `yarn set version berry`
3. `yarn config`

<details>
  <summary>Output</summary>

```bash
➤ YN0000: caFilePath                    null
➤ YN0000: cacheFolder                   'C:\\test-node-linker\\.yarn\\cache'
➤ YN0000: cacheKeyOverride              null
➤ YN0000: checksumBehavior              'throw'
➤ YN0000: cloneConcurrency              2
➤ YN0000: compressionLevel              'mixed'
➤ YN0000: defaultLanguageName           'node'
➤ YN0000: defaultProtocol               'npm:'
➤ YN0000: defaultSemverRangePrefix      '^'
➤ YN0000: enableColors                  true
➤ YN0000: enableGlobalCache             false
➤ YN0000: enableHyperlinks              true
➤ YN0000: enableImmutableCache          false
➤ YN0000: enableImmutableInstalls       false
➤ YN0000: enableInlineBuilds            false
➤ YN0000: enableInlineHunks             false
➤ YN0000: enableMessageNames            true
➤ YN0000: enableMirror                  true
➤ YN0000: enableNetwork                 true
➤ YN0000: enableProgressBars            true
➤ YN0000: enableScripts                 true
➤ YN0000: enableStrictSsl               true
➤ YN0000: enableTelemetry               true
➤ YN0000: enableTimers                  true
➤ YN0000: enableTransparentWorkspaces   true
➤ YN0000: globalFolder                  'C:\\Users\\<User>\\AppData\\Local\\Yarn\\Berry'
➤ YN0000: httpProxy                     null
➤ YN0000: httpRetry                     3
➤ YN0000: httpTimeout                   60000
➤ YN0000: httpsProxy                    null
➤ YN0000: ignoreCwd                     false
➤ YN0000: ignorePath                    false
➤ YN0000: immutablePatterns             []
➤ YN0000: initEditorConfig              Map(0) {}
➤ YN0000: initFields                    Map(0) {}
➤ YN0000: initScope                     null
➤ YN0000: installStatePath              'C:\\test-node-linker\\.yarn\\install-state.gz'
➤ YN0000: lastUpdateCheck               null
➤ YN0000: lockfileFilename              'yarn.lock'
➤ YN0000: logFilters                    []
➤ YN0000: networkConcurrency            Infinity
➤ YN0000: networkSettings               Map(0) {}
➤ YN0000: nmHoistingLimits              'none'
➤ YN0000: nmMode                        'classic'
➤ YN0000: nodeLinker                    'node-modules'
➤ YN0000: npmAlwaysAuth                 false
➤ YN0000: npmAuthIdent                  null
➤ YN0000: npmAuthToken                  null
➤ YN0000: npmPublishAccess              null
➤ YN0000: npmPublishRegistry            null
➤ YN0000: npmRegistries                 Map(0) {}
➤ YN0000: npmRegistryServer             'https://registry.yarnpkg.com'
➤ YN0000: npmScopes                     Map(0) {}
➤ YN0000: packageExtensions             Map(0) {}
➤ YN0000: patchFolder                   'C:\\test-node-linker\\.yarn\\patches'
➤ YN0000: pnpDataPath                   'C:\\test-node-linker\\.pnp.data.json'
➤ YN0000: pnpEnableInlining             true
➤ YN0000: pnpFallbackMode               'dependencies-only'
➤ YN0000: pnpIgnorePatterns             []
➤ YN0000: pnpMode                       'strict'
➤ YN0000: pnpShebang                    '#!/usr/bin/env node'
➤ YN0000: pnpUnpluggedFolder            'C:\\test-node-linker\\.yarn\\unplugged'
➤ YN0000: preferAggregateCacheInfo      false
➤ YN0000: preferInteractive             false
➤ YN0000: preferTruncatedLines          false
➤ YN0000: progressBarStyle              undefined
➤ YN0000: rcFilename                    '.yarnrc.yml'
➤ YN0000: telemetryInterval             7
➤ YN0000: telemetryUserId               null
➤ YN0000: unsafeHttpWhitelist           []
➤ YN0000: virtualFolder                 'C:\\test-node-linker\\.yarn\\__virtual__'
➤ YN0000: yarnPath                      'C:\\test-node-linker\\.yarn\\releases\\yarn-3.0.2.cjs'
➤ YN0000: Done
```
</details>

**Comment by rtritto** [comment]
@clemyan I have `.yarnrc.yml` file in `C:\Users\<User>` with `nodeLinker: node-modules`.
I solved removing it.

Anyway with `yarn config --why` command:
```
...
➤ YN0000: nodeLinker                    /C:/Users/<User>/.yarnrc.yml               'node-modules'
...
```

Thanks!

**Comment by tgelu** [comment]
> @clemyan I have `.yarnrc.yml` file in `C:\Users\<User>` with `nodeLinker: node-modules`. I solved removing it.
> 
> Anyway with `yarn config --why` command:
> 
> ```
> ...
> ➤ YN0000: nodeLinker                    /C:/Users/<User>/.yarnrc.yml               'node-modules'
> ...
> ```
> 
> Thanks!

After hours of debugging around the same issue I ended up here, which fixed it!

In my case the root cause of those files being generated in `\Users\<User>\.yarnrc.yml` was from running `yarn` somewhere outside a project by mistake. Strange that it initializes a project at that level. And this in combination with adding a `.yarnrc.yml` with a `nodeLinker` that overwrites the default is hard to catch if you're unfamiliar with yarn berry.
