### ISSUE TITLE
[cli] after bump from yarn 3.0.2 -> 3.1.0, adding `@squoosh/cli` fails: "Error: Invalid filename: "@squoosh/cli""

### ISSUE THREAD

**Issue by pgnd** [yarnpkg/berry#3673]
bumping an existing project from yarn 3.0.2 to yarn 3.1.0, with
```
cd ~/test
node -v
	v16.13.0
npm -v
	8.1.0
yarn --version
	3.1.0
```

installing `@squoosh/cli`
```
yarn add --dev @squoosh/cli
	➤ YN0000: ┌ Resolution step
	➤ YN0000: └ Completed
	➤ YN0000: ┌ Fetch step
	➤ YN0000: └ Completed in 0s 357ms
	➤ YN0000: ┌ Link step
	➤ YN0001: │ Error: Invalid filename: "@squoosh/cli"
	    at kr (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:312:6878)
	    at o (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:695:5923)
	    at o (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:695:6083)
	    at o (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:695:6083)
	    at o (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:695:6083)
	    at H6e (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:695:6164)
	    at async T6e (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:695:10478)
	    at async yce.finalizeInstall (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:680:26254)
	    at async Ke.linkEverything (/home/dev/test/.yarn/releases/yarn-3.1.0.cjs:441:14966)
	    at async /home/dev/test/.yarn/releases/yarn-3.1.0.cjs:444:4329
	➤ YN0000: └ Completed in 0s 683ms
	➤ YN0000: Failed with errors in 1s 292ms
```

Installing with 3.0.2 wasn't an issue; this is new to the 3.1.0 install

**Comment by merceyz** [comment]
Please follow the issue template, it's there for a reason
