### ISSUE TITLE
[Bug?]: pnpify 3.1.0 seems to incorrectly handle windows paths

### ISSUE THREAD

**Issue by leaumar** [yarnpkg/berry#3680]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Upgrading pnpify to 3.1.0 causes file handling issues that look like windows' backslash being interpreted as an escape character. Note the paths like `D:Projectscopy-selected-links.yarncache@yarnpkg-pnpify-npm-3.1.0-3723536d4d-44584d389a.zipnode_modules@yarnpkgpnpifylibindex.js` that it tries to access:

```
PS D:\Projects\copy-selected-links> yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ addons-linter@npm:3.20.0 doesn't provide @types/download (p925da), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:3.20.0 doesn't provide body-parser (pb71a4), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:3.20.0 doesn't provide download (pe8d32), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:3.20.0 doesn't provide express (p8e506), requested by addons-scanner-utils
➤ YN0002: │ addons-linter@npm:3.20.0 doesn't provide safe-compare (p8ea43), requested by addons-scanner-utils
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0019: │ @yarnpkg-shell-npm-2.4.1-1bf84da3ca-f173d61f6b.zip appears to be unused - removing
➤ YN0019: │ binjumper-npm-0.1.4-8ed133195d-07b0f2cf66.zip appears to be unused - removing
➤ YN0019: │ clipanion-npm-2.6.2-65049fe240-d162deedd0.zip appears to be unused - removing
➤ YN0019: │ comment-json-npm-2.4.2-ad40caa02b-80bc181741.zip appears to be unused - removing
➤ YN0019: │ has-own-prop-npm-2.0.0-d895adfe8c-8513ff9052.zip appears to be unused - removing
➤ YN0000: └ Completed in 0s 843ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=11e9ea The platform win32 is incompatible with this module, build skipped.
➤ YN0000: └ Completed in 0s 259ms
➤ YN0000: Done with warnings in 1s 414ms
PS D:\Projects\copy-selected-links> yarn build
➤ YN0000: executing [build]: run-s clean prettier lint compile qa package bundle
➤ YN0000: executing [clean]: rimraf dist extension .cache
➤ YN0000: executing [prettier]: prettier --write --list-different --ignore-unknown --ignore-path .gitignore . !.yarn !yarn.lock
➤ YN0000: executing [lint]: run-p eslint tsc
➤ YN0000: executing [tsc]: tsc --noEmit
➤ YN0000: executing [eslint]: eslint src/**/*.ts
➤ YN0000: executing [compile]: pnpify parcel build src/*.* --out-dir extension
D:\Projects\copy-selected-links\.pnp.js:19852
    throw firstError;
    ^

Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: D:Projectscopy-selected-links.yarncache@yarnpkg-pnpify-npm-3.1.0-3723536d4d-44584d389a.zipnode_modules@yarnpkgpnpifylibindex.js
Rejected candidate: D:Projectscopy-selected-links.yarncache@yarnpkg-pnpify-npm-3.1.0-3723536d4d-44584d389a.zipnode_modules@yarnpkgpnpifylibindex.js
Rejected candidate: D:Projectscopy-selected-links.yarncache@yarnpkg-pnpify-npm-3.1.0-3723536d4d-44584d389a.zipnode_modules@yarnpkgpnpifylibindex.js.js
Rejected candidate: D:Projectscopy-selected-links.yarncache@yarnpkg-pnpify-npm-3.1.0-3723536d4d-44584d389a.zipnode_modules@yarnpkgpnpifylibindex.js.json
Rejected candidate: D:Projectscopy-selected-links.yarncache@yarnpkg-pnpify-npm-3.1.0-3723536d4d-44584d389a.zipnode_modules@yarnpkgpnpifylibindex.js.node

Require stack:
- internal/preload
    at internalTools_makeError (D:\Projects\copy-selected-links\.pnp.js:19596:34)
    at resolveUnqualified (D:\Projects\copy-selected-links\.pnp.js:20635:13)
    at resolveRequest (D:\Projects\copy-selected-links\.pnp.js:20659:14)
    at Object.resolveRequest (D:\Projects\copy-selected-links\.pnp.js:20731:26)
    at Function.external_module_.Module._resolveFilename (D:\Projects\copy-selected-links\.pnp.js:19829:34)
    at Function.external_module_.Module._load (D:\Projects\copy-selected-links\.pnp.js:19694:48)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1276:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:484:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:78:3)
ERROR: "compile" exited with 1.
PS D:\Projects\copy-selected-links>
```

### To reproduce

```json
"devDependencies": {
    "@yarnpkg/pnpify": "^3.1.0",
    "parcel-bundler": "^1.12.5"
}
```

`yarn pnpify parcel` on windows throws the error.

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 16.13.0 - ~\AppData\Local\Temp\xfs-55d6d7a8\node.EXE
    Yarn: 2.4.3 - ~\AppData\Local\Temp\xfs-55d6d7a8\yarn.EXE
    npm: 8.1.0 - ~\scoop\apps\nvs\current\nodejs\node\16.13.0\x64\npm.CMD
```

### Additional context

Wanted to try it under yarn 3.0.2 as well (I have no idea if they're supposed to be major-version-locked), but then `yarn install` doesn't even work as it can't build `parcel-bundler` for some reason ([build.log](https://github.com/yarnpkg/berry/files/7447143/build.log)), so that was a dead end for me.

**Comment by larixer** [comment]
The bug was introduced by:
https://github.com/yarnpkg/berry/pull/3226
the relevant discussion is also here:
https://github.com/yarnpkg/berry/issues/3355#issuecomment-907124407

So far there were no interesting parties to submit the correct fix. We can roll back the PR: #3226, if no one volunteers to submit a good fix.

**Comment by leaumar** [comment]
Aha, ok, thanks. Can't say I believe I have a reasonable shot at fixing this as a total outsider either.

**Comment by larixer** [comment]
Yes, string escaping in JavaScript is a known very hard computer science problem. The ancient told - the legend is true and the chosen one should come one day, we must wait patiently.

**Comment by leaumar** [comment]
I assume the help-wanted is because there could be lots of complications about this change, and a big-picture solution that doesn't introduce other problems is going to be more complex than `str.replace(/\\/g, "\\\\")`?
