### ISSUE TITLE
[Feature] Error messages in a workspace should show which workspace they belong to

### ISSUE THREAD

**Issue by MarkKahn** [yarnpkg/berry#3812]
I recently renamed a package and saw this:

```sh
➜  modules git:(main) ✗ yarn
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: renamed-package@workspace:*: Workspace not found (renamed-package@workspace:*)
    at Fe.getWorkspaceByDescriptor (/main/.yarn/releases/yarn-berry.cjs:303:3502)
    at Eh.getCandidates (/main/.yarn/releases/yarn-berry.cjs:294:8755)
    at Xc.getCandidates (/main/.yarn/releases/yarn-berry.cjs:294:4947)
    at Xc.getCandidates (/main/.yarn/releases/yarn-berry.cjs:294:4947)
    at /main/.yarn/releases/yarn-berry.cjs:303:7643
    at Gl (/main/.yarn/releases/yarn-berry.cjs:242:4003)
    at y (/main/.yarn/releases/yarn-berry.cjs:303:7623)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 91ms
```

with no indication of which of the ~100 sub-projects the error was coming from.

Using yarn 3.0.2

**Comment by merceyz** [comment]
Please don't just delete the issue template

**Comment by MarkKahn** [comment]
The template isn't relevant here.  Error message doesn't contain the workspace that it came from.  End of issue and anything else is noise.

**Comment by arcanis** [comment]
This isn't yours to decide. If you can't take the time to feel a form to request we implement an enhancement for you, I don't see why we should leave your enhancement request open. Feel free to open a PR directly.
