### ISSUE TITLE
[Bug]: Installing from CodeSandbox CI registry~ fails to install their dependencies

### ISSUE THREAD

**Issue by Andarist** [yarnpkg/berry#3866]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a build on CodeSandbox CI like this one: https://ci.codesandbox.io/status/changesets/changesets/pr/705/builds/198643

with installation instructions like this:
```
# yarn 1
yarn add https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/apply-release-plan https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/assemble-release-plan https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/changelog-git https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/changelog-github https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/cli https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/config https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/errors https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-dependents-graph https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-github-info https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-release-plan https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-version-range-type https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/get-workspaces https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/git https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/logger https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/parse https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/pre https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/read https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/release-utils https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/test-utils https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/types https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/write
# yarn 2, 3
yarn add @changesets/apply-release-plan@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/apply-release-plan/_pkg.tgz @changesets/assemble-release-plan@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/assemble-release-plan/_pkg.tgz @changesets/changelog-git@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/changelog-git/_pkg.tgz @changesets/changelog-github@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/changelog-github/_pkg.tgz @changesets/cli@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/cli/_pkg.tgz @changesets/config@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/config/_pkg.tgz @changesets/errors@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/errors/_pkg.tgz @changesets/get-dependents-graph@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-dependents-graph/_pkg.tgz @changesets/get-github-info@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-github-info/_pkg.tgz @changesets/get-release-plan@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-release-plan/_pkg.tgz @changesets/get-version-range-type@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-version-range-type/_pkg.tgz get-workspaces@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/get-workspaces/_pkg.tgz @changesets/git@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/git/_pkg.tgz @changesets/logger@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/logger/_pkg.tgz @changesets/parse@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/parse/_pkg.tgz @changesets/pre@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/pre/_pkg.tgz @changesets/read@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/read/_pkg.tgz @changesets/release-utils@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/release-utils/_pkg.tgz @changesets/test-utils@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/test-utils/_pkg.tgz @changesets/types@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/types/_pkg.tgz @changesets/write@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/write/_pkg.tgz
# npm
npm i https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/apply-release-plan https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/assemble-release-plan https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/changelog-git https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/changelog-github https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/cli https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/config https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/errors https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-dependents-graph https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-github-info https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-release-plan https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/get-version-range-type https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/get-workspaces https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/git https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/logger https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/parse https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/pre https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/read https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/release-utils https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/test-utils https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/types https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/write
```

I'm only interested in installing explicitly the top-level package -> `@changesets/cli`, so given those instructions I attempt to:
```
yarn add --dev @changesets/cli@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/cli/_pkg.tgz
```
and, according to my understanding, this step succeeds but it fails quickly while trying to install its dependencies that are defined like this:
```json
{
  "dependencies": {
    "@changesets/apply-release-plan": "https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/apply-release-plan",
  }
}
```

This results in:
```
➤ YN0001: │ Error: @changesets/apply-release-plan@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/apply-release-plan isn't supported by any available resolver
    at Ed.getResolverByDescriptor (/project/.yarn/releases/yarn-3.2.0-rc.8.cjs:395:1658)
    at Ed.bindDescriptor (/project/.yarn/releases/yarn-3.2.0-rc.8.cjs:395:1047)
    at oe (/project/.yarn/releases/yarn-3.2.0-rc.8.cjs:441:7014)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### To reproduce

```
yarn add --dev @changesets/cli@https://pkg.csb.dev/changesets/changesets/commit/34fbdd76/@changesets/cli/_pkg.tgz
```

### Environment

```shell
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.20.0 - /private/var/folders/ws/tlwxqvs5407f21nxy7w8bgr80000gp/T/xfs-0f985bda/node
    Yarn: 3.2.0-rc.8 - /private/var/folders/ws/tlwxqvs5407f21nxy7w8bgr80000gp/T/xfs-0f985bda/yarn
    npm: 7.1.0 - ~/.nvm/versions/node/v12.20.0/bin/npm
```

### Additional context

npm and pnpm manage to install this

I've tried both with yarn 3.0.2 and 3.2.0-rc.8

**Comment by ylemkimon** [comment]
Related: #3327

I think this should be fixed on the CodeSandbox's side, they should declare dependencies ending with `.tgz` in `package.json`. Could you open an issue there too?

**Comment by Andarist** [comment]
Yep, you are right - this is a duplicate 🙈 I put some more context about the problem [here](https://github.com/codesandbox/codesandbox-ci-ui/pull/34#issuecomment-995829289) and I hope that CodeSandbox CI maintainers will give this a look.
