### ISSUE TITLE
[Bug]:  TypeError: e is not iterable

### ISSUE THREAD

**Issue by dorianmariefr** [yarnpkg/berry#3869]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn up` fails with this:

```
➤ YN0000: ┌ Link step
➤ YN0001: │ TypeError: e is not iterable
    at Function.isManifestFieldCompatible (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:327107)
    at Module.y (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:271098)
    at J.installPackage (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:179128)
    at ie.linkEverything (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:377801)
    at async /Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:387577
    at async f.startTimerPromise (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:397980)
    at async ie.install (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:387361)
    at async /Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:84242
    at async Function.start (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:396677)
    at async de.execute (/Users/dorianmariefr/src/socializus/.yarn/releases/yarn-2.4.3.cjs:2:84140)
➤ YN0000: └ Completed
```

### To reproduce

here is my package.json

```
{
  "dependencies": {
    "@babel/core": "*",
    "@babel/eslint-parser": "*",
    "@babel/preset-react": "*",
    "@hotwired/stimulus": "*",
    "@hotwired/turbo-rails": "*",
    "@prettier/plugin-ruby": "*",
    "@prettier/plugin-xml": "*",
    "@rails/actioncable": "*",
    "@tailwindcss/line-clamp": "*",
    "ansi-html": "*",
    "autoprefixer": "*",
    "esbuild": "*",
    "esbuild-plugin-stimulus": "*",
    "eslint": "*",
    "eslint-config-prettier": "*",
    "eslint-config-standard": "*",
    "eslint-plugin-import": "*",
    "eslint-plugin-jsx": "*",
    "eslint-plugin-node": "*",
    "eslint-plugin-promise": "*",
    "eslint-plugin-react": "*",
    "glob": "*",
    "google-maps-react": "*",
    "husky": "*",
    "lint-staged": "*",
    "lodash": "*",
    "lowdash": "*",
    "mustache": "*",
    "parameterize": "*",
    "parse-price": "*",
    "postcss": "*",
    "postcss-cli": "*",
    "postcss-import": "*",
    "prettier": "*",
    "prettier-plugin-sh": "*",
    "prop-types": "*",
    "react": "*",
    "react-dom": "*",
    "tailwindcss": "*"
  },
  "lint-staged": {
    "*.json": [
      "sort-json"
    ],
    "*.yml": [
      "sort-yaml"
    ],
    "config/locales/*": [],
    "{*.js,*.jsx}": [
      "eslint --fix"
    ],
    "{Gemfile,Rakefile,!(db/schema.rb)*.{rb,rake,ru}}": [
      "bundle exec rubocop -A"
    ],
    "{Gemfile,Rakefile,Podfile,bin/*,!(db/schema.rb)*.{js,jsx,rb,rake,ru,json,xml,yml,erb,jbuilder}}": [
      "prettier --write"
    ]
  },
  "name": "socializus",
  "private": true,
  "scripts": {
    "build": "NODE_ENV=production bin/build.js",
    "build-dev": "bin/build.js",
    "build:css": "bin/build-css.sh",
    "prepare": "husky install",
    "prettier": "prettier"
  },
  "version": "0.1.0",
  "packageManager": "yarn@2.4.3"
}
```

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
  Binaries:
    Node: 17.0.1 - /private/var/folders/rr/_xd59_bs4b58pncgf_tf39_00000gn/T/xfs-d52bef0b/node
    Yarn: 2.4.3 - /private/var/folders/rr/_xd59_bs4b58pncgf_tf39_00000gn/T/xfs-d52bef0b/yarn
    npm: 8.1.0 - /usr/local/bin/npm
```

### Additional context

I just upgraded from yarn 1 to yarn 2, using node modules

**Comment by merceyz** [comment]
Could you see if the issue has been fixed in the latest version? We're currently at `3.1.1`
```sh
yarn set version berry
```

**Comment by dorianmariefr** [comment]
works fine in latest, thanks
