### ISSUE TITLE
[Bug]: The "file" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by MartinHotmann** [yarnpkg/berry#3986]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In my package.json I have cinfigurated a "script" like this (most data removed for making it clean):

```
{
    "name": "",
    "version": "",
    "description": "",
    "main": "index.html",
    "author": "",
    "license": "MIT",
    "scripts": {
        "clean": "> assets/assets/app.min.css",
    },
    "dependencies": {
    }
}
```
the command actually is a very simple shell command which removes the content of this text file. This worked pretty fine with Yarn v1 (v1.22.7), but since I upgraded to V3 (v3.2.0-rc.10) it does not work.

### To reproduce

try to run a predefined script in package.json and include someting like I mentioned above.

### Environment

```shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (6) x64 QEMU Virtual CPU version 2.5+
  Binaries:
    Node: 17.3.1 - /tmp/xfs-bb4d67d9/node
    Yarn: 3.2.0-rc.10 - /tmp/xfs-bb4d67d9/yarn
    npm: 8.3.1 - /usr/bin/npm
```

### Additional context

Worked with Yarn 1, does not work with Yarn 3.

Thanks for looking into this, would love to upgrade, but need my scripts/commands to still work.

Full Error:

```
$ yarn clean
Type Error: The "file" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at normalizeSpawnArguments (node:child_process:503:3)
    at Object.spawn (node:child_process:691:13)
    at d1 (/var/www/vhosts/domain.com/httpdocs/berryTest/.yarn/releases/yarn-3.2.0-rc.10.cjs:4:7429)
    at Ld.implementation (/var/www/vhosts/domain.com/httpdocs/berryTest/.yarn/releases/yarn-3.2.0-rc.10.cjs:396:18376)
    at Ld.exec (/var/www/vhosts/domain.com/httpdocs/berryTest/.yarn/releases/yarn-3.2.0-rc.10.cjs:399:1582)
    at Ld.run (/var/www/vhosts/domain.com/httpdocs/berryTest/.yarn/releases/yarn-3.2.0-rc.10.cjs:399:1753)
    at /var/www/vhosts/domain.com/httpdocs/berryTest/.yarn/releases/yarn-3.2.0-rc.10.cjs:405:787
    at /var/www/vhosts/domain.com/httpdocs/berryTest/.yarn/releases/yarn-3.2.0-rc.10.cjs:405:5028
```

**Comment by Ayc0** [comment]
I just encountered the same issue. On my end, I had something like `build --version=\"$(< ./version)\"`, I fixed it by replacing the `<` by `cat`.

I think there is a bug with `<` and `>` .

**Comment by maguroid** [comment]
this error is caused when empty command is passed to "name" argument for [makeProcess()](https://github.com/yarnpkg/berry/blob/7f64a982ff00320546f5c7e6ab8069bbfa1ab08d/packages/yarnpkg-shell/sources/pipe.ts#L41).

I want to try fixing it as my first contribution. But not coming up any good idea...
How can I handle the case when name is undefined?
In that case, we need to define another child process?(but child process must have non-empty string).

I'd be happy if anyone gave me advice.

**Comment by arcanis** [comment]
A fix would be appreciated! I think we'd need to implement a [builtin](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-shell/sources/index.ts#L114) that prints on stdout what it receives in stderr (say, `__ysh_passthrough`), and treat `< foo` as an alias to `__ysh_passthrough < foo`. And writes a few [unit tests](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-shell/tests/shell.test.ts#L88) around that 🤔

**Comment by maguroid** [comment]
Thank you for your replying! Sure. I'll try it.

**Comment by maguroid** [comment]
I have few questions. I didn't get how this command execution program works...

1. ">" is defined as type "redirection".  Why not "argument"? and when the type defined?
2. When BUILTINS constant are used? If "__ysh_passthrough" is defined, how we combine it with ">" mark?

**Comment by maguroid** [comment]
I may know how to fix this issue. I gonna send PR today.

**Comment by maguroid** [comment]
↑ I add __ysh_passthrough function to BULITINS but it doesn't work...
Could someone review my code? Thanks...

**Comment by vabaimova** [comment]
Is this still an issue?

**Comment by Jellyfishboy** [comment]
Still an issue,
