### ISSUE TITLE
[Bug?]: Problem in the bowels of pnpify (PortableNodeModulesFS.readdirPromise) when using serverless-esbuild plugin

### ISSUE THREAD

**Issue by francisu** [yarnpkg/berry#4069]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

When using serverless-esbuild,  doing a deploy or package, I get the following stack trace:

```
  TypeError: Cannot destructure property 'withFileTypes' of '(intermediate value)(intermediate value)(intermediate value)' as it is null.
      at PortableNodeModulesFS.readdirPromise (/Users/francis/d/IdeaProjects/product/.yarn/__virtual__/@yarnpkg-pnpify-virtual-3ce804316c/0/cache/@yarnpkg-pnpify-npm-2.3.3-d139ee88e8-a8fcde14e5.zip/node_modules/@yarnpkg/pnpify/lib/NodeModulesFS.js:303:31)
      at NodeModulesFS.readdirPromise (/Users/francis/d/IdeaProjects/product/.yarn/unplugged/@yarnpkg-fslib-npm-2.6.0-ec8b110e16/node_modules/@yarnpkg/fslib/lib/ProxiedFS.js:198:28)
      at URLFS.readdirPromise (/Users/francis/d/IdeaProjects/product/.yarn/unplugged/@yarnpkg-fslib-npm-2.6.0-ec8b110e16/node_modules/@yarnpkg/fslib/lib/ProxiedFS.js:198:28)
      at /Users/francis/d/IdeaProjects/product/.yarn/unplugged/@yarnpkg-fslib-npm-2.6.0-ec8b110e16/node_modules/@yarnpkg/fslib/lib/patchFs.js:131:30
      at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
 
The offending code appears to be:

`.yarn/unplugged/@yarnpkg-pnpify-virtual-6e98a8765b/node_modules/@yarnpkg/pnpify/lib/NodeModulesFS.js`

Here is the way I patched it to work around the problem:

```
diff --git a/lib/NodeModulesFS.js b/lib/NodeModulesFS.js
index 19b940ed34d3c84b8b375de55d4d72ab448ce12f..7886a68145f0c446f5c96981ab1bb9ca03c96ea4 100644
--- a/lib/NodeModulesFS.js
+++ b/lib/NodeModulesFS.js
@@ -300,7 +300,8 @@ class PortableNodeModulesFS extends fslib_2.FakeFS {
                 return this.baseFs.readFileSync(this.resolveFilePath(p), encoding);
         }
     }
-    async readdirPromise(p, { withFileTypes } = {}) {
+    async readdirPromise(p, args) {
+        const { withFileTypes } = args || {};
         const pnpPath = this.resolvePath(p);
         if (pnpPath.dirList || this.resolvePath(fslib_1.ppath.join(p, `node_modules`)).dirList) {
             let fsDirList = [];
```

The really offending code is probably somewhere in the `serverless-esbuild` plugin, since that's what I was using. But I was unable to get any good stack trace (everything was in `pnp.cjs`) so I could not tell what it might be doing wrong.

### To reproduce

Don't have a small reproduction, sorry.

I use Serverless framework, version 2.72.2 with serverless-esbuild 1.23.4 and do a serverless deploy and this problem is encountered after the esbuild compile.

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.3 - /private/var/folders/s7/1ndbqwz50xd84b32lkmj97900000gn/T/xfs-7c8e7663/node
    Yarn: 3.1.1 - /private/var/folders/s7/1ndbqwz50xd84b32lkmj97900000gn/T/xfs-7c8e7663/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
```

**Comment by francisu** [comment]
nvm, I removed 'pnpify' from the yarn command line and the problem went away.

**Comment by merceyz** [comment]
This was also fixed in https://github.com/yarnpkg/berry/pull/3239
