### ISSUE TITLE
[Bug?]:  ENOENT when adding plugin from local path

### ISSUE THREAD

**Issue by d3dc** [yarnpkg/berry#4195]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

```
Internal Error: ENOTDIR: not a directory, open 'node_modules/archive/package.json'
    at Cs (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:314:10129)
    at Do (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:314:10462)
    at Ai.resolveFilename (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:319:21646)
    at Ai.readFileBuffer (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:319:30774)
    at Ai.readFilePromise (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:319:30494)
    at zh.readFilePromise (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:319:37486)
    at Pa.readFilePromise (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:319:37486)
    at sl.loadFile (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:394:32946)
    at Function.fromFile (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:394:32503)
    at Function.tryFind (/Users/sam/Workspace/@me/banana/.yarn/releases/yarn-3.2.0.cjs:394:32224)
```

### To reproduce

1. `yarn plugin add ${local_path}`

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 17.6.0 - /private/var/folders/k5/3nc4cxkj20xbxgyz0sc983w40000gn/T/xfs-c6ab2f54/node
    Yarn: 3.2.0 - /private/var/folders/k5/3nc4cxkj20xbxgyz0sc983w40000gn/T/xfs-c6ab2f54/yarn
    npm: 8.5.3 - /usr/local/bin/npm
```

### Additional context

Seems very similar to #3449

**Comment by d3dc** [comment]
Still occurring with a built plugin in a clean test repo.

The plugin can be installed in its own repo.
