### ISSUE TITLE
[Bug?]: ESM import nested `js` file

### ISSUE THREAD

**Issue by rtritto** [yarnpkg/berry#4347]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Using ES Modules, fail to resolve a js file contained in a dependency.

### To reproduce

1. `yarn init -y`
2. `yarn set version canary`
3. `yarn add next-pwa`
4. Add `"type": "module"` to `package.json`
5. Create `index.js` file:
```js
import 'next-pwa/cache'
```
6. `yarn node index`

## Actual
```console
C:\0-test-yarn\.pnp.cjs:13923
  return Object.defineProperties(new Error(message), {
                                 ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: C:\0-test-yarn\.yarn\__virtual__\next-pwa-virtual-e0fcc60274\3\Users\<User>\AppData\Local\Yarn\Berry\cache\next-pwa-npm-5.5.0-df69a3eb7d-9.zip\node_modules\next-pwa\cache
Not found: C:\0-test-yarn\.yarn\__virtual__\next-pwa-virtual-e0fcc60274\3\Users\<User>\AppData\Local\Yarn\Berry\cache\next-pwa-npm-5.5.0-df69a3eb7d-9.zip\node_modules\next-pwa\cache

    at makeError (C:\0-test-yarn\.pnp.cjs:13923:34)
    at resolveUnqualified (C:\0-test-yarn\.pnp.cjs:14919:13)
    at resolveRequest (C:\0-test-yarn\.pnp.cjs:14935:14)
    at Object.resolveRequest (C:\0-test-yarn\.pnp.cjs:14991:26)
    at resolve$1 (file:///C:/0-test-yarn/.pnp.loader.mjs:220:25)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

## Expect
No error.

## Workaround
Replace `import 'next-pwa/cache'` with `import 'next-pwa/cache.js'`

### Environment

```shell
System:
  OS: Windows 11
Binaries:
  Node: 16.4.0
  Yarn: 4.0.0-rc.2
```

**Comment by merceyz** [comment]
This is how ESM works, you're required to specify the full path. If you use the `node-modules` linker in your reproduction you'll see the following error from node:
```
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/foo/node_modules/next-pwa/cache' imported from /foo/index.js
Did you mean to import next-pwa/cache.js?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:981:10)
    at defaultResolve (node:internal/modules/esm/resolve:1078:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
