### ISSUE TITLE
Running `patch-commit` for a package that has a builtin patch now fails with

### ISSUE THREAD

**Issue by merceyz** [yarnpkg/berry#4441]
Running `patch-commit` for a package that has a builtin patch now fails with
```
Internal Error: Assertion failed: Expected the resolution to have been registered
    at PatchCommitCommand.execute (/berry/packages/plugin-patch/sources/commands/patchCommit.ts:82:15)  
    at PatchCommitCommand.validateAndExecute (/berry/.yarn/__virtual__/clipanion-virtual-6f45223597/0/cache/clipanion-npm-3.2.0-rc.4-8470d16306-c9d8ba9e16.zip/node_modules/clipanion/lib/advanced/Command.js:67:26)
    at Cli.run (/berry/.yarn/__virtual__/clipanion-virtual-6f45223597/0/cache/clipanion-npm-3.2.0-rc.4-8470d16306-c9d8ba9e16.zip/node_modules/clipanion/lib/advanced/Cli.js:149:24)
    at Cli.runExit (/berry/.yarn/__virtual__/clipanion-virtual-6f45223597/0/cache/clipanion-npm-3.2.0-rc.4-8470d16306-c9d8ba9e16.zip/node_modules/clipanion/lib/advanced/Cli.js:158:28)
    at exec (/berry/packages/yarnpkg-cli/sources/main.ts:148:7)
    at run (/berry/packages/yarnpkg-cli/sources/main.ts:48:7)
```

_Originally posted by @merceyz in https://github.com/yarnpkg/berry/issues/4218#issuecomment-1072905294_

**Comment by oxc** [comment]
I can confirm this for typescript 4.8.4.

**Comment by Deco** [comment]
I can confirm this for TypeScript 4.9.3 on Yarn 3.3.0 with nodeLinker: node-modules

**Comment by mrflip** [comment]
Any fix to this? I was able to limp the patch command home (I think) by supplying the resolution stanza myself: 

```
  "resolutions": {
    "typescript@5.0.4": "patch:typescript@5.0.4#.yarn/patches/typescript-npm-5.0.4-122f6a883a.patch"
  },
```

but nothing happens when I yarn install, because I think either the builtin-compat one is not being patched or it won't do multiple patches or something. I tried applying my patch to the patched zip, but I don't know how to calculate the checksup to cheat it home. I think that I can't use ts from a git repo because I'll need the yarn patches applied

Any advice on how to arm-twist yarn into applying these changes welcome.

**Comment by Downchuck** [comment]
This will happen all the time when there's an entry for the package in resolutions itself - seems some bugs in that.

**Comment by blutorange** [comment]
Also happens when you already have a custom patch for a package and try to add an additional patch via `yarn patch --update dom-to-image` and `yarn patch-commit -s /tmp/xfs-9bd1beff/user`.

**Comment by rpk-red** [comment]
any resolution to this problem?
