### ISSUE TITLE
[Bug?]: Error occurred when changing node versions using nvm

### ISSUE THREAD

**Issue by jeesoo-dable** [yarnpkg/berry#4581]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

When I tried to change the node versions using nvm, such as from 16.15.1 to 18.3.0 and again 16.15.1 or other lower node versions, I met the error message as below.

When I clean the cache directory (`yarn clean cache` or just delete .yarn/cache) and execute `yarn`, it won't appear. But I continuously remove the cache and install all over again for changing node versions.

It doesn't appear when using Macbook using Intel chip, but appear only with M1 chip.

I found [a blog article](https://melonicedlatte.com/2022/05/11/134700.html) mentioning the same issue as I wrote. Is there anyone who gets the same error as I have?

```
Internal Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at Object.deserialize (v8.js:343:7)
    at Ke.restoreInstallState (/Users/jeesoohong/.node/corepack/yarn/3.1.1/yarn.js:447:965)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async wC.execute (/Users/jeesoohong/.node/corepack/yarn/3.1.1/yarn.js:486:14746)
    at async wC.validateAndExecute (/Users/jeesoohong/.node/corepack/yarn/3.1.1/yarn.js:337:620)
    at async oo.run (/Users/jeesoohong/.node/corepack/yarn/3.1.1/yarn.js:351:1846)
    at async oo.runExit (/Users/jeesoohong/.node/corepack/yarn/3.1.1/yarn.js:351:2013)
    at async i (/Users/jeesoohong/.node/corepack/yarn/3.1.1/yarn.js:448:12377)
    at async r (/Users/jeesoohong/.node/corepack/yarn/3.1.1/yarn.js:448:10617)
```

### To reproduce

```
nvm use 16.15.1
yarn
nvm use 18.3.0
nvm use 16.15.1 (or nvm use 14.19.3)
yarn
```

### Environment

```shell
OS: MacOS 12.2.1
CPU: Apple M1 Pro

node: /Users/USERNAME/.nvm/versions/node/v16.13.1/bin/node (using nvm, installed by [nvm install script](https://github.com/nvm-sh/nvm#installing-and-updating))
yarn: /Users/USERNAME/.nvm/versions/node/v16.13.1/bin/yarn (version 3.1.1)
```

**Comment by jeesoo-dable** [comment]
Thank you so much! 😀
