### ISSUE TITLE
[Bug?]: eslint sdk does not work with eslint 8.19.0

### ISSUE THREAD

**Issue by noahnu** [yarnpkg/berry#4606]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Tried upgrading from eslint 8.16.0 to 8.19.0 and after applying @yarnpkg/sdks for vscode, the VSCode extension will not start. It crashes with:

```
[Error - 11:39:11 a.m.] Restarting client failed
Error: Stopping the server timed out
    at /Users/noah/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/client/out/extension.js:1:108052
    at w.restart (/Users/noah/.vscode/extensions/dbaeumer.vscode-eslint-2.2.6/client/out/extension.js:1:266164)
```

### To reproduce

Install eslint 8.19.0, run `yarn dlx @yarnpkg/sdks` and reload VSCode.

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.1 - /private/var/folders/ft/b9p2qq2n2h31j10zcc8d48qh0000gp/T/xfs-dbcbdecf/node
    Yarn: 3.2.1 - /private/var/folders/ft/b9p2qq2n2h31j10zcc8d48qh0000gp/T/xfs-dbcbdecf/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    VSCode: 1.68.1
```

**Comment by noahnu** [comment]
Ends up my VSCode was using 16.13.0 which has the bug around the esm loader. I guess eslint 8.19 uses ESM. Adding:

```
 "eslint.runtime": "/Users/noah/.nvm/versions/node/v16.15.1/bin/node"
```

to my vscode settings fixes the problem.
