### ISSUE TITLE
[Bug?]: Expected root to be registered when upgrading package

### ISSUE THREAD

**Issue by caseybaggz** [yarnpkg/berry#4625]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Repo: https://github.com/pluralsight/tva
Workspace: website
Yarn: v3.1.0 PnP

### Context
Trying to upgrade @docusaurus packages to latest. Normally works fine with no problem using:
```
yarn workspace website up @docusuarus/core@latest
```
### Bug
When using the following script, now produces
```
yarn workspace website up @docusaurus/core@latest

➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: Assertion failed: Expected the root to be registered
    at lUe (/Users/XXX/tva/.yarn/releases/yarn-berry.cjs:448:4565)
    at Ke.resolveEverything (/Users/XXX//tva/.yarn/releases/yarn-berry.cjs:441:8306)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/XXX/tva/.yarn/releases/yarn-berry.cjs:444:2138
    at async Fe.startTimerPromise (/Users/XXX/tva/.yarn/releases/yarn-berry.cjs:412:3730)
    at async Ke.install (/Users/XXX/tva/.yarn/releases/yarn-berry.cjs:444:2077)
    at async /Users/XXX/tva/.yarn/releases/yarn-berry.cjs:578:75
    at async Fe.start (/Users/XXX/tva/.yarn/releases/yarn-berry.cjs:412:2287)
    at async uf.executeUpClassic (/Users/XXX/tva/.yarn/releases/yarn-berry.cjs:578:5)
    at async uf.execute (/Users/XXX/tva/.yarn/releases/yarn-berry.cjs:573:1197)
➤ YN0000: └ Completed in 1s 590ms
➤ YN0000: Failed with errors in 1s 592ms
```

### To reproduce

1. Clone repo
2. Run `yarn workspace website up @docusaurus/core@latest`
3. Get error code

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 18.5.0 - /private/var/folders/zf/h9zmyq_d1yq0p573mfvl2vf80000gq/T/xfs-634c80dd/node
    Yarn: 3.1.0 - /private/var/folders/zf/h9zmyq_d1yq0p573mfvl2vf80000gq/T/xfs-634c80dd/yarn
    npm: 8.12.1 - /usr/local/bin/npm
```

**Comment by arpitBhalla** [comment]
Still facing with yarn@3.2.4
