### ISSUE TITLE
[Bug]: `yarn create` doesn't work with `@scope`

### ISSUE THREAD

**Issue by alan-agius4** [yarnpkg/berry#4626]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using `yarn create` the version specifier doesn't work when the package is scoped. Example `yarn create @angular@next`.

```
 YN0000: ┌ Resolution step
➤ YN0001: │ Error: create-@angular@next isn't supported by any available resolver
    at Bd.getResolverByDescriptor (/.node/corepack/yarn/3.2.1/yarn.js:396:1664)
    at Bd.bindDescriptor (/.node/corepack/yarn/3.2.1/yarn.js:396:1053)
    at ee (/.node/corepack/yarn/3.2.1/yarn.js:442:6954)
```

### To reproduce

```
yarn create @angular@next
```

### Environment

```shell
System:
    OS: Linux 5.17 Debian GNU/Linux rodete 12 (rodete)
    CPU: (48) x64 AMD EPYC 7B12
  Binaries:
    Node: 16.15.1 - /tmp/xfs-cbdcc8f4/node
    Yarn: 3.2.1 - /tmp/xfs-cbdcc8f4/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

**Comment by merceyz** [comment]
`@angular` isn't a valid package identifier
```sh
yarn dlx @angular/cli@next new my-project --package-manager yarn
```

**Comment by alan-agius4** [comment]
@merceyz, why not? `@angular/create` is a valid package that we just released as pre-release yesterday. 

See: https://www.npmjs.com/package/@angular/create

Does this mean that Yarn 2 and 3 no longer support scoped packages when using `yarn create`?

**Comment by merceyz** [comment]
I see [npm documents](https://docs.npmjs.com/cli/v8/commands/npm-init#synopsis)
```console
npm init <@scope> (same as `npx <@scope>/create`)
```
so I'll add support for that as well.

Though note it doesn't work with npm
```console
$ npm init @angular@next
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@angular" of package "@angular@next/create": name can only contain URL-friendly characters.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-15T16_07_31_388Z-debug-0.log
```

**Comment by alan-agius4** [comment]
@merceyz, yeah I am aware of that. I have a separate issue for that https://github.com/npm/cli/issues/5175
