### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by sargunv** [yarnpkg/berry#4918]
- [x] I'd be willing to implement this feature ([contributing guide](https://yarnpkg.com/advanced/contributing))
- [x] This feature is important to have in this repository; a contrib plugin wouldn't do

**Describe the user story**

While migrating from `npm publish` to `yarn npm publish`, we encountered the lack of a dry run flag in `yarn npm publish`. We use the dry run flag to help us validate our publishing scripts without needing to clean up published packages after the fact.

**Describe the solution you'd like**

We'd like a `--dry-run` flag that just lists what would have been published without publishing anything, similar to `yarn pack`.

**Describe the drawbacks of your solution**

Maintenance risk of future tweaks to the publish command forgetting to check the flag.

**Describe alternatives you've considered**

We could potentially use `yarn pack --dry-run` as our publishing dryrun.

**Comment by arcanis** [comment]
> We could potentially use yarn pack `--dry-run` as our publishing dryrun.

Yes, that's what you should do

**Comment by sargunv** [comment]
👍

**Comment by worldomkar** [comment]
Please re-open. This issue isn't yet fixed for those of us not on yarn berry.

Definitely like to have a dry run as by default publish will publish to public registry - which is not what we want. We want to make sure it points to private registry, gets correct files in - then publish to the private registry. without dry run, there are no logs showing that yarn would use private registry to publish.

```
$ yarn publish --verbose      
yarn publish v1.22.22
verbose 0.116235583 Checking for configuration file "/source/cra-demo/.npmrc".
verbose 0.11646975 Checking for configuration file "/home/user/.npmrc".
verbose 0.11675975 Found configuration file "/home/user/.npmrc".
verbose 0.117109875 Checking for configuration file "/home/user/.nvm/versions/node/v22.5.1/etc/npmrc".
verbose 0.117286375 Checking for configuration file "/source/cra-demo/.npmrc".
verbose 0.117388916 Checking for configuration file "/source/.npmrc".
verbose 0.118577875 Checking for configuration file "/source/cra-demo/.yarnrc".
verbose 0.118723208 Checking for configuration file "/home/user/.yarnrc".
verbose 0.118776125 Found configuration file "/home/user/.yarnrc".
verbose 0.118930208 Checking for configuration file "/home/user/.nvm/versions/node/v22.5.1/etc/yarnrc".
verbose 0.119021583 Checking for configuration file "/source/cra-demo/.yarnrc".
verbose 0.119094208 Checking for configuration file "/source/.yarnrc".
verbose 0.119153416 Checking for configuration file "/.yarnrc".
verbose 0.121961458 current time: 2024-08-07T20:07:37.322Z
verbose 0.130740458 Error: Package marked as private, not publishing.
    at MessageError.ExtendableBuiltin (/home/user/.nvm/versions/node/v22.5.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/user/.nvm/versions/node/v22.5.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v22.5.1/lib/node_modules/yarn/lib/cli.js:87097:13)
    at Generator.next (<anonymous>)
    at step (/home/user/.nvm/versions/node/v22.5.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/user/.nvm/versions/node/v22.5.1/lib/node_modules/yarn/lib/cli.js:321:13
error Package marked as private, not publishing.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

At least reason out properly if this isn't possible to implement? (Please don't mention development priority as users have moved on to >2 versions; I'm asking specific technical reasons.) Which I doubt would be too complex to implement, as this flag should add only a conditional statement to actual publish effort and "console.info" out going to publish to xyz registry.

If there is a known alternative flag - that does what is expected, I'm happy with using that flag.

**Comment by sargunv** [comment]
I'm not a yarn maintainer but my understanding is Yarn v1 is no longer receiving new features or fixes, as it's many years out of date. It's also not in this repository. I won't be reopening this issue.
