### ISSUE TITLE
[Bug?]: yarn install fails with fatal error: too many errors emitted, stopping now [-ferror-limit=]

### ISSUE THREAD

**Issue by ChurikiTenna** [yarnpkg/berry#4919]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

yarn install emit `fatal error: too many errors emitted, stopping now [-ferror-limit=]`.
The project was created 2 years ago by another person, and I am really new to this.. so sorry if this is a stupid report.

logs:
```
...
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#~builtin<compat/fsevents>::version=1.2.13&hash=18f3a7 must be built because it never has been before or the last one failed
➤ YN0009: │ realm@npm:2.29.2 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/cv/yb103sl92sn87wng_mvscb_80000gn/T/xfs-c3aab6f5/build.log)
➤ YN0007: │ aitem@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ aitem@workspace:. couldn't be built successfully (exit code 2, logs can be found here: /private/var/folders/cv/yb103sl92sn87wng_mvscb_80000gn/T/xfs-27f7def6/build.log)
➤ YN0000: └ Completed in 1m 16s
➤ YN0000: Failed with errors in 1m 50s
```
inside of  /private/var/folders/cv/yb103sl92sn87wng_mvscb_80000gn/T/xfs-c3aab6f5/build.log):
```
...
In file included from ../src/node/node_init.cpp:19:
In file included from ../src/node/node_init.hpp:29:
In file included from ../src/node/node_class.hpp:23:
../src/js_class.hpp:92:17: error: no type named 'StringPropertyGetterCallback' in 'realm::node::Types'
    typename T::StringPropertyGetterCallback getter;
    ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/node/node_class.hpp:368:16: note: in instantiation of template class 'realm::js::StringPropertyType<realm::node::Types>' requested here
template<node::StringPropertyType::GetterType F>
               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/realm/src/node/node_init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tenna/Desktop/aitem/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/tenna/.nvm/versions/node/v17.0.1/bin/node" "/Users/tenna/Desktop/aitem/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/tenna/Desktop/aitem/node_modules/realm/compiled/node-v102_darwin_arm64/realm.node" "--module_name=realm" "--module_path=/Users/tenna/Desktop/aitem/node_modules/realm/compiled/node-v102_darwin_arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
gyp ERR! cwd /Users/tenna/Desktop/aitem/node_modules/realm
gyp ERR! node -v v17.0.1
gyp ERR! node-gyp -v v9.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/tenna/.nvm/versions/node/v17.0.1/bin/node /Users/tenna/Desktop/aitem/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tenna/Desktop/aitem/node_modules/realm/compiled/node-v102_darwin_arm64/realm.node --module_name=realm --module_path=/Users/tenna/Desktop/aitem/node_modules/realm/compiled/node-v102_darwin_arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tenna/Desktop/aitem/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/Users/tenna/.nvm/versions/node/v17.0.1/bin/node" "/Users/tenna/Desktop/aitem/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/tenna/Desktop/aitem/node_modules/realm
node-pre-gyp ERR! node -v v17.0.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/tenna/.nvm/versions/node/v17.0.1/bin/node /Users/tenna/Desktop/aitem/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tenna/Desktop/aitem/node_modules/realm/compiled/node-v102_darwin_arm64/realm.node --module_name=realm --module_path=/Users/tenna/Desktop/aitem/node_modules/realm/compiled/node-v102_darwin_arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
```

### To reproduce

I can give an access to my project if that'll works.

### Environment

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 17.0.1 - /private/var/folders/cv/yb103sl92sn87wng_mvscb_80000gn/T/xfs-bfc35190/node
    Yarn: 3.2.3 - /private/var/folders/cv/yb103sl92sn87wng_mvscb_80000gn/T/xfs-bfc35190/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  npmPackages:
    jest: 24.1.0 => 24.1.0
```

**Comment by jj811208** [comment]
I don't think it's a yarn bug, it looks like you're using a package that failed to build when you installed it, 

so try upgrading that package or lowering your node.js version.

https://github.com/realm/realm-js/issues/2682

**Comment by RDIL** [comment]
Not a Yarn bug, rather an actual error with this package's build step.
