### ISSUE TITLE
[Bug?]: After corepack is used, yarn cannot be used

### ISSUE THREAD

**Issue by Niefee** [yarnpkg/berry#4953]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I Cannot use yarn。

### To reproduce

```bash
node -v
> v16.17.1

nvm version
>1.1.9

corepack enable

yarn set version stable

 yarn -v
> 3.2.4

 yarn info vue
>
Internal Error: root-workspace-0b6124@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at gQ.getCandidates (D:\Users\xxxx\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:435:5146)
    at Wf.getCandidates (D:\Users\xxxx\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:391:1264)
    at D:\Users\xxxx\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:439:7695
    at Rf (D:\Users\xxxx\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:390:8965)
    at ue (D:\Users\xxxx\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:439:7675)
```

### Environment

```shell
Error: Cannot find module './envinfo'
```

**Comment by merceyz** [comment]
To quote the error message:
> run "yarn install" to update the lockfile
