### ISSUE TITLE
[Bug?]: Experimental `node:test` can't be resolved in PnP

### ISSUE THREAD

**Issue by kmannislands** [yarnpkg/berry#4984]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Yarn PnP fails to resolve import from `node:test` (experimental, node 18-19). Running with plain `node` works just fine, resolution error only crops up when running via a `yarn` script.

This is an experimental built-in module at this stage but still seems like ideally PnP resolution wouldn't get in the way.

```
/Users/test/repo/.pnp.cjs:9757
  return Object.defineProperties(new Error(message), {
                                 ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: /Users/test/repo/test
Not found: /Users/test/repo/test

    at makeError (/Users/test/repo/.pnp.cjs:9757:34)
    at resolveUnqualified (/Users/test/repo/.pnp.cjs:11272:13)
    at resolveRequest (/Users/test/repo/.pnp.cjs:11314:14)
    at Object.resolveRequest (/Users/test/repo/.pnp.cjs:11370:26)
    at resolve$1 (file:///Users/test/repo/.pnp.loader.mjs:1989:25)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:829:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:412:18)
    at ESMLoader.import (node:internal/modules/esm/loader:513:22)
    at node:internal/modules/run_main:59:28
```

### To reproduce

```js repro
import { test } from 'node:test';
import assert from 'node:assert';

test('it works', () => {
    assert.strictEqual(1, 1);
});
```

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 19.0.0 - /private/var/folders/ll/pmd45pwn5894nj5v33zlprl80000gn/T/xfs-d558f930/node
    Yarn: Unqualified resolve /Users/test/repo.yarn/releases/yarn-3.2.4.cjs undefined
Unqualified resolve /Users/test/repo.yarn/releases/yarn-3.2.4.cjs undefined
3.2.4 - /private/var/folders/ll/pmd45pwn5894nj5v33zlprl80000gn/T/xfs-d558f930/yarn
    npm: Unqualified resolve /Users/test/.nvm/versions/node/v19.0.0/bin/npm undefined
8.19.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
```

### Additional context

I am using esmodules. Code being run is compiled js from typescript. The pnp-patched ts seems to resolve the import correctly.  As I'm compiling to an ESM target, the `import` syntax is preserved.

**Comment by kmannislands** [comment]
Please disregard, turns out my issue was far more silly.

I made a typo in my `scripts` section and was running `node test dist/` instead of `node --test dist/` kicking off the resolution I was observing here.
