### ISSUE TITLE
[Bug?]: `yarn build` error in Chinese path: Qualified path resolution failed

### ISSUE THREAD

**Issue by Mfweb** [yarnpkg/berry#5074]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Error when using yarn build when the file path has Chinese in it.
```
F:\Projects\测试\test\.pnp.cjs:25929
  return Object.defineProperties(new Error(message), {
                                 ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: F:\Projects\娴嬭瘯\test\.yarn\__virtual__\react-scripts-virtual-3eceb0491e\0\cache\react-scripts-npm-5.0.1-d06bd2d5ad-92afa2f245.zip\node_modules\react-scripts\bin\react-scripts.js
Not found: F:\Projects\娴嬭瘯\test\.yarn\__virtual__\react-scripts-virtual-3eceb0491e\0\cache\react-scripts-npm-5.0.1-d06bd2d5ad-92afa2f245.zip\node_modules\react-scripts\bin\react-scripts.js

    at makeError (F:\Projects\测试\test\.pnp.cjs:25929:34)
    at resolveUnqualified (F:\Projects\测试\test\.pnp.cjs:27444:13)
    at resolveRequest (F:\Projects\测试\test\.pnp.cjs:27485:14)
    at Object.resolveRequest (F:\Projects\测试\test\.pnp.cjs:27541:26)
    at resolve$1 (file:///F:/Projects/%E6%B5%8B%E8%AF%95/test/.pnp.loader.mjs:1989:25)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at node:internal/modules/run_main:58:28

Node.js v18.12.1
```

The Chinese part of the `Source path` is garbled.

### To reproduce

`mkdir 测试`
`cd 测试`
`yarn dlx create-react-app test`
`cd test`
`yarn build`

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\Temp\xfs-dc58b6bc\node.CMD
    Yarn: 3.3.0 - ~\AppData\Local\Temp\xfs-dc58b6bc\yarn.CMD
    npm: 8.19.2 - ~\AppData\Local\nvs\default\npm.CMD
```

**Comment by Mfweb** [comment]
> ![image](https://user-images.githubusercontent.com/25342059/202674026-a8b1a3b6-9253-400b-bcd3-feecbbf8ec5f.png)
> 
> I am also a chinese speaker, but this is not reproducible on my Mac, maybe only on windows🤔

Yes, I didn't reproduce the problem on my MAC either

**Comment by jtyoui** [comment]
> 

俺也一样，有解决方案吗？
