### ISSUE TITLE
[Bug?]: Yarn fails to install on corrupt cache zip file rather than re-fetching

### ISSUE THREAD

**Issue by me4502** [yarnpkg/berry#5096]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In the case that a cached zip file in `.yarn/cache` becomes corrupt (such as an issue in caching infrastructure downloads), yarn will crash. Rather than crashing and failing the install, yarn should consider this package not cached and download a fresh copy.

```
YN0001: │ Libzip Error: Failed to open the cache entry for @bazel/ibazel@npm:0.16.2: Not a zip archive
    at Xr.makeLibzipError (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:377:12827)
    at new Xr (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:377:12268)
    at L (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:429:2832)
    at /mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:429:2896
    at NP (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:390:9038)
    at Jg.factory (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:429:2887)
    at get baseFs [as baseFs] (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:377:41108)
    at Jg.readFilePromise (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:377:38530)
    at Qo.readFilePromise (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:377:38537)
    at $A.loadFile (/mnt/vss/_work/1/s/.yarn/releases/yarn-3.3.0.cjs:390:30519)
```

### To reproduce

To reproduce, replace any file in `.yarn/cache` with something that's not a valid zip file.

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.12.1 - /private/var/folders/92/h3d4hb8n54g0kmbbvqhl4fp40000gn/T/xfs-e0fcd0af/node
    Yarn: 3.3.0 - /private/var/folders/92/h3d4hb8n54g0kmbbvqhl4fp40000gn/T/xfs-e0fcd0af/yarn
    npm: 8.19.1 - /opt/homebrew/bin/npm
```

**Comment by BaidenGenie** [comment]
C:\E-commerce app with REST API>yarn create strapi-app my-project
yarn create v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-strapi-app@4.25.8" with binaries:
      - create-strapi-app
node:internal/modules/package_json_reader:93
        throw error;
        ^

SyntaxError: Error parsing C:\Users\BAIDEN\AppData\Local\Yarn\Data\global\node_modules\date-fns\isWithinInterval\package.json: Unterminated string in JSON at position 49
    at parse (<anonymous>)
    at read (node:internal/modules/package_json_reader:80:16)
    at readPackage (node:internal/modules/package_json_reader:141:10)
    at Object.readPackageScope (node:internal/modules/package_json_reader:164:19)
    at Module._extensions..js (node:internal/modules/cjs/loader:1507:35)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\BAIDEN\AppData\Local\Yarn\Data\global\node_modules\date-fns\index.js:1827:40) {
  path: 'C:\\Users\\BAIDEN\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\date-fns\\isWithinInterval\\package.json'
}

Node.js v20.17.0
error Command failed.
Exit code: 1
Command: C:\Users\BAIDEN\AppData\Local\Yarn\bin\create-strapi-app
Arguments: my-project
Directory: C:\E-commerce app with REST API
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

C:\E-commerce app with REST API># 'yarn create' creates a new project
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\E-commerce app with REST API># 'strapi-app' is the Strapi package
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\E-commerce app with REST API># 'my-project' is the name of your Strapi project
'#' is not recognized as an internal or external command,
operable program or batch file.

this is the error that i have , can you help fix it cause i don't understand

**Comment by clemyan** [comment]
@BaidenGenie Not related. For one, you are using yarn v1. And, the error message looks nothing like the one in the OP.

If you are still encountering problems please open an issue in the appropriate repo with a reproduction
