### ISSUE TITLE
(🐞) Nonsense error when running `yarn init -2`

### ISSUE THREAD

**Issue by KotlinIsland** [yarnpkg/berry#5126]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

When I am trying to create a new project, and I run `yarn init -2`, yarn says I am:
- In a project subdirectory (I'm not, I'm in `~/projects/asdfsadfg`)
- Using the `--install` flag (I'm not, I'm using the `-2` flag)

### To reproduce

```
👉 yarn init -2
Usage Error: Cannot use the --install flag from within a project subdirectory

$ yarn init [-p,--private] [-w,--workspace] [-i,--install] [-n,--name #0]
```

### Environment

```shell
👉  yarn dlx -q envinfo --preset jest
➤ YN0027: envinfo@unknown can't be resolved to a satisfying range
➤ YN0001: RequestError: tunneling socket could not be established, statusCode=407
    at ClientRequest.<anonymous> (C:\Users\BartholomewM\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:258:14340)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at o.emit (C:\Users\BartholomewM\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:253:90235)
    at ClientRequest.c (C:\Users\BartholomewM\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:258:33205)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnData (node:_http_client:570:11)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at ClientRequest.c (C:\Users\BartholomewM\AppData\Local\node\corepack\yarn\3.2.4\yarn.js:258:33094)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnData (node:_http_client:570:11)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

➤ Errors happened when preparing the environment required to run this command.
```
```


### Additional context

btw, I'm using yarn 4.0.0-rc.32

**Comment by arcanis** [comment]
> In a project subdirectory (I'm not, I'm in `~/projects/asdfsadfg`)

You probably have a bogus `yarn.lock` in `~` or `~/projects`.

**Comment by KotlinIsland** [comment]
@arcanis True, I'll update the issue to focus on these details

**Comment by sethwklein** [comment]
This message is also produced if there's a bogus `package.json` in a parent directory.

**Comment by strogonoff** [comment]
Getting this when trying to initialize a workspace in a monorepo.

- There is a `yarn.lock` and `package.json` in monorepo root
- There’s no `package.json` in immediate ancestor
- Regardless of the above, the error message is bogus—the flag mentioned (`--install`) was never passed to `init`
