### ISSUE TITLE
[Bug?]: Dependencies defined in `imports` causes Yarn PnP to crash 

### ISSUE THREAD

**Issue by wojtekmaj** [yarnpkg/berry#5187]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When running `chalk@^5.2.0` in Yarn PnP environment (in my case, indirectly, by running `yarn dlx serve` instead of `npx serve`, the following error is thrown:

```
/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-f5b08830/dlx-706/.pnp.cjs:9364
  return Object.defineProperties(new Error(message), {
                                 ^

Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.1 (via /Users/wmaj/.yarn/berry/cache/chalk-npm-5.0.1-6afcb94227-8.zip/node_modules/chalk/source/index.js)

    at makeError (/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-f5b08830/dlx-706/.pnp.cjs:9364:34)
    at resolveToUnqualified (/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-f5b08830/dlx-706/.pnp.cjs:10283:21)
    at Object.resolveToUnqualified (/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-f5b08830/dlx-706/.pnp.cjs:10427:26)
    at resolve$1 (file:///private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-f5b08830/dlx-706/.pnp.loader.mjs:224:31)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1
```

This is directly related to https://github.com/chalk/chalk/commit/04fdbd6d8d262ed8668cf3f2e94f647d2bc028d8 in which dependencies were bundled and `imports` feature was leveraged.

### To reproduce

```js repro
await expect(yarn(`dlx`, `serve`)).rejects.not.toThrow();
```

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - /private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-a3797145/node
    Yarn: 3.3.0 - /private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-a3797145/yarn
    npm: 8.19.2 - /usr/local/bin/npm
```

**Comment by arcanis** [comment]
Should be solved by https://github.com/yarnpkg/berry/pull/4862, please try the RCs

**Comment by wojtekmaj** [comment]
@arcanis Nope :(

```
wmaj@MacBook-Pro home-page % yarn -v                                
4.0.0-rc.35
wmaj@MacBook-Pro home-page % yarn dlx serve                         
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 2s 689ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 2s 820ms

/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-83d97c82/dlx-2819/.pnp.cjs:9364
  return Object.defineProperties(new Error(message), {
                                 ^

Error: chalk tried to access #ansi-styles, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: #ansi-styles (via "#ansi-styles/package.json")
Required by: chalk@npm:5.0.1 (via /Users/wmaj/.yarn/berry/cache/chalk-npm-5.0.1-6afcb94227-8.zip/node_modules/chalk/source/index.js)

    at makeError (/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-83d97c82/dlx-2819/.pnp.cjs:9364:34)
    at resolveToUnqualified (/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-83d97c82/dlx-2819/.pnp.cjs:10283:21)
    at Object.resolveToUnqualified (/private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-83d97c82/dlx-2819/.pnp.cjs:10427:26)
    at resolve$1 (file:///private/var/folders/wg/cztxqmdj6h94ht8783cym75c0000gp/T/xfs-83d97c82/dlx-2819/.pnp.loader.mjs:224:31)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.1
```

**Comment by merceyz** [comment]
You're running into https://github.com/nodejs/corepack/issues/202, you'll need to update Corepack.

> Should be solved by #4862, please try the RCs

It was backported to v3.

**Comment by wojtekmaj** [comment]
You are correct! I was hitting the issue with Corepack 0.14.2 + Yarn 3/4.rc-35, but NOT with Corepack 0.15.3 + Yarn 3/4.rc-35
