### ISSUE TITLE
[Bug?]: 

### ISSUE THREAD

**Issue by cowwoc** [yarnpkg/berry#5202]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I run `yarn-3.3.1.cjs run --binaries-only gulp --color --gulpfile gulpfile.babel.js default` the first time I get:

```
"C:\Program Files\nodejs\node.exe" C:\Users\Gili\Documents\requirements.js\.yarn\releases\yarn-3.3.1.cjs run --binaries-only gulp --color --gulpfile C:\Users\Gili\Documents\requirements.js\gulpfile.babel.js default --mode=DEBUG
[14:19:22] Requiring external module @babel/register
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\Gili\Documents\requirements.js\.yarn\cache\typescript-patch-7bc527fc0a-1caaea6cb7.zip\node_modules\typescript\lib\typescript.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\Gili\Documents\requirements.js\.yarn\cache\rollup-npm-3.10.0-a133550ae4-31a882689c.zip\node_modules\rollup\dist\shared\rollup.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\Gili\Documents\requirements.js\.yarn\cache\terser-npm-5.16.1-d407c2c364-cb52412350.zip\node_modules\terser\dist\bundle.min.js as it exceeds the max of 500KB.
[14:19:32] DEBUG mode detected
[14:19:33] Using gulpfile ~\Documents\requirements.js\gulpfile.babel.js
[14:19:33] Starting 'default'...
Hello world
[14:19:33] Finished 'default' after 2.17 ms
```

When I run it a second time I get:

```
"C:\Program Files\nodejs\node.exe" C:\Users\Gili\Documents\requirements.js\.yarn\releases\yarn-3.3.1.cjs run --binaries-only gulp --color --gulpfile C:\Users\Gili\Documents\requirements.js\gulpfile.babel.js default --mode=DEBUG
[14:20:10] Requiring external module @babel/register
C:\Users\Gili\Documents\requirements.js\.yarn\cache\@babel-core-npm-7.20.12-1f7c5fb4ea-62e6c3e214.zip\node_modules\@babel\core\lib\transformation\index.js:47
    throw e;
    ^

TypeError: C:\Users\Gili\Documents\requirements.js\.yarn\cache\convert-source-map-npm-1.9.0-e294555f4b-dc55a1f28d.zip\node_modules\convert-source-map\index.js: _convertSourceMap(...).fromObject is not a function
    at generateCode (C:\Users\Gili\Documents\requirements.js\.yarn\cache\@babel-core-npm-7.20.12-1f7c5fb4ea-62e6c3e214.zip\node_modules\@babel\core\src\transformation\file\generate.ts:70:43)
    at run (C:\Users\Gili\Documents\requirements.js\.yarn\cache\@babel-core-npm-7.20.12-1f7c5fb4ea-62e6c3e214.zip\node_modules\@babel\core\src\transformation\index.ts:59:48)
    at run.next (<anonymous>)
    at transform (C:\Users\Gili\Documents\requirements.js\.yarn\cache\@babel-core-npm-7.20.12-1f7c5fb4ea-62e6c3e214.zip\node_modules\@babel\core\src\transform.ts:29:20)
    at transform.next (<anonymous>)
    at evaluateSync (C:\Users\Gili\Documents\requirements.js\.yarn\cache\gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip\node_modules\gensync\index.js:251:28)
    at fn (C:\Users\Gili\Documents\requirements.js\.yarn\cache\gensync-npm-1.0.0-beta.2-224666d72f-a7437e58c6.zip\node_modules\gensync\index.js:89:14)
    at stopHiding - secret - don't use this - v1 (C:\Users\Gili\Documents\requirements.js\.yarn\cache\@babel-core-npm-7.20.12-1f7c5fb4ea-62e6c3e214.zip\node_modules\@babel\core\src\errors\rewrite-stack-trace.ts:97:14)
    at Object.transformSync (C:\Users\Gili\Documents\requirements.js\.yarn\cache\@babel-core-npm-7.20.12-1f7c5fb4ea-62e6c3e214.zip\node_modules\@babel\core\src\transform.ts:66:52)
    at exports.transformSync (C:\Users\Gili\Documents\requirements.js\.yarn\__virtual__\@babel-register-virtual-5b77fbcf59\0\cache\@babel-register-npm-7.18.9-bcdce8aed1-4aeaff97e0.zip\node_modules\@babel\register\lib\worker\transform.js:94:15)      
    at Function.handleMessage (C:\Users\Gili\Documents\requirements.js\.yarn\__virtual__\@babel-register-virtual-5b77fbcf59\0\cache\@babel-register-npm-7.18.9-bcdce8aed1-4aeaff97e0.zip\node_modules\@babel\register\lib\worker\handle-message.js:23:16)
    at LocalClient.<anonymous> (C:\Users\Gili\Documents\requirements.js\.yarn\__virtual__\@babel-register-virtual-5b77fbcf59\0\cache\@babel-register-npm-7.18.9-bcdce8aed1-4aeaff97e0.zip\node_modules\@babel\register\lib\worker-client.js:134:86)      
    at LocalClient.transform (C:\Users\Gili\Documents\requirements.js\.yarn\__virtual__\@babel-register-virtual-5b77fbcf59\0\cache\@babel-register-npm-7.18.9-bcdce8aed1-4aeaff97e0.zip\node_modules\@babel\register\lib\worker-client.js:64:47)
    at compile (C:\Users\Gili\Documents\requirements.js\.yarn\__virtual__\@babel-register-virtual-5b77fbcf59\0\cache\@babel-register-npm-7.18.9-bcdce8aed1-4aeaff97e0.zip\node_modules\@babel\register\lib\hook.js:58:25)
    at compileBabel7 (C:\Users\Gili\Documents\requirements.js\.yarn\__virtual__\@babel-register-virtual-5b77fbcf59\0\cache\@babel-register-npm-7.18.9-bcdce8aed1-4aeaff97e0.zip\node_modules\@babel\register\lib\hook.js:49:14)
    at Module._compile (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at require$$0.Module._extensions..js (C:\Users\Gili\Documents\requirements.js\.pnp.cjs:19027:33)
    at Object.newLoader [as .js] (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Function.require$$0.Module._load (C:\Users\Gili\Documents\requirements.js\.pnp.cjs:18864:14)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:\Users\Gili\Documents\requirements.js\.yarn\cache\vinyl-sourcemap-npm-1.1.0-e961858bf5-e7174851fa.zip\node_modules\vinyl-sourcemap\lib\/helpers.js:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._compile (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at require$$0.Module._extensions..js (C:\Users\Gili\Documents\requirements.js\.pnp.cjs:19027:33)
    at Object.newLoader [as .js] (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Function.require$$0.Module._load (C:\Users\Gili\Documents\requirements.js\.pnp.cjs:18864:14)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:\Users\Gili\Documents\requirements.js\.yarn\cache\vinyl-sourcemap-npm-1.1.0-e961858bf5-e7174851fa.zip\node_modules\vinyl-sourcemap\/index.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._compile (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at require$$0.Module._extensions..js (C:\Users\Gili\Documents\requirements.js\.pnp.cjs:19027:33)
    at Object.newLoader [as .js] (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Function.require$$0.Module._load (C:\Users\Gili\Documents\requirements.js\.pnp.cjs:18864:14)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:\Users\Gili\Documents\requirements.js\.yarn\cache\vinyl-fs-npm-3.0.3-7379431c37-9483663259.zip\node_modules\vinyl-fs\lib\src\/sourcemap.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._compile (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at require$$0.Module._extensions..js (C:\Users\Gili\Documents\requirements.js\.pnp.cjs:19027:33)
    at Object.newLoader [as .js] (C:\Users\Gili\Documents\requirements.js\.yarn\cache\pirates-npm-4.0.5-22f8e827ce-c9994e61b8.zip\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1096:32) {
  code: 'BABEL_GENERATE_ERROR'
}

Node.js v19.4.0
```

This error occurs forever unless I delete `node_modules` in which case I get the first output again.

Expected behavior: I should always get the first output without needing to delete the `node_modules` directory.

### To reproduce

package.json
```js
{
  "main": "node/cjs/index.js",
  "browser": "browser/cjs/index.js",
  "module": "node/mjs/index.mjs",
  "types": "node/ts/index.d.ts",
  "dependencies": {
    "@babel/register": "^7.18.9",
    "@rollup/plugin-babel": "^6.0.3",
    "@rollup/plugin-commonjs": "^24.0.0",
    "@rollup/plugin-node-resolve": "^15.0.1",
    "@rollup/plugin-typescript": "^11.0.0",
    "core-js": "^3.27.1",
    "fancy-log": "^2.0.0",
    "minimist": "^1.2.7",
    "rollup": "^3.10.0"
  },
  "nyc": {
    "include": [
      "target/test/**/*.js"
    ]
  },
  "packageManager": "yarn@3.3.1",
  "devDependencies": {
    "@babel/core": "^7.20.12",
    "@babel/preset-env": "^7.20.2",
    "@babel/preset-typescript": "^7.18.6",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-connect": "^5.7.0",
    "gulp-eslint-new": "^1.7.1",
    "gulp-jsdoc3": "^3.0.0",
    "gulp-mocha": "^8.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-sourcemaps": "^3.0.0",
    "gulp-terser": "^2.1.0",
    "gulp-typescript": "^6.0.0-alpha.1",
    "rollup-plugin-node-globals": "^1.4.0",
    "typescript": "^4.9.4",
    "yarn": "^1.22.19"
  }
}
```

.babelrc.js
```js
const presets =
  [
    "@babel/preset-typescript",
    [
      "@babel/preset-env",
      {
        useBuiltIns: "usage",
        corejs:
          {
            version: "3.27.1",
            proposals: true
          }
      }
    ]
  ];

const ignore =
  [
    "**/node_modules/**"
  ];

module.exports =
  {
    presets,
    ignore
  };
```
gulpfile.babel.js
```js
gulp.task("default", done =>
{
  console.info("Hello world");
  done();
});
```

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 19.4.0 - ~\AppData\Local\Temp\xfs-04ea59f7\node.CMD    
    Yarn: 3.3.1 - ~\AppData\Local\Temp\xfs-04ea59f7\yarn.CMD     
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by arcanis** [comment]
That doesn't sound related to Yarn.

**Comment by cowwoc** [comment]
You're probably right. I've moved this issue to https://github.com/babel/babel/issues/15352.
