### ISSUE TITLE
[Bug?]: ESBuild integration does not resolve dependency

### ISSUE THREAD

**Issue by dalisoft** [yarnpkg/berry#5242]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

ESBuild build does not work at build level due of not flat tree node_modules resolving

<details>

<summary>Logs</summary>

```
pnpm-esbuild/frontend on  master [✘+] via ⬢ v19.5.0 
❯ yarn yarn-build
✘ [ERROR] Could not resolve "uuid"

    src/App.js:2:29:
      2 │ import { v4 as uuidv4 } from "uuid";
        ╵                              ~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "uuid" here because it's not listed as a
  dependency of this package:

    .pnp.cjs:281:33:
      281 │           "packageDependencies": [\
          ╵                                  ~~

  You can mark the path "uuid" as external to exclude it from the bundle, which will remove this
  error.

/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
src/App.js:2:29: ERROR: Could not resolve "uuid"
    at failureErrorWithLog (/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:1048:25
    at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:993:52
    at buildResponseToResult (/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/dalisoft/Desktop/bug/pnpm-esbuild/frontend/.yarn/unplugged/esbuild-npm-0.17.5-ba581df653/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 29,
        file: 'src/App.js',
        length: 6,
        line: 2,
        lineText: 'import { v4 as uuidv4 } from "uuid";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 33,
            file: '.pnp.cjs',
            length: 421,
            line: 281,
            lineText: '          "packageDependencies": [\\',
            namespace: '',
            suggestion: ''
          },
          text: `The Yarn Plug'n'Play manifest forbids importing "uuid" here because it's not listed as a dependency of this package:`
        },
        {
          location: null,
          text: 'You can mark the path "uuid" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "uuid"'
    }
  ],
  warnings: []
}

Node.js v19.5.0
```

</details>

### To reproduce

- clone repo via `git clone git@github.com:dalisoft/pnpm-esbuild.git`
- go-to folder via `cd pnpm-esbuild`
- run `yarn set version stable`
- run `yarn install` on each subfolder
- run `yarn yarn-build` at `frontend` folder
- you will see error

### Environment

```shell
System:
    OS: macOS 12.6.3
    CPU: (8) arm64 Apple M1
Binaries:
    Node: 19.5.0 - /private/var/folders/kj/92wfmyss40g5lzxfmy9czwwh0000gn/T/xfs-86accc9d/node
    Yarn: 3.4.1 - /private/var/folders/kj/92wfmyss40g5lzxfmy9czwwh0000gn/T/xfs-86accc9d/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
```

### Additional context

PNPM has same issue: https://github.com/pnpm/pnpm/issues/6009

**Comment by arcanis** [comment]
https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies

**Comment by dalisoft** [comment]
Thank you for useful link @arcanis 

So, it is means **npm** choose wrong way of doing installation?

**Comment by dalisoft** [comment]
When i changed `nodeLinker: node-modules`, it worked and successfully. See [my test result](https://github.com/dalisoft/pnpm-esbuild#test-case)

**Comment by arcanis** [comment]
Yes and no. The problem is in your project, not npm directly. It's just that npm isn't advanced enough to detect it.
