### ISSUE TITLE
[Bug?]: 

### ISSUE THREAD

**Issue by blumfontein** [yarnpkg/berry#5243]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Hi! Yarn 3 can't resolve git+https dependencies from custom gitlab instance. This worked in Yarn 1.

Th error:
```
Error: @my/dep@https://pull-token:some-token@my-gitlab.com/my/repo#semver:>=1 isn't supported by any available resolver
    at yf.getResolverByDescriptor (/projects/perfumer/platform/yarn-3.4.1.cjs:391:1647)
    at yf.bindDescriptor (/projects/perfumer/platform/yarn-3.4.1.cjs:391:1036)
    at Z (/projects/perfumer/platform/yarn-3.4.1.cjs:439:6900)
```
My package.json looks like this:

```
"dependencies": {
    "@my/dep": "git+https://pull-token:some-token@my-gitlab.com/my/repo#semver:>=1",
  },
```

### To reproduce

I can send a link to repo in the private message

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
  Binaries:
    Node: 16.16.0 - /tmp/xfs-6e8ff5b1/node
    Yarn: 3.4.1 - /tmp/xfs-6e8ff5b1/yarn
    npm: 8.11.0 - /usr/bin/npm
```

**Comment by r4m-ilyasm** [comment]
I figured out, that this works with packages with simple names like "my-dep", but doesn't work with nacmes with "@" like "@my/dep"

**Comment by 4rcadiaN** [comment]
Is there any update on this? This is blocking our team for quite some time from using yarn. Still not working in 4.2.1

**Comment by wuhkuh** [comment]
I ran into the same issue for patches. I managed to work around this as follows:
```
patch:@<SCOPE>/<PACKAGE>@npm%3A<VERSION>#~/.yarn/patches/@<SCOPE>-<PACKAGE>-npm-<VERSION>-<DIGEST>.patch
```
Effectively eliding the `__archiveUrl` segment. There might be a better manual workaround, but wanted to get this out there for now.

**Comment by Quineone** [comment]
Any new about this, have the same issue?
