### ISSUE TITLE
[Bug?]: How can I solve this issue? open@npm

### ISSUE THREAD

**Issue by kbyunghoon** [yarnpkg/berry#5260]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I type 'yarn start', This kind of problem comes up. What should I do?

```
C:\Users\user\Desktop\frontend_study\.pnp.cjs:30824
      Error.captureStackTrace(firstError);
            ^

Error: Required unplugged package missing from disk. This may happen when switching branches without running installs (unplugged packages must be fully materialized on disk to work).

Missing package: open@npm:8.4.0
Expected package location: C:\Users\user\Desktop\frontend_study\.yarn\unplugged\open-npm-8.4.0-df63cfe537\node_modules\open\

Require stack:
- C:\Users\user\Desktop\frontend_study\.yarn\__virtual__\react-dev-utils-virtual-fe01a48f21\0\cache\react-dev-utils-npm-12.0.1-83ba06e3ee-2c6917e47f.zip\node_modules\react-dev-utils\openBrowser.js    
- C:\Users\user\Desktop\frontend_study\.yarn\__virtual__\react-scripts-virtual-11bcdbbae0\0\cache\react-scripts-npm-5.0.1-d06bd2d5ad-92afa2f245.zip\node_modules\react-scripts\scripts\start.js
    at Function.require$$0.Module._resolveFilename (C:\Users\user\Desktop\frontend_study\.pnp.cjs:30824:13)
    at Function.require$$0.Module._load (C:\Users\user\Desktop\frontend_study\.pnp.cjs:30674:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\user\Desktop\frontend_study\.yarn\__virtual__\react-dev-utils-virtual-fe01a48f21\0\cache\react-dev-utils-npm-12.0.1-83ba06e3ee-2c6917e47f.zip\node_modules\react-dev-utils\openBrowser.js:13:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require$$0.Module._extensions..js (C:\Users\user\Desktop\frontend_study\.pnp.cjs:30868:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (C:\Users\user\Desktop\frontend_study\.pnp.cjs:30705:14)

### To reproduce

gitignore
# Zero-installs
.yarn/*
!.yarn/cache
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

### Environment

shell
PC:Windows 10, Mac OS
Yarn : 3.3.0
npm : 8.1.0
```

**Comment by arcanis** [comment]
Please respect the template. Using only the information you mention, I can't help you with anything else than "did you read the error message?"
