### ISSUE TITLE
[Bug?]:  Yarn 4.0.0-rc.39 Dollar Sign ($) in script causes syntax error

### ISSUE THREAD

**Issue by cjshearer** [yarnpkg/berry#5295]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Using a dollar sign in a script causes a syntax error.

### To reproduce

In a new directory, create:
```js
// package.json
{
  "version": "0.0.1",
  "scripts": {
    "test": "$"
  },
  "packageManager": "yarn@4.0.0-rc.39"
}
```
And run
```sh
# create empty lock file
touch yarn.lock 
yarn set version 4.0.0-rc.39
yarn
yarn test
```

Which should output 
```sh
$: command not found
```
but instead throws 
```sh
Syntax Error: Expected [$@*?#a-zA-Z0-9_\-] or any character but end of input found (line 1, column 2).
    at ag (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:12:3214)
    at Q8e (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:12:22154)
    at CD (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:12:22327)
    at PE (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:162:1973)
    at b (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:183:2734)
    at /home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:183:2918
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Pn.mktempPromise (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:9:44525)
    at async Object.TP (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:183:2547)
    at async Z0.execute (/home/.../.yarn/releases/yarn-4.0.0-rc.39.cjs:491:2167)
 ```

### Environment

```shell
System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 9 4900HS with Radeon Graphics
  Binaries:
    Node: 19.7.0 - /tmp/xfs-549e8f09/node
    Yarn: 4.0.0-rc.39 - /tmp/xfs-549e8f09/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  npmPackages:
    jest: 29.4.3 => 29.4.3
```

**Comment by jdalrymple** [comment]
Similar problem with the inclusion of <. Maybe worth mentioning these characters are not supported in scripts.
