### ISSUE TITLE
[Bug?]: Yarn is unable to run shell scripts in Node version >= 18.12.1 

### ISSUE THREAD

**Issue by hikarunoryoma** [yarnpkg/berry#5364]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have a package.json file that defines: 

```
"scripts": {
    "compile": "./compile.sh"
}
```

when running `yarn compile` I get the following error: 
```
Internal Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at oU (.../yarn-3.5.0.cjs:4:7031)
    at qf.implementation (.../.yarn/releases/yarn-3.5.0.cjs:392:17799)
    at qf.exec (.../.yarn/releases/yarn-3.5.0.cjs:395:1585)
    at qf.run (.../.yarn/releases/yarn-3.5.0.cjs:395:1756)
    at pV (.../.yarn/releases/yarn-3.5.0.cjs:401:6331)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ake (.../.yarn/releases/yarn-3.5.0.cjs:403:16)
    at async o (.../.yarn/releases/yarn-3.5.0.cjs:403:146)
```
Using `n` I have tried changing my version of node and have found that any version >= 18.12.1 will fail.  This might be an issue with Node, but checking here first in case this has something to do with yarn not handling something properly with Node 18.  

### To reproduce

```
"scripts": {
    "compile": "./compile.sh"
}
```

have a `compile.sh` file

run `yarn compile` with Node version 18.15.0

### Environment

```shell
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - /private/var/folders/ls/.../node
    Yarn: 3.5.0 - /private/var/folders/ls/.../yarn
    npm: 9.3.1 - ~/.n/bin/npm
```

**Comment by hikarunoryoma** [comment]
This is fixed if the top of the `.sh` file has `#!/bin/bash`

**Comment by danielrsantana** [comment]
I'm having the same issue

**server.menage.sh**

```
#!/bin/bash

echo Hello World
```

package.json:
```
{
    (...),
    "scripts": {
      "inspect": "./server.manage.sh",
    },
    (...),
}
```

command: `sh server.menage.sh` works properly, but when I run it through yarn (`yarn inspect`) I have the error:

command not found: ./server.manage.sh

The same goes for `"inspect": "sh server.menage.sh --inspect",` or `"inspect": "sh ./server.menage.sh --inspect",`

<img width="503" alt="image" src="https://github.com/yarnpkg/berry/assets/11296189/b7c36cef-a290-44fa-bde0-69c568c9a456">
