### ISSUE TITLE
[Bug]: `yarn import` fails with npm workspaces monorepo

### ISSUE THREAD

**Issue by drew-vanta** [yarnpkg/berry#5566]
### Describe the bug

`yarn import` fails when trying to migrate an npm workspaces monorepo. It seems to get hung up on the root-level package.json.

### To reproduce

Unfortunately, when trying to use Sherlock, I encountered an Internal Server Error when clicking [this link](https://yarnpkg.com/playground) available on [this page](https://yarnpkg.com/advanced/sherlock). Nonetheless, here are the available files to reproduce the issue:
test-npm-workspaces/package.json:
```
{
  "name": "package-a",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "standard": "17.1.0"
  }
}
```

packages/package-a/package.json:
```
{
  "name": "package-a",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "standard": "17.1.0"
  }
}
```

Followed by `npm install` (`package-lock.json` omitted here).

Then, I encounter the following output when trying to run `yarn import`:
```
$ yarn import
Internal Error: test-npm-workspaces@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:435:5145)
    at kf.getCandidates (/workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:391:1264)
    at /workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:439:8033
    at df (/workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:390:11070)
    at ge (/workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:390:10398)
    at async /workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:439:8545
    at async ti.startProgressPromise (/workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:390:47579)
    at async je.resolveEverything (/workspaces/test-npm-workspaces/.yarn/releases/yarn-3.6.0.cjs:439:6573)
```

### Environment

```shell
System:
 OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
 CPU: (16) x64 AMD EPYC 7763 64-Core Processor
Binaries:
 Node: 18.16.1 - /tmp/xfs-77936ddd/node
 Yarn: 3.6.0 - /tmp/xfs-77936ddd/yarn
 npm: 9.5.1 - /usr/local/share/nvm/versions/node/v18.16.1/bin/npm
 pnpm: 8.6.6 - /usr/local/share/nvm/versions/node/v18.16.1/bin/pnpm
```

**Comment by arcanis** [comment]
The `yarn import` command doesn't exist in modern releases (your command is actually running `yarn run import`).

We try to only have commands that we significantly dogfood ourselves, and the import feature was a little awkward from this perspective since we rarely/never migrate from npm, since all our repository our already Yarn-based ... so it didn't felt something we could efficiently support.

**Comment by drew-vanta** [comment]
Ah! I didn't notice that this was on the Yarn Classic docs. Thanks.
