### ISSUE TITLE
[Bug]: Yarn 4.0.0RC48 crashes on every "yarn install" 

### ISSUE THREAD

**Issue by ulrik-s** [yarnpkg/berry#5633]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

I tried to upgrade my project to use 4.0.0.rc48, this causes yarn to crash 100% percent of the time.
The stack trace looks like this:

```angular2html
➤ YN0000: · Yarn 4.0.0-rc.48.dev
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + eslint@npm:8.46.0, react-scripts@npm:4.0.3, @aashutoshrathi/word-wrap@npm:1.2.6, @ampproject/remapping@npm:2.2.1, @babel/code-frame@npm:7.10.4, and 1555 more
➤ YN0000: └ Completed in 6s 347ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0001: │ TypeError: Invalid version. Must be a string. Got type "symbol".
    at new SemVer (/home/ulrik/src/berry/.yarn/cache/semver-npm-7.5.4-c4ad957fcd-985dec0d37.zip/node_modules/semver/classes/semver.js:19:13)
    at Object.compare (/home/ulrik/src/berry/.yarn/cache/semver-npm-7.5.4-c4ad957fcd-985dec0d37.zip/node_modules/semver/functions/compare.js:3:3)
    at mergeComparators (/home/ulrik/src/berry/packages/yarnpkg-core/sources/semverUtils.ts:139:18)
    at Object.simplifyRanges (/home/ulrik/src/berry/packages/yarnpkg-core/sources/semverUtils.ts:210:33)
    at <anonymous> (/home/ulrik/src/berry/packages/yarnpkg-core/sources/Project.ts:2670:39)
    at Array.map (<anonymous>)
    at emitPeerDependencyWarnings (/home/ulrik/src/berry/packages/yarnpkg-core/sources/Project.ts:2653:98)
    at <anonymous> (/home/ulrik/src/berry/packages/yarnpkg-core/sources/Project.ts:1774:7)
    at StreamReport.startSectionPromise (/home/ulrik/src/berry/packages/yarnpkg-core/sources/StreamReport.ts:289:20)
    at StreamReport.startTimerPromise (/home/ulrik/src/berry/packages/yarnpkg-core/sources/StreamReport.ts:351:17)
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 6s 350ms
```

After a bit of digging I found a few ways of getting rid of the symptom, but none of them addressed the real issue. Fixing the issue properly is unfortunately not something I could do without a few pointers from someone.

### To reproduce

```js repro
await expect(packageJsonAndInstall({
  dependencies: {
    "eslint": "^8.35.0",
    "react-scripts": "^4"
  }
})).resolves.not.toThrowError();
```

### Environment

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
  Binaries:
    Node: 20.5.0 - /tmp/xfs-c1ed236a/node
    Yarn: 4.0.0-rc.48.dev - /tmp/xfs-c1ed236a/yarn
    npm: 9.8.0 - /usr/local/bin/npm
```

**Comment by ulrik-s** [comment]
A symptomfix:
```
diff --git a/packages/yarnpkg-core/sources/Project.ts b/packages/yarnpkg-core/sources/Project.ts
index 956d778e3..d7c72283e 100644
--- a/packages/yarnpkg-core/sources/Project.ts
+++ b/packages/yarnpkg-core/sources/Project.ts
@@ -2661,7 +2661,7 @@ function emitPeerDependencyWarnings(project: Project, report: Report) {
         throw new Error(`Assertion failed: Expected the ident to be registered`);

       return peerDependency.range;
-    });
+    }).filter(range => range !== `*`);

     const andDescendants = warning.dependents.size > 1
       ? `and other dependencies request`
```

**Comment by starsolaris** [comment]
yarn@4.0.0-rc.49 has the same error also
OS: Windows 10
Node: v18.14.0

```
yarn install
➤ YN0000: · Yarn 4.0.0-rc.49
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 358ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0001: │ TypeError: Invalid version. Must be a string. Got type "symbol".
    at new tl (C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:132:14082)
    at Object.Kqe [as compare] (C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:132:19017)
    at nM (C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:140:117372)
    at C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:140:117975
    at Array.map (<anonymous>)
    at iM (C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:140:117968)
    at C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:207:6475
    at Array.map (<anonymous>)
    at hAt (C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:207:6070)
    at C:\Users\star\AppData\Local\node\corepack\yarn\4.0.0-rc.49\yarn.js:213:2583
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 0s 369ms
```

**Comment by jnoordsij** [comment]
I seem to be running into the same issue on some of my projects. rc-47 seems to work fine, rc-48 and rc-49 trigger have this issue.

**Comment by ulrik-s** [comment]
Yes you are right. Commit 155ff9cc4 seems to be responsible for the crash.
