### ISSUE TITLE
[Bug?]: Yarn CLI doesn't work except for install

### ISSUE THREAD

**Issue by jacoboneill** [yarnpkg/berry#5708]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I can't seem to get the following commands to work:
```yarn search```
```yarn upgrade-interactive```

Can't tell if this is an actual bug or if I installed yarn wrong

### To reproduce

```zsh repro
yarn search
```

Internal Error: Desktop@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:435:5145)
    at kf.getCandidates (/Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:391:1264)
    at /Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:439:8033
    at df (/Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:390:11070)
    at ge (/Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:390:10398)
    at async /Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:439:8545
    at async ti.startProgressPromise (/Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:390:47579)
    at async je.resolveEverything (/Users/user/Desktop/.yarn/releases/yarn-3.6.3.cjs:439:6573)

### Environment

```shell
System:
    OS: macOS 13.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 18.16.0 - /private/var/folders/cq/h_4_95xx0tx2vqngkgxw5n1m0000gn/T/xfs-45bb5dff/node
    Yarn: 3.6.3 - /private/var/folders/cq/h_4_95xx0tx2vqngkgxw5n1m0000gn/T/xfs-45bb5dff/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
```

**Comment by jacoboneill** [comment]
Found the fix. First off make sure you are in version 3.x. On mac, to do this use the command:
`yarn set version stable`.

Then you have to import the "interactive-tools" plugin by using: `yarn plugin import interactive-tools`. This will then allow the CLI tools. I think the documentation should be a bit clearer on the website for the version and the import command.
