### ISSUE TITLE
[Bug?]: Assertion failed: Unsupported workflow

### ISSUE THREAD

**Issue by lunaisnotaboy** [yarnpkg/berry#5715]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Whenever I run `yarn install`, I get the following log:

```
➤ YN0000: ┌ Resolution step
➤ YN0013: │ summaly@https://github.com/misskey-dev/summaly.git#commit=d2d8db49943ccb201c1b1b283e9d0a630519fac7 can't be
➤ YN0013: │ sharp-read-bmp@https://github.com/misskey-dev/sharp-read-bmp.git#commit=02d9dc189fa7df0c4bea09330be26741772
➤ YN0032: │ sharp@npm:0.32.5: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @aws-sdk/node-http-handler@npm:3.374.0 is deprecated: This package has moved to @smithy/node-http-handler
➤ YN0032: │ nan@npm:2.17.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:6.1.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0013: │ sharp-read-bmp@https://github.com/misskey-dev/sharp-read-bmp.git#commit=02d9dc189fa7df0c4bea09330be26741772
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0032: │ msgpackr-extract@npm:3.0.2: Implicit dependencies on node-gyp are discouraged
➤ YN0013: │ summaly@https://github.com/misskey-dev/summaly.git#commit=d2d8db49943ccb201c1b1b283e9d0a630519fac7 can't be
➤ YN0001: │ Error: sharp-read-bmp@https://github.com/misskey-dev/sharp-read-bmp.git#commit=02d9dc189fa7df0c4bea09330be26741772dac01: Assertion failed: Unsupported workflow
    at /home/robert/.cache/node/corepack/yarn/3.6.1/yarn.js:422:1549
    at async $t.mktempPromise (/home/robert/.cache/node/corepack/yarn/3.6.1/yarn.js:314:69436)
    at async /home/robert/.cache/node/corepack/yarn/3.6.1/yarn.js:419:66
    at async $t.mktempPromise (/home/robert/.cache/node/corepack/yarn/3.6.1/yarn.js:314:69436)
    at async /home/robert/.cache/node/corepack/yarn/3.6.1/yarn.js:414:3103
➤ YN0000: └ Completed in 12s 229ms
➤ YN0000: Failed with errors in 12s 247ms
```

### To reproduce

```js
await packageJsonAndInstall({
  dependencies: {
    [`sharp-read-bmp`]: `github:misskey-dev/sharp-read-bmp`
  }
})
```

### Environment

```shell
System:
  OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
Binaries:
  Node: 18.17.0 - /tmp/xfs-f2d94a62/node
  Yarn: 3.6.1 - /tmp/xfs-f2d94a62/yarn
  npm: 9.6.7 - /usr/local/lib/nodejs/node-v18.17.0-linux-x64/bin/npm
```

**Comment by lunaisnotaboy** [comment]
Has there been any update on this?

**Comment by Gitii** [comment]
@lunaisnotaboy It seems that the root cause is missing pnpm support.
https://github.com/yarnpkg/berry/issues/3169#issuecomment-903590194
Do not ask me why but I have the same issue and it's also a pnpm repository.

**Comment by panther7** [comment]
Still issue.

```
yarn add electron-builder@github:electron-userland/electron-builder
```

```
➤ YN0000: · Yarn 4.9.2
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: electron-builder@https://github.com/electron-userland/electron-builder.git#commit=2d014a86050eee16e4092cfce40a1a6e9c9ee474: Assertion failed: Unsupported workflow
```
