### ISSUE TITLE
[Bug?]: 

### ISSUE THREAD

**Issue by TaniaSYSandWEB** [yarnpkg/berry#5735]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

<html>
<body>

Running "vercel build"
--
18:08:45.059 | Vercel CLI 32.2.1
18:08:45.291 | WARN! Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
18:08:46.319 | Warning: Detected "engines": { "node": ">=18.0.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
18:08:46.322 | Installing dependencies...
18:08:47.333 | ➤ YN0000: ┌ Resolution step
18:08:47.787 | ➤ YN0001: │ Error: yarn@npm:^3.6.3: No candidates found
18:08:47.787 | at ge (/vercel/path0/.yarn/releases/yarn-3.6.3.cjs:439:8124)
18:08:47.788 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
18:08:47.788 | at async Promise.allSettled (index 141)
18:08:47.788 | at async io (/vercel/path0/.yarn/releases/yarn-3.6.3.cjs:390:10398)
18:08:47.788 | ➤ YN0000: └ Completed in 0s 454ms
18:08:47.788 | ➤ YN0000: Failed with errors in 0s 458ms
18:08:47.814 | Error: Command "yarn install" exited with 1

</body>
</html>

### To reproduce

When it is run automatically in Vercel it shows this yarn error, because an update from node 14 -> 18

### Environment

```shell
{
    "name": "appname",
    "version": "1.0.0",
    "private": true,
    "engines": {
        "node": ">=18.0.0"
    },
    "scripts": {
        "start:client": "cross-env NODE_ENV=development cross-env BABEL_ENV=web webpack-dev-server --env.env=dev --progress",
        "start:server": "run-p start:devserver start:devplayground",
        "start:devserver": "yarn nodemon src/server/index.js",
        "start:devplayground": "yarn prisma playground",
        "start:bundleanalyzer": "yarn start:client --env.addons=bundleanalyzer",
        "build:preclient": "rimraf dist",
        "build:actualclient": "cross-env NODE_ENV=production cross-env BABEL_ENV=web webpack -p --env.env=prod",
        "build:client": "run-s build:preclient build:actualclient",
        "build": "npm build:client",
        "build-css": "sass src/styles/main.scss dist/styles/main.css",
        "now-build": "npm build",
        "lint": "eslint --ext .js,.jsx",
        "lintfix": "eslint --fix"
    },
    "dependencies": {
        "@date-io/moment": "^1.3.5",
        "@emotion/core": "^10.0.10",
        "@emotion/styled": "^10.3.0",
        "@fortawesome/fontawesome-svg-core": "^1.2.18",
        "@fortawesome/free-brands-svg-icons": "^5.8.2",
        "@fortawesome/free-regular-svg-icons": "^5.8.2",
        "@fortawesome/free-solid-svg-icons": "^5.8.2",
        "@fortawesome/react-fontawesome": "^0.1.4",
        "@hot-loader/react-dom": "^16.8.6",
        "@material-ui/core": "^4.11.0",
        "@material-ui/icons": "^4.5.1",
        "@material-ui/lab": "^4.0.0-alpha.36",
        "@material-ui/pickers": "^3.2.10",
        "@mui/x-date-pickers": "^6.13.0",
        "@react-google-maps/api": "^1.8.8-alpha",
        "axios": "^0.21.1",
        "classnames": "^2.3.1",
        "cleave.js": "^1.4.10",
        "core-js": "3.0.1",
        "express": "^4.17.1",
        "formik": "^1.5.1",
        "globalize": "^0.1.1",
        "greenlet": "^1.0.1",
        "history": "^4.9.0",
        "jsonwebtoken": "^8.5.1",
        "jwt-decode": "^2.2.0",
        "leaflet": "^1.7.1",
        "localforage": "^1.7.3",
        "lodash": "^4.17.11",
        "lodash-decorators": "^6.0.1",
        "lottie-web": "^5.5.2",
        "material-ui-pickers": "^2.2.4",
        "mobx": "^5.9.0",
        "mobx-persist": "^0.4.1",
        "mobx-react": "6.1.1",
        "mobx-react-lite": "^1.4.1",
        "mobx-state-tree": "^3.10.2",
        "mobx-utils": "^5.4.1",
        "moment": "^2.24.0",
        "mui-datatables": "^2.14.0",
        "notistack": "^0.9.7",
        "numeral": "^2.0.6",
        "prop-types": "^15.7.2",
        "query-string": "^6.13.5",
        "react": "^16.9.0",
        "react-delay-render": "^0.1.2",
        "react-dom": "^16.9.0",
        "react-facebook-pixel": "^1.0.4",
        "react-ga": "^3.2.0",
        "react-helmet": "^5.2.1",
        "react-hooks-helper": "^1.6.0",
        "react-hot-loader": "^4.8.4",
        "react-image": "^4.0.3",
        "react-imported-component": "^5.5.3",
        "react-indiana-drag-scroll": "^2.0.1",
        "react-json-view": "^1.19.1",
        "react-messenger-customer-chat": "^0.8.0",
        "react-number-format": "^4.0.7",
        "react-paypal-button-v2": "^2.6.3",
        "react-player": "^2.6.1",
        "react-redux": "^5.0.7",
        "react-responsive-pinch-zoom-pan": "^0.3.0",
        "react-router": "^5.0.1",
        "react-router-dom": "^5.0.1",
        "react-router-redux": "~5.0.0-alpha.9",
        "react-slick": "^0.28.1",
        "react-spinner-children": "^1.0.8",
        "react-table": "^7.7.0",
        "react-transition-group": "^4.3.0",
        "recompose": "^0.30.0",
        "redux": "~3.7.2",
        "redux-form": "~7.4.0",
        "redux-saga": "~0.16.0",
        "request": "^2.88.0",
        "sass": "^1.66.1",
        "shortid": "^2.2.16",
        "slick-carousel": "^1.8.1",
        "swiper": "^6.7.5",
        "use-react-router": "^1.0.7",
        "utf8": "^3.0.0",
        "uuid": "^3.3.2",
        "yarn": "^3.6.3",
        "yup": "^0.27.0"
    },
    "devDependencies": {
        "@babel/cli": "^7.4.4",
        "@babel/core": "^7.4.4",
        "@babel/node": "^7.2.2",
        "@babel/plugin-proposal-class-properties": "^7.4.4",
        "@babel/plugin-proposal-decorators": "^7.4.4",
        "@babel/plugin-proposal-optional-chaining": "^7.2.0",
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@babel/preset-env": "^7.4.4",
        "@babel/preset-react": "^7.0.0",
        "@babel/register": "^7.4.4",
        "@types/cleave.js": "^1.4.0",
        "@types/lodash": "^4.14.124",
        "@types/react": "^16.8.17",
        "@types/react-dom": "^16.8.4",
        "@types/react-router-dom": "^4.3.3",
        "@types/react-table": "^6.8.1",
        "autoprefixer": "^9.5.1",
        "babel-eslint": "^10.0.1",
        "babel-loader": "^8.0.5",
        "babel-plugin-dynamic-import-node": "^2.2.0",
        "babel-plugin-emotion": "^10.0.9",
        "babel-plugin-lodash": "^3.3.4",
        "chalk": "^2.4.2",
        "clean-webpack-plugin": "^2.0.2",
        "copy-webpack-plugin": "^5.0.3",
        "cross-env": "^5.2.0",
        "css-loader": "^2.1.1",
        "dotenv": "^8.0.0",
        "dotenv-webpack": "^1.7.0",
        "eslint": "^5.16.0",
        "eslint-config-airbnb": "^17.1.0",
        "eslint-plugin-import": "^2.17.2",
        "eslint-plugin-jsx-a11y": "^6.2.1",
        "eslint-plugin-react": "^7.13.0",
        "eslint-plugin-react-hooks": "^1.6.0",
        "file-loader": "^3.0.1",
        "html-webpack-plugin": "^3.2.0",
        "husky": "^2.2.0",
        "lerna": "^3.14.1",
        "mini-css-extract-plugin": "^0.6.0",
        "nodemon": "^1.19.0",
        "npm-run-all": "^4.1.5",
        "optimize-css-assets-webpack-plugin": "^5.0.1",
        "postcss-loader": "^3.0.0",
        "rimraf": "^2.6.3",
        "sass-loader": "^7.1.0",
        "shelljs": "^0.8.3",
        "style-loader": "^0.23.1",
        "terser-webpack-plugin": "^1.2.3",
        "typescript": "^3.4.5",
        "url-loader": "^1.1.1",
        "webpack": "^4.30.0",
        "webpack-bundle-analyzer": "^3.3.2",
        "webpack-cli": "^3.3.2",
        "webpack-dev-server": "^3.3.1",
        "webpack-jarvis": "^0.3.2",
        "webpack-md5-hash": "^0.0.6",
        "webpack-merge": "^4.2.1",
        "webpack-stylish": "^0.1.8",
        "webpackbar": "^3.2.0"
    },
    "packageManager": "yarn@3.6.3",
    "description": "**Setup steps**",
    "main": "postcss.config.js",
    "keywords": [],
    "author": "",
    "license": "ISC"
}
```

**Comment by arcanis** [comment]
Not sure why you have `yarn` in your package.json's dependencies, that's a mistake
