### ISSUE TITLE
[Bug?]: yarn install hangs on TS repo, using 100% CPU and a lot of memory, sometimes crashes Zlib

### ISSUE THREAD

**Issue by jakebailey** [yarnpkg/berry#5737]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When adding yarn to the TypeScript repo, `yarn install` hangs, using 100% CPU and a lot of memory.

```
➤ YN0000: · Yarn 4.0.0-rc.50
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @esfx/canceltoken@npm:1.0.0, @octokit/rest@npm:19.0.13, @types/chai@npm:4.3.6, @types/glob@npm:8.1.0, and 395 more
➤ YN0000: └ Completed in 0s 845ms
➤ YN0000: ┌ Fetch step
➤ YN0000: ⠙ ===============================================================================-
```

Sometimes, it crashes with:

```
➤ YN0000: · Yarn 4.0.0-rc.50
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @esfx/canceltoken@npm:1.0.0, @octokit/rest@npm:19.0.13, @types/chai@npm:4.3.6, @types/glob@npm:8.1.0, and 395 more
➤ YN0000: └ Completed in 0s 845ms
➤ YN0000: ┌ Fetch step
➤ YN0001: │ Libzip Error: typescript@patch:typescript@workspace%3A.#optional!builtin<compat/typescript>::version=5.3.0&hash=f3b441: Zlib error: insufficient memory
    at us.makeLibzipError (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:149:194787)
    at us.getBufferAndClose (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:149:195517)
    at us.saveAndClose (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:149:196971)
    at Mv.patchPackage (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:707:1879)
    at async v (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:199:1576)
    at async b (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:199:1916)
    at async E (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:199:3030)
    at async Nr.fetchPackageFromCache (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:199:3151)
    at async Mv.fetch (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:707:1060)
    at async pE.fetch (/home/jabaile/.cache/node/corepack/yarn/4.0.0-rc.50/yarn.js:141:463)
➤ YN0000: └ Completed in 16s 122ms
➤ YN0000: · Failed with errors in 16s 971ms
```

### To reproduce

The sherlock link is broken so I don't quite know how to construct that, but here's a link to a branch where things break: https://github.com/jakebailey/TypeScript/tree/yarn-hang

### Environment

```shell
Er, well, this command fails too:


➤ YN0001: │ Error: EXDEV: cross-device link not permitted, link '/home/jabaile/.local/share/yarn/berry/index/bc/bc5e9c3195095194973fd9732cedd94d4aad5a6d.dat' -> '/tmp/xfs-57527b60/dlx-472010/node_modules/.store/envinfo-npm-7.10.0-cba8c054d4/package/LICENSE'
➤ YN0000: · Failed with errors in 0s 189ms
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EXDEV: cross-device link not permitted, link '/home/jabaile/.local/share/yarn/berry/index/bc/bc5e9c3195095194973fd9732cedd94d4aad5a6d.dat' -> '/tmp/xfs-57527b60/dlx-472010/node_modules/.store/envinfo-npm-7.10.0-cba8c054d4/package/LICENSE'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'link',
  path: '/home/jabaile/.local/share/yarn/berry/index/bc/bc5e9c3195095194973fd9732cedd94d4aad5a6d.dat',
  dest: '/tmp/xfs-57527b60/dlx-472010/node_modules/.store/envinfo-npm-7.10.0-cba8c054d4/package/LICENSE'
}

Node.js v20.6.1
```
```


### Additional context

_No response_

**Comment by merceyz** [comment]
I ran into this a long time ago as well, the issue is Yarn is trying to patch the TypeScript workspace itself to add PnP support which doesn't work.
You can work around it by adding `enableTransparentWorkspaces: false` to your `.yarnrc.yml` file.

**Comment by jakebailey** [comment]
Oh, oops 😄

Yeah, I can understand why this might break!
