### ISSUE TITLE
[Bug?]: yarn install fails during 'Post-resolution validation' after upgrade to 4.0

### ISSUE THREAD

**Issue by eigilsagafos** [yarnpkg/berry#5841]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After upgrading to yarn 4 and running yarn install I get the following error:

```
➤ YN0000: ┌ Post-resolution validation
➤ YN0001: │ TypeError: Cannot read properties of null (reading 'set')
    at /.yarn/releases/yarn-4.0.0.cjs:140:118086
    at Array.map (<anonymous>)
    at sM (/.yarn/releases/yarn-4.0.0.cjs:140:118074)
    at /.yarn/releases/yarn-4.0.0.cjs:207:6475
    at Array.map (<anonymous>)
    at FAt (/.yarn/releases/yarn-4.0.0.cjs:207:6070)
    at /.yarn/releases/yarn-4.0.0.cjs:213:2771
    at Lt.startSectionPromise (/.yarn/releases/yarn-4.0.0.cjs:176:2834)
    at Lt.startTimerPromise (/.yarn/releases/yarn-4.0.0.cjs:176:3734)
    at St.install (/.yarn/releases/yarn-4.0.0.cjs:213:2697)
```

### To reproduce

This is a huge private monorepo. I'm aware that this might get closed due to no way to reproduce, but I am posting in case others have the same issue and could add more context.

Note: The doc link in this issue template to `https://yarnpkg.com/advanced/sherlock` is broken

### Environment

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 19.9.0 - /private/var/folders/1h/8llh51vx1s1g998jrmj8_qg80000gn/T/xfs-68ee2d4f/node
    Yarn: 4.0.0 - /private/var/folders/1h/8llh51vx1s1g998jrmj8_qg80000gn/T/xfs-68ee2d4f/yarn
    npm: 9.6.3 - ~/.local/share/nvm/v19.9.0/bin/npm
```

**Comment by arcanis** [comment]
Hm - can you try running `yarn set version from sources --no-minify` to have a more readable stacktrace and be able to add console.log around the relevant lines?

**Comment by MrDockal** [comment]
Hello I'm having the same problem. Basically, we have two monorepos and I'd like to link packages from one monorepo to another using `yarn link /path/to/package/in/monorepo --all`

After a quick investigation the error occurs here https://github.com/yarnpkg/berry/blob/017b94ae4eb20dea14ac673a053a1f2974b778ff/packages/yarnpkg-core/sources/semverUtils.ts#L207

I can try to reproduce the issue

**Comment by izifortune** [comment]
Having the same issue here we are not using the `workspace:packages/name`

**Comment by noahnu** [comment]
I just run into this as well. I patched Yarn to add some debug logging to see if I can trace down what's happening.

In my code, I was programmatically using Yarn (as part of the [monoweave](https://github.com/monoweave/monoweave) project). In monoweave, we update the version ranges in the package.jsons and then call:

```
await project.install({
    cache,
    report,
    immutable: false,
})
```

it ends up there was a bug in monoweave which caused one of the dependency ranges to be set to a value which produced peer dependency warnings. In emitPeerDependencyWarnings, we collect ranges and pass them to simplifyRanges which ultimates passes each range to validRange:

https://github.com/yarnpkg/berry/blob/2aa53d144c2e0fed8792032ce8655a34116a15f7/packages/yarnpkg-core/sources/Project.ts#L2652C11-L2652C20

one of the peer dependency ranges being passed in was a workspace protocol: `workspace:1.2.3`. This was converted to "null" via validRange which caused the error.

In my case, once I fixed my invalid peer dependencies, the error went away. This does seem to imply some sort of bug or lack of error handling in the emitPeerDependencyWarnings function though.

Full stack trace (semverUtils.js:188 points to validRange).

```
Post-resolution validation
➤ YN0001: │ TypeError: Cannot read properties of null (reading 'set')
    at /home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/semverUtils.js:188:63
    at Array.map (<anonymous>)
    at Object.simplifyRanges (/home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/semverUtils.js:188:33)
    at /home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/Project.js:1982:43
    at Array.map (<anonymous>)
    at emitPeerDependencyWarnings (/home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/Project.js:1969:100)
    at /home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/Project.js:1305:13
    at StreamReport.startSectionPromise (/home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/StreamReport.js:239:26)
    at StreamReport.startTimerPromise (/home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/StreamReport.js:289:21)
    at Project.install (/home/runner/.yarn/berry/cache/@yarnpkg-core-patch-09dbe5b5d6-10.zip/node_modules/@yarnpkg/core/lib/Project.js:1302:27)
➤ YN0000: │ └ Completed
```

**Comment by filipw01** [comment]
I'm still seeing this issue in yarn 4.3.0.

I was on 3.5.1 and upgraded to 4.3.0

I didn't get a chance to dig in deeper, let me know if that's needed.

After running `yarn set version from sources --no-minify` here's the stack trace

```
➤ · Yarn 4.3.0-git.20240610.hash-f1edfae
➤ ┌ Resolution step
➤ │ + octokit@npm:3.1.2, typescript@patch:typescript@npm%3A5.4.5#optional!builtin<compat/typescript>::version=5.4.5&hash=5adc0c, @octokit/app@npm:14.1.0, @octokit/auth-app@npm:6.1.1, @octokit/auth-oauth-app@npm:7.1.0, and 35 more.
➤ │ - @octokit/app@npm:13.1.2, @octokit/auth-app@npm:4.0.9, @octokit/auth-oauth-app@npm:5.0.5, @octokit/auth-oauth-device@npm:4.0.4, @octokit/auth-oauth-user@npm:2.1.1, @octokit/auth-token@npm:3.0.3, and 26 more.
➤ │ TypeError: Cannot read properties of null (reading 'set')
    at /Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:30895:65
    at Array.map (<anonymous>)
    at simplifyRanges (/Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:30895:33)
    at applyVirtualResolutionMutations (/Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:53185:54)
    at Project.resolveEverything (/Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:53851:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:54422:13
    at async StreamReport.startSectionPromise (/Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:45184:20)
    at async Project.install (/Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:54421:11)
    at async /Users/filip/projects/chilipiper/frontend/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:137716:9
➤ └ Completed in 3m 56s
➤ · Failed with errors in 3m 56s
```

**Comment by filipw01** [comment]
I'm still seeing this issue in yarn 4.3.0.

I was on 3.5.1 and upgraded to 4.3.0

I didn't get a chance to dig in deeper, let me know if that's needed.

After running `yarn set version from sources --no-minify` here's the stack trace

```
➤ · Yarn 4.3.0-git.20240610.hash-f1edfae
➤ ┌ Resolution step
➤ │ + octokit@npm:3.1.2, typescript@patch:typescript@npm%3A5.4.5#optional!builtin<compat/typescript>::version=5.4.5&hash=5adc0c, @octokit/app@npm:14.1.0, @octokit/auth-app@npm:6.1.1, @octokit/auth-oauth-app@npm:7.1.0, and 35 more.
➤ │ - @octokit/app@npm:13.1.2, @octokit/auth-app@npm:4.0.9, @octokit/auth-oauth-app@npm:5.0.5, @octokit/auth-oauth-device@npm:4.0.4, @octokit/auth-oauth-user@npm:2.1.1, @octokit/auth-token@npm:3.0.3, and 26 more.
➤ │ TypeError: Cannot read properties of null (reading 'set')
    at /<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:30895:65
    at Array.map (<anonymous>)
    at simplifyRanges (/<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:30895:33)
    at applyVirtualResolutionMutations (/<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:53185:54)
    at Project.resolveEverything (/<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:53851:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:54422:13
    at async StreamReport.startSectionPromise (/<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:45184:20)
    at async Project.install (/<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:54421:11)
    at async /<redacted>/.yarn/releases/yarn-4.3.0-git.20240610.hash-f1edfae.cjs:137716:9
➤ └ Completed in 3m 56s
➤ · Failed with errors in 3m 56s
```

**Comment by filipw01** [comment]
@arcanis I still have the same issue in 4.4.1, should I open a separate issue for this?

**Comment by filipw01** [comment]
On 4.5.1 it started failing with different issue

```
➤ Automatically removed core plugins that are now builtins 👍

➤ Migrated your project to the latest Yarn version 🚀

➤ · Yarn 4.5.1
➤ ┌ Resolution step
➤ ⠸ @types/xmpp__xml@patch:@types/xmpp__xml@npm%3A0.13.1#./.yarn/patches/@types-xmpp__xml-npm-0.13.1-e7192910➤ │ + typescript@patch:typescript@npm%3A5.5.2#optional!builtin<compat/typescript>::version=5.5.2&hash=379a07, and 3 more.
➤ │ - fsevents@patch:fsevents@npm%3A2.3.3#~builtin<compat/fsevents>::version=2.3.3&hash=df0bf1, and 3 more.
➤ │ TypeError: Invalid comparator: workspace:^2.0.0
    at t.parse (/<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:132:35501)
    at new t (/<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:132:35300)
    at /<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:132:31430
    at Array.map (<anonymous>)
    at t.parseRange (/<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:132:31423)
    at /<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:132:30293
    at Array.map (<anonymous>)
    at new t (/<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:132:30281)
    at Object.pGe [as subset] (/<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:132:39680)
    at /<REDACTED>/.yarn/releases/yarn-4.5.1.cjs:140:120210
➤ └ Completed in 26s 605ms
➤ · Failed with errors in 26s 612ms
```

I changed 
```
    "@my-monorepo/dependency": "workspace:^1.10.1 || workspace:^2.0.0"
```
to
```
    "@my-monorepo/dependency": "workspace:^2.0.0"
```

And now it worked
