### ISSUE TITLE
[Bug?]: There is no option called 'auto' for config cacheMigrationMode

### ISSUE THREAD

**Issue by trivikr** [yarnpkg/berry#5856]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

As per documentation, there's an option called `'auto'` for [cacheMigrationMode](https://yarnpkg.com/configuration/yarnrc#cacheMigrationMode) which is set by default.

However, the config does not accept `'auto'` for `cacheMigrationMode`, and the default is `'always'`.

### To reproduce

The default option for `cacheMigrationMode` is always:
```console
$ yarn --version
4.0.0

$ cat .yarnrc.yml
yarnPath: .yarn/releases/yarn-4.0.0.cjs

$ yarn config cacheMigrationMode
└─ cacheMigrationMode
   ├─ Description: Defines the conditions under which Yarn upgrades should cause the cache archives to be regenerated.
   ├─ Source: <default>
   └─ Value: 'always'
```

Explicitly setting `cacheMigrationMode` to `'auto'` fails:
```console
$ yarn config set cacheMigrationMode auto
Internal Error: Invalid value, expected one of always, match-spec, required-only in /Users/trivikram/workspace/test-yarn/.yarnrc.yml (in /Users/trivikram/workspace/test-yarn/.yarnrc.yml)
    at H4 (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:148:1732)
    at Y4 (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:148:904)
    at rA.use (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:148:23241)
    at rA.useWithSource (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:148:22421)
    at rA.find (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:148:17754)
    at async Rh.execute (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:407:1560)
    at async Rh.validateAndExecute (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:94:787)
    at async as.run (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:98:3250)
    at async tPt (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:734:11315)
    at async nk (/Users/trivikram/workspace/test-yarn/.yarn/releases/yarn-4.0.0.cjs:734:11671)
```

### Environment

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.18.0 - /private/var/folders/42/54jl1_3x4hz06cf7bc_kzd4h0000gn/T/xfs-85560da2/node
    Yarn: 4.0.0 - /private/var/folders/42/54jl1_3x4hz06cf7bc_kzd4h0000gn/T/xfs-85560da2/yarn
    npm: 9.8.1 - ~/Library/Caches/fnm_multishells/44911_1698194202141/bin/npm
```

**Comment by trivikr** [comment]
It looks like the option was meant to be added in https://github.com/yarnpkg/berry/pull/5564, but was removed in [`a2c3954` (#5564)](https://github.com/yarnpkg/berry/pull/5564/commits/a2c39544fb3aa3f960f88c863052333ee741a06d)
