### ISSUE TITLE
Implement `yarn pack` and `yarn publish`

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/berry#6]
**Describe the user story**

I'm a package author, and I'd like to publish a package on the npm registry.

**Describe the solution you'd like**

This is a perfect example for a plugin. The best solution would be to implement `yarn pack` and `yarn publish` into their own plugins - this would allow us to iterate much faster on this, for example by adding validation checks on the submitted packages (one could imagine a check to make sure that licenses are correct for example).

**Describe the drawbacks of your solution**

This is a rare case of a feature with no drawback. Our users simply expect to have `yarn publish`, so there will be no surprise.

**Describe alternatives you've considered**

Similarly, not many alternatives available.

**Comment by LaRuaNa** [comment]
Hey @arcanis tried to give that one a go. Followed this [instruction](https://github.com/yarnpkg/berry/blob/master/docs/plugin-system.md) but unfortunately couldn't get nothing else than bunch of errors. Is that document up to date?

Seems like the regex [here](https://github.com/yarnpkg/berry/blob/master/packages/berry-builder/sources/build-plugin.js#L22) doesn't match 'plugin-hello' at all. see -> https://regex101.com/r/hT1J2J/2

Do you have a hint for me?

`❯ yarn @berry-build-plugin
Error: Invalid plugin name "plugin-hello"
    at getNormalizedName (/Users/laruana/Workspace/forks/berry/packages/berry-builder/sources/build-plugin.js:24:11)
    at Command.concierge.command.action [as run] (/Users/laruana/Workspace/forks/berry/packages/berry-builder/sources/build-plugin.js:33:24)
    at /Users/laruana/Workspace/forks/berry/.yarn/cache/@manaflair-concierge-npm-0.10.2-725b73770737cec6aeabe85ac343c02757c83a6fdf4dc321680d9346f31bba17.zip/node_modules/@manaflair/concierge/core/Concierge.js:1207:48
    at _loop (/Users/laruana/Workspace/forks/berry/.yarn/cache/@manaflair-concierge-npm-0.10.2-725b73770737cec6aeabe85ac343c02757c83a6fdf4dc321680d9346f31bba17.zip/node_modules/@manaflair/concierge/core/Concierge.js:69:39)
    at runMaybePromises (/Users/laruana/Workspace/forks/berry/.yarn/cache/@manaflair-concierge-npm-0.10.2-725b73770737cec6aeabe85ac343c02757c83a6fdf4dc321680d9346f31bba17.zip/node_modules/@manaflair/concierge/core/Concierge.js:80:9)
    at Concierge.run (/Users/laruana/Workspace/forks/berry/.yarn/cache/@manaflair-concierge-npm-0.10.2-725b73770737cec6aeabe85ac343c02757c83a6fdf4dc321680d9346f31bba17.zip/node_modules/@manaflair/concierge/core/Concierge.js:1202:34)
    at Concierge.runExit (/Users/laruana/Workspace/forks/berry/.yarn/cache/@manaflair-concierge-npm-0.10.2-725b73770737cec6aeabe85ac343c02757c83a6fdf4dc321680d9346f31bba17.zip/node_modules/@manaflair/concierge/core/Concierge.js:1262:41)
    at Object.<anonymous> (/Users/laruana/Workspace/forks/berry/packages/berry-builder/sources/build-plugin.js:107:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
Error: Command failed: /usr/local/Cellar/node/10.5.0_1/bin/node /Users/laruana/Workspace/forks/berry/packages/berry-builder/sources/build-plugin.js
null
null
    at makeError (/Users/laruana/Workspace/forks/berry/packages/berry-cli/bin/berry.js:66632:9)
    at Promise.all.then.arr (/Users/laruana/Workspace/forks/berry/packages/berry-cli/bin/berry.js:66736:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by arcanis** [comment]
At the moment plugins should be named either `@berry/plugin-something` or `berry-plugin-something` (in the second case any scope will be fine). I forgot to add a settings in the project yarnrc to define the scope when running `yarn init`, so the name is likely wrong! Try to rename your new plugin to `berry-plugin-hello`.

The error message should also make this much clearer - ideally by throwing a `UsageError` when running with an invalid package name 🤔

**Comment by LaRuaNa** [comment]
Hmm. Somehow didn't help much. Get the following error with both options.

```
ERROR in Entry module not found: Error: Can't resolve '.' in '/Users/laruana/Workspace/forks/berry/packages/berry-plugin-hello'
Error: Command failed: /usr/local/Cellar/node/10.5.0_1/bin/node /Users/laruana/Workspace/forks/berry/packages/berry-builder/sources/build-plugin.js
null
null
    at makeError (/Users/laruana/Workspace/forks/berry/packages/berry-cli/bin/berry.js:66632:9)
    at Promise.all.then.arr (/Users/laruana/Workspace/forks/berry/packages/berry-cli/bin/berry.js:66736:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by arcanis** [comment]
Two things:

- Can you pull? I've just noticed a bug in how plugins were loaded, should be fixed now
- You either need to rename your `sources/index.ts` into `index.ts`, or add a `main` field in your package.json file to tell the bundler where is your entry file located in. I've made this clearer in the documentation! 😃

**Comment by LaRuaNa** [comment]
Lovely! Thanks :]

**Comment by LaRuaNa** [comment]
I played a bit around on plugins to get a better understanding of the plugin system. But honestly, I'm a bit lost in the code base and not sure if my approach is the best. Currently, I determine the manifest root via `Configuration.find` and `Project.find`.  And that’s more or less all I could get. Should I archive files via `tgzUtils.makeArchive`? What about writing them on fs is there already some logic or should I handle streams manually? Ignoring dot files? Is there more docs than in /docs? Need a bit your introduction :]

**Comment by olingern** [comment]
@arcanis Sorry to ghost on the `yarn publish`. I have something basic together right now ... okay if I claim this?

**Comment by LaRuaNa** [comment]
Hey @olingern since I already started working my way into that, I wish to keep that one. If it's okay for you :]

**Comment by olingern** [comment]
Sure, I was late getting to opening something meaningful up ... so all yours :slightly_smiling_face:

**Comment by arcanis** [comment]
Hey @olingern - copying it here since I'm not sure you visit Discord everyday 😃 

> @olingern @LaRuaNa hey sorry about the duplicated work :open_mouth: I'm pretty sure we can figure out a way to parallelize things though, don't you think?

> @olingern can you submit a PR? Depending how advanced it is we'll figure out the next steps
Don't worry, there is no shortage of things to do :stuck_out_tongue:

**Comment by arcanis** [comment]
Implemented via #115 and #124 🙂

**Comment by michaelaflores** [comment]
Are there any plans to implement `--dry-run`?

**Comment by zachkirsch** [comment]
+1 I would love a `--dry-run` option

**Comment by merceyz** [comment]
Please open a separate issue for your request
