### ISSUE TITLE
[Bug?]: Syntax error when running shell command

### ISSUE THREAD

**Issue by rChaoz** [yarnpkg/berry#6233]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Create a new `package.json` file with the following script in it:

```json
"thing": "cmd /c copy /Y \".\\node_modules\\.prisma\\client\\*.js\" \".\\node_modules\\@prisma\\client\\\""
```

Then try to run it with `yarn run thing`. Output:

```
Syntax Error: Expected "$", "$(", "$((", "${", "\"", "\\", "\\\n", or [^$"] but end of input found (line 1, column 85).
    at pg (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:12:3213)
    at u8e (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:12:22154)
    at ND (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:12:22327)
    at TE (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:168:1973)
    at x (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:189:2758)
    at C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:189:2942
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Tn.mktempPromise (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:9:44849)
    at async Object.Wb (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:189:2571)
    at async t0.execute (C:\Users\Matei\AppData\Local\node\corepack\yarn\4.1.1\yarn.js:499:2341)

```

### Environment

```shell
System:
  OS: Windows 10 10.0.19045
  CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
Binaries:
  Node: 20.8.0 - ~\AppData\Local\Temp\xfs-2e9c83c0\node.CMD
  Yarn: 4.1.1 - ~\AppData\Local\Temp\xfs-2e9c83c0\yarn.CMD
  npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD

(installed with nvm)
```

**Comment by arcanis** [comment]
The Yarn scripts are run through a [portable Posix-like shell](https://yarnpkg.com/features/scripting#portable-shell), so the command syntax (especially escaping) must be similar to bash.
