### ISSUE TITLE
[Bug?]: Yarn 4 cannot install the packages from github

### ISSUE THREAD

**Issue by DharanBro** [yarnpkg/berry#6240]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Adding the package from github url fails with
```
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0058: │ google-map-react@https://github.com/google-map-react/google-map-react.git#commit=6fe7e11c4f9e2519097eb59f039681ee573efb8f: Packing the package failed (exit code 1, logs can be found here: /private/var/folders/m7/x__rb0q55rq0y56m5klj7j000000gn/T/xfs-d422264e/pack.log)
➤ YN0000: └ Completed in 54s 114ms
➤ YN0000: · Failed with errors in 54s 123ms
```

*pack.log*
```
Packing google-map-react@https://github.com/google-map-react/google-map-react.git#commit=6fe7e11c4f9e2519097eb59f039681ee573efb8f from sources
Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile

➤ YN0000: Downloading https://classic.yarnpkg.com/latest.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-classic.cjs
➤ YN0000: Done in 4s 855ms

yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[5/5] Building fresh packages...
$ run-s build
[31m[1mInternal Error[22m[39m: google-map-react@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Xx.getCandidates (/Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:205:8149)
    at Dd.getCandidates (/Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:141:1311)
    at /Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:210:8409
    at Ky (/Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:140:53916)
    at Fe (/Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:210:8389)
    at async Promise.allSettled (index 0)
    at async Uc (/Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:140:53244)
    at async /Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:210:9140
    at async Qi.startProgressPromise (/Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:140:137284)
    at async Pt.resolveEverything (/Users/user/.volta/tools/image/yarn/4.1.1/bin/yarn.js:210:7138)
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### To reproduce

yarn add google-map-react@https://github.com/google-map-react/google-map-react

### Environment

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 20.12.0 - /private/var/folders/m7/x__rb0q55rq0y56m5klj7j000000gn/T/xfs-c3858d0f/node
    Yarn: 4.1.1 - /private/var/folders/m7/x__rb0q55rq0y56m5klj7j000000gn/T/xfs-c3858d0f/yarn
    npm: 10.5.0 - ~/.volta/tools/image/node/20.12.0/bin/npm
```

**Comment by zach-betz-hln** [comment]
Your yarn version seems to be `Yarn 4.1.1` but `v1.22.19` is used to install this package per your log output. 

Looks like the cause is:

```
Packing google-map-react@https://github.com/google-map-react/google-map-react.git#commit=6fe7e11c4f9e2519097eb59f039681ee573efb8f from sources
Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
```

**Comment by vricosti** [comment]
I have the same kind of error:

```
yarn add 'androidtv-remote@https://github.com/vricosti/androidtv-remote.git#releases'
yarn install
```
When I look inside my node_modules/androidtv-remote the folder inside the dist folder are missing
but when I clone directly in command line I can see my folders and files (pairing/PairingManager.js ....)

`git clone -b releases https://github.com/vricosti/androidtv-remote.git`

**Comment by DharanBro** [comment]
> Your yarn version seems to be `Yarn 4.1.1` but `v1.22.19` is used to install this package per your log output.
> 
> Looks like the cause is:
> 
> ```
> Packing google-map-react@https://github.com/google-map-react/google-map-react.git#commit=6fe7e11c4f9e2519097eb59f039681ee573efb8f from sources
> Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
> ```

Does that mean we can't add a package using yarn v1 in a project that is using v4?

**Comment by zach-betz-hln** [comment]
> Does that mean we can't add a package using yarn v1 in a project that is using v4 via git url?

I don't know.

**Comment by andreiwow2** [comment]
> Does that mean we can't add a package using yarn v1 in a project that is using v4 via git url?

@DharanBro 

Apparently yeah, I had the same problem, and updating my other packages to Yarn 2+ from Yarn 1 fixed the issue, so probably another solution would to be to push dist to github and not `prebuild` it. But since Yarn 2+ can be used with nodeLinker node-modules, I don't see a reason not to update.
