### ISSUE TITLE
[Case Study] Make yarn v2 work with flow

### ISSUE THREAD

**Issue by lhorie** [yarnpkg/berry#634]
**What package is covered by this investigations?**

flow-bin

**Describe the goal of the investigation**

It should be possible to use [flow](https://flow.org/) in a codebase.

**Investigation report**

I've put together a small repo demonstrating that flow doesn't work with yarn v2: https://github.com/lhorie/flow-berry

```
# repro steps
git clone git@github.com:lhorie/flow-berry.git
cd flow-berry
yarn
yarn flow
```

Produces this error:

```
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Object.<anonymous> (/Users/lhorie/Documents/flow-berry/.yarn/cache/flow-bin-npm-0.114.0-2e7dec7caf-1.zip/node_modules/flow-bin/cli.js:14:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at Function.external_module_default.a._load (/Users/lhorie/Documents/flow-berry/.pnp.js:7963:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I've also tried suggestions from [this thread](https://github.com/yarnpkg/yarn/issues/6957), but without success.

**Comment by arcanis** [comment]
This will be difficult (and I won't implement it).

Two blockers:

- Flow is written in OCaml. This means that we cannot mount the zip file system on top of `fs`. Because of that, Flow has to have native support for zip archives. I pushed for it when I was at FB but it never happened, so I don't expect it to change anytime soon.

- FB doesn't use PnP at the moment as they hit integration issues with their Buck setup, and noone really dared to confront it. As an unfortunate side effect, Flow [silently removed support](https://github.com/facebook/flow/commit/87820b8e21e626126e2a8ab7e3a70f253a24bafd) for the custom resolvers a few months ago (in 0.110, apparently).

On the other hand TypeScript is written in JS, so even if they don't support PnP natively (yet, but we're working with them to find an appropriate way that satisfies both sides) we can implement it through [PnPify](https://next.yarnpkg.com/advanced/pnpapi), which simulates a n_m folder.

I realize it's not the answer you hoped for, and I'm really sorry not to have better news in this regard ...

---

One last thing of interest is that @larixer is working on implementing a n_m linker for Yarn 2 (you can follow the development in #470). This will allow your projects to keep using node_modules until you're ready to migrate to PnP. Unfortunately this also means that you won't benefit from the PnP perf, stability improvements, and some features, but ... tradeoffs tradeoffs. At least you'll get the rest of the CLI improvements, and will be able to use the Yarn plugin interface etc.

**Comment by nicolo-ribaudo** [comment]
The first blocker can be easily worked around using `yarn unplug flow-bin`

**Comment by kaushalyap** [comment]
I also need this in order to move to Yarn 2, any workarounds?

**Comment by arcanis** [comment]
The only one is to use the node_modules linker until Flow implements PnP support (if ever):

**.yarnrc.yml**
```yml
nodeLinker: node-modules
```

**Comment by AndrewPardoe** [comment]
The Flow team has no plans to adopt support for Yarn 2 or PNP. The primary use case for Flow at Facebook is in support of React code. The React team has [publicly stated that they have no immediate plans to support Yarn 2](https://twitter.com/cpojer/status/1221094706182049792). There's [a more thorough discussion here](https://twitter.com/sebmck/status/1137059802838757377).

**Comment by sberney** [comment]
> As an unfortunate side effect, Flow silently removed support for the custom resolvers a few months ago (in 0.110, apparently).

Is not at all expected. It took me a long time to hunt down this not-really-a-solution; especially since I came across a few examples of using custom resolvers (which didn't work). It might be useful to have a prominently featured partial list of common tools that *don't* work with yarn 2.

Please make it all work together!

**Comment by arcanis** [comment]
Yep, that's a good idea - we have a [compatibility table](https://yarnpkg.com/features/pnp#caveats-and-work-in-progress), PRs welcome to track tools that are still missing (I'll open one for Flow and React Native myself).

**Comment by ylemkimon** [comment]
I'm not sure why, but I'm unable to reproduce the issue. Flow still cannot resolve any dependencies, but without them, it's working fine.

**Comment by ylemkimon** [comment]
It seems the original issue, `Error: spawn ENOTDIR`, is fixed in `@yarnpkg/cli/2.0.0-rc.28`.

**Comment by merceyz** [comment]
> It seems the original issue, Error: spawn ENOTDIR, is fixed in @yarnpkg/cli/2.0.0-rc.28.

@ylemkimon That would be because Yarn started automatically unplugging dependencies with specific file types in https://github.com/yarnpkg/berry/pull/853 and https://github.com/yarnpkg/berry/pull/912

**Comment by b-jsshapiro** [comment]
Eleven months is kind of a long time. Any hope of a resolution on this? What still needs to be done?

**Comment by nicolo-ribaudo** [comment]
You can help convincing the Flow team to allow using custom resolvers: https://github.com/facebook/flow/issues/8292, https://github.com/facebook/flow/issues/7014

**Comment by psychobolt** [comment]
Had to create a separate sub yarn project to manage my flow dependencies: 

https://github.com/psychobolt/react-pie-menu/tree/master/shared/flow-deps

and [symlink-dir](https://github.com/psychobolt/react-pie-menu/blob/7e351861f3d187188392711ecdd7c490b532c575/flow-typed-update.js#L25) the path to the root.

```
[options]
module.system.node.resolve_dirname=flow-deps-modules
```

Not sure if ideal long term as I plan to switch to full Zero-Install completely, but works for me as I can easily opt-in to `node_modules` and install libraries that ship and support `.flow` files.

**Comment by edoardo-bluframe** [comment]
We use Yarn Berry and PNP in **a lot** of projects where we also use Flow!

Solution - **a little** cumbersome but works:

* Have a root `flow-typed` folder
* Every package has a symlink `flow-typed` => `../flow-typed`
* Use `flow-typed` to install as many types as we can
* Maintain the ones that aren't available in `flow-typed` by hand
* Yeah. **Literally**. Maintain the types for the other packages by hand

It takes awhile but once we have them we have them - and they work!

As let's face it - `flow` isn't gonna support Yarn Berry probably **ever**

Right?
