### ISSUE TITLE
[Bug?]: Yarn v4.3.1 times out on fetch step

### ISSUE THREAD

**Issue by awarrier99** [yarnpkg/berry#6389]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Running `yarn install` with v4.3.1 results in the install hanging perpetually in the fetch step. The only way I have found around this is to delete the `yarn.lock`, which allows the install to work that one time.

### To reproduce

Run `yarn install` with v4.3.1, in a project where a `yarn.lock` has already been generated

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 20.15.0 - /private/var/folders/68/n_bpn5_95ms6ldqw6jnq2_fh0000gn/T/xfs-24dcaba6/node
    Yarn: 4.3.1 - /private/var/folders/68/n_bpn5_95ms6ldqw6jnq2_fh0000gn/T/xfs-24dcaba6/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.15.0/bin/npm
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

### Additional context

<img width="869" alt="Screenshot 2024-07-09 at 10 39 42 AM" src="https://github.com/yarnpkg/berry/assets/17476235/52ba3c3e-d46d-49ad-b46f-8903a655d007">

**Comment by awarrier99** [comment]
Turns out it doesn't just perpetually hang, now that I let it run for long enough, it eventually runs into a timeout. Here is the error I received:
```
➤ YN0001: │ RequestError: connect ETIMEDOUT 166.9.48.21:443
    at ClientRequest.<anonymous> (/Users/awarrier/dev/AnalystTools/analyst-tools-server-node/.yarn/releases/yarn-4.3.1.cjs:147:14258)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at u.emit (/Users/awarrier/dev/AnalystTools/analyst-tools-server-node/.yarn/releases/yarn-4.3.1.cjs:142:14861)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
```

**Comment by awarrier99** [comment]
Apologies I spoke too soon, this appears to be an issue with our Artifactory instance which we are using as our npm registry, rather than with Yarn itself.
