### ISSUE TITLE
[Bug?]: Using @mui/x-data-grid-premium v7 produces emotion error

### ISSUE THREAD

**Issue by Jul13nT** [yarnpkg/berry#6425]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm trying to upgrade @mui/x-data-grid-premium from `6.20.0` to `7.11.1`.

I'm using Yarn `4.3.1` with PnP mode, vite `5.3.3`, rollup `4.18.1`.

After upgrading the data-grid version, I'm getting the following error when I'm trying to build the application with vite:

```
$ yarn build:preprod:service-openapi
vite v5.3.3 building for production...
✓ 1820 modules transformed.
x Build failed in 9.71s
error during build:
../../.yarn/__virtual__/@mui-styled-engine-virtual-619ee54b8b/0/cache/@mui-styled-engine-npm-5.16.4-494372f892-5dbd656aed.zip/node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js (4:9): "CacheProvider" is not exported by "__vite-optional-peer-dep:@emotion/react:@mui/styled-engine", imported by "../../.yarn/__virtual__/@mui-styled-engine-virtual-619ee54b8b/0/cache/@mui-styled-engine-npm-5.16.4-494372f892-5dbd656aed.zip/node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js".
file: /workspaces/mui-x-upgrade-7-styled-error/.yarn/__virtual__/@mui-styled-engine-virtual-619ee54b8b/0/cache/@mui-styled-engine-npm-5.16.4-494372f892-5dbd656aed.zip/node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:4:9

2: 
3: import * as React from 'react';
4: import PropTypes from 'prop-types';
            ^
5: import { CacheProvider } from '@emotion/react';
6: import createCache from '@emotion/cache';

    at getRollupError (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:13827:16)
    at Module.traceVariable (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:14275:29)
    at ModuleScope.findVariable (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:11990:39)
    at FunctionScope.findVariable (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at FunctionBodyScope.findVariable (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at Identifier.bind (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:6908:40)
    at CallExpression.bind (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:4771:28)
    at CallExpression.bind (file:///workspaces/mui-x-upgrade-7-styled-error/.yarn/cache/rollup-npm-4.18.1-ff252ce141-c3c73252fd.zip/node_modules/rollup/dist/es/shared/node-entry.js:9135:15)
```

When starting the dev mode with vite, I'm getting this error:

```
Uncaught Error: Could not resolve "@emotion/styled" imported by "@mui/styled-engine". Is it installed?
    optional-peer-dep:__vite-optional-peer-dep: @mui_x-data-grid-premium.js:266
    __require2 chunk-PLDDJCW6.js:17
    <anonymous> index.js:11
styled-engine:1:6
```

### To reproduce

https://github.com/Jul13nT/mui-x-upgrade-7-styled-error

- `yarn install`
- `yarn build:preprod:service-openapi` or `yarn start:service-openapi` (both produce different error, see above).

### Environment

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  Binaries:
    Node: 20.15.1 - /tmp/xfs-4c14b306/node
    Yarn: 4.3.1 - /tmp/xfs-4c14b306/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v20.15.1/bin/npm
    bun: 1.1.20 - ~/.nvm/versions/node/v20.15.1/bin/bun
```

### Additional context

I opened an issue on MUI-X side (https://github.com/mui/mui-x/issues/13304), but the analysis seems to point to a problem with Yarn because all the packages used declare their dependencies correctly.

**Comment by clemyan** [comment]
There are a number of issues here:

1. You have duplicated dependencies. You should `yarn dedupe` first

2. After you dedupe, you can see there are 2 instances of `@mui/styled-engine`

```
> yarn why -R @mui/styled-engine
└─ service-openapi@workspace:service-openapi/front
   ├─ @mui/material@npm:5.15.21 [e1697] (via npm:^5.15.21 [e1697])
   │  └─ @mui/system@npm:5.16.5 [e1697] (via npm:^5.15.20 [e1697])
   │     └─ @mui/styled-engine@npm:5.16.4 [49910] (via npm:^5.16.4 [49910])
   ├─ @mui/system@npm:5.16.5 [e1697] (via npm:^5.15.20 [e1697])
   └─ @mui/x-data-grid-premium@npm:7.11.1 [e1697] (via npm:^7.11.1 [e1697])
      ├─ @mui/system@npm:5.16.5 [8d972] (via npm:^5.16.5 [8d972])
      │  └─ @mui/styled-engine@npm:5.16.4 [e21d5] (via npm:^5.16.4 [e21d5])
      ├─ @mui/x-data-grid@npm:7.11.1 [8d972] (via npm:7.11.1 [8d972])      
      │  └─ @mui/system@npm:5.16.5 [8d972] (via npm:^5.16.5 [8d972])       
      └─ @mui/x-data-grid-pro@npm:7.11.1 [8d972] (via npm:7.11.1 [8d972])  
         ├─ @mui/system@npm:5.16.5 [8d972] (via npm:^5.16.5 [8d972])       
         └─ @mui/x-data-grid@npm:7.11.1 [8d972] (via npm:7.11.1 [8d972])

> yarn info -AR --virtuals @mui/styled-engine
├─ @mui/styled-engine@npm:5.16.4
│  ├─ Instances: 2
│  ├─ Version: 5.16.4
│  │
│  └─ Dependencies
│     ├─ @babel/runtime@npm:^7.23.9 → npm:7.25.0
│     ├─ @emotion/cache@npm:^11.11.0 → npm:11.11.0
│     ├─ csstype@npm:^3.1.3 → npm:3.1.3
│     └─ prop-types@npm:^15.8.1 → npm:15.8.1
│
├─ @mui/styled-engine@npm:5.16.4 [49910]
│  ├─ Version: 5.16.4
│  │
│  └─ Peer dependencies
│     ├─ @emotion/react@^11.4.1 → npm:11.11.4 [e1697]
│     ├─ @emotion/styled@^11.3.0 → npm:11.11.5 [e1697]
│     ├─ @types/emotion__react@* → ✘
│     ├─ @types/emotion__styled@* → ✘
│     ├─ @types/react@* → ✘
│     └─ react@^17.0.0 || ^18.0.0 → npm:18.3.1
│
└─ @mui/styled-engine@npm:5.16.4 [e21d5]
   ├─ Version: 5.16.4
   │
   └─ Peer dependencies
      ├─ @emotion/react@^11.4.1 → ✘
      ├─ @emotion/styled@^11.3.0 → ✘
      ├─ @types/emotion__react@* → ✘
      ├─ @types/emotion__styled@* → ✘
      ├─ @types/react@* → ✘
      └─ react@^17.0.0 || ^18.0.0 → npm:18.3.1
```

This is because `@mui/x-data-grid-premium` does not declare a peer dependency on `@emotion/react` and `@emotion/styled`, so when the instance of `@mui/styled-engine` under `@mui/x-data-grid-premium` tries to import `@emotion/react`, it will fail to resolve.

3. Yarn *would* have warned you about this, but since `@mui/styled-engine` declares the peer to be optional the warning is suppressed. I don't know MUI but it looks like `@mui/styled-engine` **needs** `@emotion/react` and `@emotion/styled` to work, in which case declaring the peer to be optional is incorrect.

**Comment by Jul13nT** [comment]
Thanks for your investigation!

I can confirm that adding the following to `.yarnrc.yml` fixes the issue:

```
packageExtensions: {
  "@mui/styled-engine@*": {
    dependencies: {
      "@emotion/react": "^11.4.1",
      "@emotion/styled": "^11.3.0",
    }
  },
}
```

I will reopen the issue on MUI side.
