### ISSUE TITLE
[Bug?]: TimeoutOverflowWarning when running PnP project with mocked `Date.now()`

### ISSUE THREAD

**Issue by Actimia** [yarnpkg/berry#6448]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I run my testsuite, which uses [chronokinesis](https://github.com/paed01/chronokinesis) to fix the time for reproducibility, several thousand identical warnings are sent to the console:

```
(node:77) TimeoutOverflowWarning: 145266125147 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
    at new Timeout (node:internal/timers:169:17)
    at setTimeout (node:timers:164:19)
    at ZipOpenFS.limitOpenFiles (/app/.pnp.cjs:22346:36)
    at Timeout._onTimeout (/app/.pnp.cjs:22348:14)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
```

This seems to be connected to some type of PnP access cache.

### To reproduce

Run a file that accesses other modules after running `chronokinesis.freeze()` or similar.

### Environment

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
  Binaries:
    Node: 20.16.0 - /private/var/folders/d7/5jx4ysyx43gfys_6p_psd2qnmwp7ml/T/xfs-137b348d/node
    Yarn: 4.3.1 - /private/var/folders/d7/5jx4ysyx43gfys_6p_psd2qnmwp7ml/T/xfs-137b348d/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
```

**Comment by SheldonWBM** [comment]
A workaround but not a soluton: https://github.com/yarnpkg/berry/issues/6788#issuecomment-2855913517
