### ISSUE TITLE
[Bug?]: Yarn symlink error

### ISSUE THREAD

**Issue by Shobhit0109** [yarnpkg/berry#6506]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

On symlinking ~/.yarn to ~/.cache so that my btrfs snapshots size don't increase by its downlaod cache i got this error in working project.
Expected: As symlinks acts as actual directories so this error shouldn't happens.
Note: Using btrfs subvolumes doesn't cause any errors.

![image](https://github.com/user-attachments/assets/41a6ae6b-0325-4c12-9580-d1845ef0718f)

Error:
/home/shobhit/Documents/projects/web/blogging_app/.pnp.cjs:13844
      Error.captureStackTrace(firstError);
            ^

Error: Your application tried to access styled-jsx, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: styled-jsx (via "styled-jsx/package.json")
Required by: /home/shobhit/Documents/projects/web/blogging_app/.yarn/__virtual__/next-virtual-da40f0adeb/5/.cache/berry/cache/next-npm-14.2.8-5e29f8a979-10c0.zip/node_modules/next/dist/server/

Require stack:
- /home/shobhit/Documents/projects/web/blogging_app/.yarn/__virtual__/next-virtual-da40f0adeb/5/.cache/berry/cache/next-npm-14.2.8-5e29f8a979-10c0.zip/node_modules/next/dist/server/require-hook.js
- /home/shobhit/Documents/projects/web/blogging_app/.yarn/__virtual__/next-virtual-da40f0adeb/5/.cache/berry/cache/next-npm-14.2.8-5e29f8a979-10c0.zip/node_modules/next/dist/bin/next
    at require$$0.Module._resolveFilename (/home/shobhit/Documents/projects/web/blogging_app/.pnp.cjs:13844:13)
    at resolve (node:internal/modules/helpers:190:19)
    at Object.<anonymous> (/home/shobhit/Documents/projects/web/blogging_app/.yarn/__virtual__/next-virtual-da40f0adeb/5/.cache/berry/cache/next-npm-14.2.8-5e29f8a979-10c0.zip/node_modules/next/dist/server/require-hook.js:38:32)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at require$$0.Module._extensions..js (/home/shobhit/Documents/projects/web/blogging_app/.pnp.cjs:13887:33)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at require$$0.Module._load (/home/shobhit/Documents/projects/web/blogging_app/.pnp.cjs:13735:31)
    at Module.require (node:internal/modules/cjs/loader:1311:19)

Node.js v20.17.0

### To reproduce

symlinking any directory in ~/.yarn, ~/.yarn/berry, ~/.yarn/berry/cache to ~/.config or any other location.

### Environment

```shell
System:
    OS: Linux 6.10 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
  Binaries:
    Node: 20.17.0 - /tmp/xfs-e6634e12/node
    Yarn: 4.5.0 - /tmp/xfs-e6634e12/yarn
    npm: 10.8.2 - ~/.local/share/mise/installs/node/lts/bin/npm
```

### Additional context

I am using mise (asdf frontend) for node and yarn installation.
EDIT:  This is happening in pnp mode of yarn.

**Comment by BasixKOR** [comment]
Yarn implements a custom filesystem for PnP, so moving files via symlinks will likely cause trouble. If you want to just save some space, could you try `enableGlobalCache` instead?

**Comment by Shobhit0109** [comment]
Thanks for the solution.
