### ISSUE TITLE
[Bug?]: yarn.lock file is not getting generated

### ISSUE THREAD

**Issue by sadhan46** [yarnpkg/berry#6523]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

"yarn install" isn't generating the yarn.lock file 

I tried to run "yarn example android " for running my android app of react native but it threw an error of
 "Internal Error: rn-ocr1-sdk@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile"
 
 so I entered the command "yarn install" and still the yarn.lock file is not generated which according to internet has a workspace in it 
 
 I'm new to react native side as i'm try to create a sdk of flutter to trigger from react native side through android files
 
 this where my error logs
 
 sadhan@Sadhans-MacBook-Pro rn-ocr1-sdk % yarn example android  

Internal Error: rn-ocr1-sdk@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:435:5145)
    at kf.getCandidates (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:391:1264)
    at /Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:439:8033
    at df (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:390:11070)
    at ge (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:390:10398)
    at async /Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:439:8545
    at async ti.startProgressPromise (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:390:47579)
    at async je.resolveEverything (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:439:6573)
    
    
sadhan@Sadhans-MacBook-Pro rn-ocr1-sdk % yarn install
➤ YN0000: ┌ Resolution step
➤ YN0061: │ rimraf@npm:3.0.2 is deprecated: Rimraf versions prior to v4 are no longer supported
➤ YN0061: │ glob@npm:8.1.0 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0061: │ glob@npm:7.2.3 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0001: │ RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:195:14340)
    at Object.onceWrapper (node:events:635:26)
    at ClientRequest.emit (node:events:532:35)
    at o.emit (/Users/sadhan/Desktop/rn-ocr1-sdk/.yarn/releases/yarn-3.6.1.cjs:190:90286)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)
➤ YN0000: └ Completed in 4m 27s
➤ YN0000: Failed with errors in 4m 27s
➤ YN0061: inflight@npm:1.0.6 is deprecated: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
➤ YN0061: @babel/plugin-proposal-optional-chaining@npm:7.21.0 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
➤ YN0061: @babel/plugin-proposal-class-properties@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
➤ YN0061: rimraf@npm:2.6.3 is deprecated: Rimraf versions prior to v4 are no longer supported
➤ YN0061: @babel/plugin-proposal-nullish-coalescing-operator@npm:7.18.6 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.    

### To reproduce

step 1). npx create-react-native-library@latest rn-login-sdk
step 2). cd rn-login-sdk
step 3). yarn example android

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2
Binaries:
    Yarn : 3.6.1
    node : v22.3.0
    npm: 10.8.1
```

**Comment by arcanis** [comment]
> RequestError: read ECONNRESET

This is a network error, ie an issue on your side.
