### ISSUE TITLE
yarn install not install the library from frog artifactory

### ISSUE THREAD

**Issue by sankar-gp** [yarnpkg/berry#6531]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I'm using yarn 3.6.4 and when I'm trying to install the library from frog artifactory I'm getting error 

following is my yarnrc.yml

npmScopes:
  forculus:
    npmRegistryServer: https://artifactory-na.bing.com/artifactory/api/npm/test-rn-test-npm-stable-local/
    npmPublishRegistry: https://artifactory-na.bing.com/artifactory/api/npm/test-rn-test-npm-stable-local/
    npmAuthToken: SFSFSSFSFSFSFSFSFSF
    npmAlwaysAuth: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs

### To reproduce

yarn install not working, throwing error

### Environment

```shell
CPU: Apple M2 Pro
OS: Version 15.0 (24A335)
```

**Comment by sankar-gp** [comment]
How to install a library from jfrog artifactoy using yarn v3 in react native app?

**Comment by BasixKOR** [comment]
Could you attach the error log as well? I can't help since I (and other contributors) don't have access to your repository.

**Comment by sankar-gp** [comment]
➤ YN0001: │ Error: @fyndus/fynduscommunicator@npm:0.0.3: @fyndus/fynduscommunicator@npm:0.0.3::__archiveUrl=https%3A%2F%2Fartifactory-fyndus.com%3A443%2Fartifactory%2Fapi%2Fnpm%2Ffyndus-rn-fynduscommunicator-npm-stable-local%2F%40fyndus%2Ffynduscommunicator%2F-%2F%40fyndus%2Ffynduscommunicator-0.0.3.tgz isn't supported by any available resolver
    at kf.getResolverByDescriptor (/Users/B412126/.yarn/releases/yarn-3.6.4.cjs:391:1647)
    at kf.getCandidates (/Users/B412126/.yarn/releases/yarn-3.6.4.cjs:391:1235)
    at W0.getCandidates (/Users/B412126/.yarn/releases/yarn-3.6.4.cjs:435:3323)
    at kf.getCandidates (/Users/B412126/.yarn/releases/yarn-3.6.4.cjs:391:1264)
    at /Users/B412126/.yarn/releases/yarn-3.6.4.cjs:439:8033
    at df (/Users/B412126/.yarn/releases/yarn-3.6.4.cjs:390:11070)
    at ge (/Users/B412126/.yarn/releases/yarn-3.6.4.cjs:439:8013)
    at async Promise.allSettled (index 5)
    at async io (/Users/B412126/.yarn/releases/yarn-3.6.4.cjs:390:10398)
➤ YN0000: └ Completed in 7s 28ms
➤ YN0000: Failed with errors in 7s 30ms

**Comment by BasixKOR** [comment]
See #5890

**Comment by sankar-gp** [comment]
@BasixKOR  Can you please provide an detailed sample
