### ISSUE TITLE
[Bug?]: Error: Assertion failed: The locator should have been registered

### ISSUE THREAD

**Issue by b-irsigler** [yarnpkg/berry#6573]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Hi,

We are trying to install some atlaskit packages which fails with **Error: Assertion failed: The locator should have been registered**. We figured that only yarn 1.22.22 will build. Currently, however, we want to use 4.5.0.

Thanks in advance. Best
Bernhard

### To reproduce

Minimal setup **package.json**

```
{
  "name": "test123",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@atlaskit/editor-common": "72.0.0",
  }
}
```

### Environment

  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M3 Pro
  Binaries:
    Node: 20.11.1 - /private/var/folders/qs/21fcps297lq1tjry9cvsc0sm0000gn/T/xfs-ec22ad8c/node
    Yarn: 4.5.0 - /private/var/folders/qs/21fcps297lq1tjry9cvsc0sm0000gn/T/xfs-ec22ad8c/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm

Alternatively:

System:
OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
Binaries:
Node: 20.11.0 - /tmp/xfs-b9afdeec/node
Yarn: 4.5.0 - /tmp/xfs-b9afdeec/yarn
npm: 10.5.0 - ~/.nvm/versions/node/v20.11.0/bin/npm

or

System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 20.11.0 - /tmp/xfs-fdc72878/node
    Yarn: 4.5.1 - /tmp/xfs-fdc72878/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm

### Additional context

Complete logs:

➤ YN0002: │ test123@workspace:. doesn't provide @emotion/react (p0dda0), requested by @atlaskit/media-viewer.
➤ YN0002: │ test123@workspace:. doesn't provide react (p9e4a5), requested by @atlaskit/editor-common and other dependencies.
➤ YN0002: │ test123@workspace:. doesn't provide react-dom (pd5054), requested by @atlaskit/editor-common.
➤ YN0002: │ test123@workspace:. doesn't provide react-intl-next (pb572b), requested by @atlaskit/editor-common and other dependencies.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0001: │ Error: Assertion failed: The locator should have been registered
    at /home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:210:11433
    at /home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:140:55074
    at Array.map (<anonymous>)
    at Fs (/home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:140:55067)
    at t.fetchEverything (/home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:210:11348)
    at /home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:213:4080
    at Rt.startSectionPromise (/home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:176:2834)
    at Rt.startTimerPromise (/home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:176:3734)
    at t.install (/home/user/temp/test/.yarn/releases/yarn-4.5.0.cjs:213:4028)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 1s 562ms

**Comment by zemlint** [comment]
Hi,

I'm a colleague of @b-irsigler. 

The Problem seems to be resolvable by adding the following two dependencies to the `package.json`
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@atlaskit/editor-common": "72.0.0",
    "react-focus-lock": "^2.9.5",
    "react-focus-lock-next": "npm:react-focus-lock@^2.13.2"
  },
  "packageManager": "yarn@4.5.1"
}
```
We these additional information can you help investigate the bug.

**Comment by dstengele** [comment]
The following minimal setup triggers the error message:

package.json
```json
{
  "name": "test",
  "packageManager": "yarn@4.5.1",
  "dependencies": {
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
    "react-focus-lock": "2.13.2",
    "subpackage": "file:./subpackage"
  }
}
```

subpackage/package.json
```json
{
    "name": "subpackage",
    "version": "1.0.0",
    "packageManager": "yarn@4.5.1",
    "dependencies": {
        "react-focus-lock": "2.13.2",
        "react-focus-lock-next": "npm:react-focus-lock@2.13.2"
    },
    "peerDependencies": {
        "react": "^16.8.0 || ^17.0.0 || ^18.0.0"
    }
}
```

If you remove the peerDependencies from `subpackage`, the install works. Same for any one of the dependencies on react-focus-lock.

Could this be related to #1352? It seems to have something to do with two dependencies with different names which resolve to the same package and version. In this case, this would be @atlaskit/drawer, which is the connection to react-focus-lock:
```
"react-focus-lock": "^2.9.5",
"react-focus-lock-next": "npm:react-focus-lock@^2.13.2",
```
Both resolve to react-focus-lock@2.13.2.

In my case, where the error was triggered by depending on @atlaskit/editor-core, I was able to work around it by setting the resolutions for the two package names to two distinct versions:
```json
"resolutions": {
    "react-focus-lock": "npm:react-focus-lock@2.13.1",
    "react-focus-lock-next": "npm:react-focus-lock@2.13.2"
}
```
