### ISSUE TITLE
[Bug?]: Invalid descriptor

### ISSUE THREAD

**Issue by Droutin** [yarnpkg/berry#6576]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Cant install packages with yarn 4.5.1 in docker node-alpine

```
 => ERROR [7/7] RUN yarn install --immutable                                                                                        1.1s
------
 > [7/7] RUN yarn install --immutable:
0.636 ! Corepack is about to download https://repo.yarnpkg.com/4.5.1/packages/yarnpkg-cli/bin/yarn.js
1.053 Internal Error: Invalid descriptor ()
1.053     at lh (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:140:111191)
1.053     at t.setupResolutions (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:210:1274)
1.053     at async t.find (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:207:10477)
1.053     at async xE.execute (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:456:16685)
1.053     at async xE.validateAndExecute (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:94:787)
1.053     at async t.run (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:98:3249)
1.053     at async HDt (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:744:7743)
1.053     at async Lk (/root/.cache/node/corepack/v1/yarn/4.5.1/yarn.js:745:142)
------
```

### To reproduce

docker build -t mre .

[mre.zip](https://github.com/user-attachments/files/17521328/mre.zip)

### Environment

  System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Binaries:
    Node: 20.18.0 - ~\AppData\Local\Temp\xfs-62e8fb79\node.CMD
    Yarn: 4.5.1 - ~\AppData\Local\Temp\xfs-62e8fb79\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.33 - ~\.bun\bin\bun.EXE

**Comment by crashzky** [comment]
same

**Comment by clemyan** [comment]
Your lockfile is corrupt -- the first entry has an empty key
