### ISSUE TITLE
[Bug?]: yarn import doesn't run if you don't have a yarn.lock file

### ISSUE THREAD

**Issue by ekasprzyk** [yarnpkg/berry#6621]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

yarn import doesn't run if you don't have a yarn.lock file.

```
yarn import
Internal Error: @nx-next/source@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Zb.getCandidates (/Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:205:8149)
    at vd.getCandidates (/Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:141:1311)
    at /Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:210:8334
    at Wy (/Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:140:53918)
    at be (/Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:210:8314)
    at async Promise.allSettled (index 0)
    at async Uc (/Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:140:53246)
    at async /Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:210:9065
    at async Qi.startProgressPromise (/Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:140:137286)
    at async St.resolveEverything (/Users/ela/.volta/tools/image/yarn/4.0.0/bin/yarn.js:210:7063)
```

### To reproduce

Repro: run `npx create-nx-workspace@latest --preset=next` and create a new project.

cd and attempt to adopt the project into yarn 4.x

### Environment

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 22.11.0 - /private/var/folders/v3/_r20j3ys1cq4zq90vkfgjq0r0000gn/T/xfs-3575bdc6/node
    Yarn: 4.5.3 - /private/var/folders/v3/_r20j3ys1cq4zq90vkfgjq0r0000gn/T/xfs-3575bdc6/yarn
    npm: 10.9.0 - ~/.volta/tools/image/node/22.11.0/bin/npm
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

**Comment by arcanis** [comment]
`yarn import` is a legacy command that doesn't exist in modern releases of Yarn. The error you see is caused by Yarn running `yarn run import` instead (since `yarn import` doesn't exist), and `yarn run` does require the project to be installed.
