### ISSUE TITLE
[Bug] 2.0.0-rc.21 not work

### ISSUE THREAD

**Issue by zdm** [yarnpkg/berry#664]
Something wrong with the 2.0.0-rc.21, it not working completely under windows.
How I can install rc-19?

```yarn install``` finished without errors, but I can't execute any scrip. Below the example of the error:
```
d:\gdrive\projects\workspace\softvisio-eslint-config>yarn lint
Error: Cannot read config file: C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\conf\eslint-recommended.js
Error: Cannot find module 'C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\conf\eslint-recommended.js'
Require stack:
- C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\lib\cli-engine\noop.js
Require stack:
- C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\lib\cli-engine\noop.js
Referenced from: d:\gdrive\projects\workspace\softvisio-eslint-config\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.module_1.Module._resolveFilename (d:\gdrive\projects\workspace\.pnp.js:20033:54)
    at resolveFileName (C:\Users\zdm\.yarn\global\cache\resolve-from-npm-4.0.0-f758ec21bf-1.zip\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Users\zdm\.yarn\global\cache\resolve-from-npm-4.0.0-f758ec21bf-1.zip\node_modules\resolve-from\index.js:43:9)
    at module.exports (C:\Users\zdm\.yarn\global\cache\resolve-from-npm-4.0.0-f758ec21bf-1.zip\node_modules\resolve-from\index.js:46:41)
    at module.exports (C:\Users\zdm\.yarn\global\cache\import-fresh-npm-3.2.1-b4f6711244-1.zip\node_modules\import-fresh\index.js:13:19)
    at loadJSConfigFile (C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\lib\cli-engine\config-array-factory.js:201:16)
    at loadConfigFile (C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\lib\cli-engine\config-array-factory.js:284:20)
    at ConfigArrayFactory._loadConfigData (C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\lib\cli-engine\config-array-factory.js:496:13)
    at ConfigArrayFactory._loadExtendedBuiltInConfig (C:\Users\zdm\.yarn\global\cache\eslint-npm-6.8.0-d27045f313-1.zip\node_modules\eslint\lib\cli-engine\config-array-factory.js:753:25)

```

**Comment by arcanis** [comment]
I've released a lot of fixes lately but since there is no Sherlock script I can't check whether the problem got fixed 🤔 I'll close this issue, please open a new one if something is still off!
