### ISSUE TITLE
[Bug] Deleting yarn.lock causes install to fail

### ISSUE THREAD

**Issue by accidentaldeveloper** [yarnpkg/berry#772]
- [ ] I'd be willing to implement a fix

**Describe the bug**

Removing yarn.lock causes install to fail instead of generating a new yarn.lock.

Error message is:
```
Internal Error: Assertion failed: The package should have been detected as part of the project
    at Function.find (C:\Users\Michael\Source\experiment\.yarn\releases\yarn-berry.js:36:574360)
    at async c.execute (C:\Users\Michael\Source\experiment\.yarn\releases\yarn-berry.js:58:22393)
    at async c.validateAndExecute (C:\Users\Michael\Source\experiment\.yarn\releases\yarn-berry.js:24:40434)
    at async c.run (C:\Users\Michael\Source\experiment\.yarn\releases\yarn-berry.js:36:533800)
    at async c.runExit (C:\Users\Michael\Source\experiment\.yarn\releases\yarn-berry.js:36:533934)
```

**To Reproduce**

```
yarn init
yarn policies set-version berry
yarn
del yarn.lock
yarn
```

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version 13.7.0
 - Yarn version 2.0.0-rc.27

**Additional context**

**Comment by accidentaldeveloper** [comment]
I just realized that this is the same issue as #755 . I also had a yarn.lock in my user directory. Deleting it resolved the error.

**Comment by egml** [comment]
Having **package.json** in user directory also causing this issue. Deleting fixes it.
