### ISSUE TITLE
[Bug] @yarnpkg/doctor fails after adding a yarn plugin

### ISSUE THREAD

**Issue by joshmeads** [yarnpkg/berry#841]
- [ ] I'd be willing to implement a fix

**Describe the bug**

After install a yarn plugin, `yarn dlx @yarnpkg/doctor` will fail to execute with the following:

```
yarn dlx @yarnpkg/doctor

➤ YN0000: ┌ Resolution step
➤ YN0002: │ @yarnpkg/plugin-version@npm:2.0.0-rc.20 [10f20] doesn't provide @types/react@>=16.8.0 requested by ink@npm:2.6.0
➤ YN0000: └ Completed in 2.42s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.2s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0.42s
➤ YN0000: Done with warnings in 3.06s

➤ YN0000: Found 3 package(s) to process
➤ YN0000: For a grand total of 14 file(s) to validate

➤ YN0000: ┌ /Users/josh0.05spackage.json
➤ YN0001: │ UsageError: This plugin cannot access the package referenced via @yarnpkg/cli which is neither a builtin, nor an exposed entry (when initializing @yarnpkg/plugin-workspace-tools, defined in /Users/josh/project/.yarnrc.yml)
    at pluginRequire (/Users/josh/.yarn/berry/cache/@yarnpkg-core-npm-2.0.0-rc.22-22619c9c59-1.zip/node_modules/@yarnpkg/core/lib/Configuration.js:536:31)
    at Object.<anonymous> (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:448:20)
    at __webpack_require__ (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:25:32)
    at Object.<anonymous> (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:150:17)
    at __webpack_require__ (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:25:32)
    at Object.<anonymous> (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:109:37)
    at __webpack_require__ (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:25:32)
    at /Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:89:20
    at factory (/Users/josh/project/.yarn/plugins/@yarnpkg/plugin-workspace-tools.js:92:12)
    at /Users/josh/.yarn/berry/cache/@yarnpkg-core-npm-2.0.0-rc.22-22619c9c59-1.zip/node_modules/@yarnpkg/core/lib/Configuration.js:540:39
➤ YN0000: └ Completed in 0.05s
```

**To Reproduce**

```
yarn plugin import workspace-tools
yarn dlx @yarnpkg/doctor
```

Works as expected if plugins are removed from `.yarnrc.yml`

**Environment if relevant (please complete the following information):**

 - OS: OSX
 - Node version: 13.7.0
 - Yarn version: 2.0.0-rc.27

**Comment by jakegibson** [comment]
This would be very helpful for us as we leverage ~40 workspaces in our serverless monorepo.  Current ugly work around is commenting out our plugins and running a script that cds into every workspace to run doctor as running it from the root  gives false positives.  Does anyone have a cleaner workaround? I would like to help with the fix but won't have time to dig into it for a week or two.
