### ISSUE TITLE
[Bug] .yarnrc generated in Windows includes yarn_path containing "\\" instead of "/"

### ISSUE THREAD

**Issue by exKAZUu** [yarnpkg/berry#858]
- [x] I'd be willing to implement a fix

**Describe the bug**

.yarnrc generated in Windows includes `yarn_path` containing "\\" instead of "/", e.g., `yarn-path ".yarn\\releases\\yarn-berry.js"`.
However, this causes a problem where a non-Windows environment cannot launch `berry` as follows.

```
$ yarn
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/mnt/c/XXX/.yarn\releases\yarn-berry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**To Reproduce**

1. Create a npm package with Yarn v1
1. `yarn policies set-version berry`

We cannot reproduce this issue in Sherlock because this issue occured only on Windows,

**Screenshots**

There is no applicable thing.

**Environment if relevant (please complete the following information):**

 - OS: Windows
 - Node version v13.3.0
 - Yarn version 2.0.0-rc.28

**Additional context**

Nothing.

**Comment by exKAZUu** [comment]
Oops, this seems due to https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/policies.js#L158, so should I move this issue into https://github.com/yarnpkg/yarn ...?

**Comment by exKAZUu** [comment]
Duplicated to https://github.com/yarnpkg/yarn/issues/7777

**Comment by exKAZUu** [comment]
Fixed in https://github.com/yarnpkg/yarn/pull/7862
