### ISSUE TITLE
[Bug] Cannot apply hunk #1 - fsevents

### ISSUE THREAD

**Issue by mikecousins** [yarnpkg/berry#911]
- [ ] I'd be willing to implement a fix

**Describe the bug**

When you try to run yarn install it fails with "Cannot apply hunk #1" on the fsevents package.

**To Reproduce**

Run `yarn` on basically any javascript project.

**Screenshots**

```
C:\GitHub\passiv-web [master ≡]> yarn
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.0.7: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.0.7: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:1.2.11: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:1.2.11: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ nan@npm:2.14.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ passiv-web@workspace:. doesn't provide eslint@>= 3.2.1 requested by eslint-plugin-cypress@npm:2.8.1
➤ YN0002: │ react-plaid-link@npm:1.5.0 [ed127] doesn't provide prop-types@>=15 requested by react-load-script@npm:0.0.6
➤ YN0000: └ Completed in 7.48s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ fsevents@patch:fsevents@npm%3A2.0.7#builtin<compat/fsevents>::version=2.0.7&hash=e8cd9e can't be found in the cache and will be fetched from the disk
➤ YN0001: │ Error: fsevents@patch:fsevents@npm%3A2.0.7#builtin<compat/fsevents>::version=2.0.7&hash=e8cd9e: Cannot apply hunk #1
    at c (C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:58:888149)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:58:890280
    at async o (C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:58:887432)
    at async Object.t.applyPatchFile (C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:58:890253)           at async t.PatchFetcher.patchPackage (C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:58:887187)       at async C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:58:886444
    at async C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:36:569449
    at async C:\Users\mikec\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:36:569392
➤ YN0000: └ Completed in 1.27s
➤ YN0000: Failed with errors in 8.75s
C:\GitHub\passiv-web [master ≡]>
```

**Environment if relevant (please complete the following information):**

 - OS: Windows 10 latest
 - Node version: 13.6.0
 - Yarn version 2.0.0-rc27

**Additional context**

This was already reported once (#719) and closed in error because someone else mentioned the typescript library in the comments.

**Comment by arcanis** [comment]
Thanks! But I'll close it since I actually fixed both `typescript` and `fsevents` in the same PR since they were similar issues 🙂

Try master with `yarn set version from sources && yarn install`.
